### ISSUE TITLE
Ideas for logo

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/effectsize#1]
What could be the content of the logo? The current metaphor of easystats is the monster (representing raw R stats or models, and easystats provide tools to hunt the monsters). Hence 'parameters' is represented by the measure of the claws of a monster (its "parameters"), performance via grades given to a monster etc.

Any ideas for effect size?

**Comment by mattansb** [comment]
Two monsters standing on their tip-toes next to each other, comparing their heights in a line-up (representing a difference between means)?

Or

A monster taking a bite from a pie-chart (representing variance explained)?

**Comment by DominiqueMakowski** [comment]
haha love it! 'til now I managed to find the monsters base images on google, and then edit them with illustrator. But finding two different ones tip-toes might be tough... maybe someone has some drawing skillz?

**Comment by mattansb** [comment]
I can draw a bit, but the tip-toe ones is a bit much...

But the pie one: 

![IMG_20191008_121252](https://user-images.githubusercontent.com/35330040/66383355-832b6880-e9c5-11e9-8d80-d5b092eed00d.jpg)

**Comment by DominiqueMakowski** [comment]
👍 for the pie chart if we make it look like a pizza 🍕 😁

**Comment by mattansb** [comment]
I'll do my best ^_^

**Comment by DominiqueMakowski** [comment]
With a picture of a drawing with a nice black n white contrast, I can easily vectorize with illustrator and then add the colours etc ☺️

**Comment by mattansb** [comment]
In your inbox

**Comment by DominiqueMakowski** [comment]
I've iterated a bit on your design to make it look kinder (yours was super evil 😈 😄) what do you think?

**Comment by mattansb** [comment]
Love it! 
(I think maybe you can drop the "variance explained"?)

**Comment by DominiqueMakowski** [comment]
true, as it is too small anyway... the hidden meaning of the logo will be something the initiated members will slowly discover 😁

**Comment by strengejacke** [comment]
1) do we also want the package to compute effect sizes for meta analysis, like https://strengejacke.github.io/esc/?
