### ISSUE TITLE
Interpret indices of fit improvements 

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/effectsize#100]
https://twitter.com/MelissaGWolf/status/1280533129057337344?s=19

For future ref

**Comment by mattansb** [comment]
This is their app: https://dynamicfit.app/cfa/

**Comment by mattansb** [comment]
@DominiqueMakowski I'm not sure we can actually implement this without porting over the whole app. Maybe we can just link to the paper / app instead?

**Comment by mattansb** [comment]
@DominiqueMakowski should I add a link to the docs and close this?

**Comment by strengejacke** [comment]
I'd vote for yes.

**Comment by DominiqueMakowski** [comment]
Yup
