### ISSUE TITLE
pseudo-standardized parameters for (G)LMMs

### ISSUE THREAD

**Issue by mattansb** [easystats/effectsize#105]
From Hoffman, 2015:
![image](https://user-images.githubusercontent.com/35330040/87931518-9f028580-ca92-11ea-8e33-0e76b3d38d3d.png)

I guess this would be incorporated as a new column in `effectsize::standardize_info()`, which would need to:

1. Detect which parameters represent within/between effects (or which level an effect is on)
2. Fit an empty `lmer()` for the outcome and each predictor.
3. Get relevant variance from (2) models for each effect according to (1).

This would also be a new option in `effectsize::standardize_parameters(..., method = "pseudo")`

**Comment by strengejacke** [comment]
@ 1: could possibly be done with [`parameters::check_heterogeneity()](https://easystats.github.io/parameters/reference/demean.html).

Would like to know where numbers actually refer to, to better understand the formula. Is it the Hoffmann-book?

**Comment by mattansb** [comment]
Yes, Hoffman 2015, page 342

**Comment by mattansb** [comment]
``` r

m <- lme4::lmer(mpg ~ cyl + am + vs + (1|cyl), mtcars)
#> boundary (singular) fit: see ?isSingular
effectsize::standardize_parameters(m, method = "pseudo")
#> Parameter   | Coefficient (std.) |         95% CI
#> -------------------------------------------------
#> (Intercept) |                    |               
#> cyl         |              -0.74 | [-1.25, -0.23]
#> am          |               0.40 | [-0.01,  0.81]
#> vs          |               0.12 | [-0.29,  0.52]
#> 
#> # Standardization method: Pseudo

effectsize::standardize_parameters(m, method = "basic")
#> Parameter   | Coefficient (std.) |         95% CI
#> -------------------------------------------------
#> (Intercept) |               0.00 | [ 0.00,  0.00]
#> cyl         |              -0.63 | [-1.07, -0.20]
#> am          |               0.25 | [-0.01,  0.51]
#> vs          |               0.11 | [-0.27,  0.49]
#> 
#> # Standardization method: Basic
```

<sup>Created on 2020-09-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mattansb** [comment]
Note for posterity:

There are 2 methods of estimating the `sd` of the X variables:
1. Compute, arithmatically, the `sd()` on the correct level (with `parameters::demean()`):
  A. For level 1 - get `sd` of *X<sub>de-meaned</sub>*
  B. For level 2 - get `sd` of *X<sub>group-mean</sub>*
2. For each X, build an LMM `X ~ (1|id)`, and get the right variance component:
  A. For level 1 - get `sqrt` of *Var<sub>residual</sub>*
  A. For level 2 - get `sqrt` of *Var<sub>intercept</sub>*

I have chosen the first option, for 2 reasons:
1. It is more stable (due to shrinkage, the **estimated** level 2 variance can shrink down to 0 when there is high level 1 variance). 
2. In "regular" regressions, the predictors are assumed to be "fixed" (not a random variable), so I saw no reason to break with that idea (wrong as it may be) here.
