### ISSUE TITLE
ci() for standardized coefficients

### ISSUE THREAD

**Issue by strengejacke** [easystats/effectsize#11]
I have implemented se/ci for post-hoc standardized coefficients, is this feature already in _effectsize_?

See news in _parameters_:

> - Standard errors for standardized parameters in `parameters_standardize()` are added as attribute, when `method = "classic"` or `method = "smart"`. There is a `ci()` method for those objects that conveniently prints confidence intervals for standardized coefficients.

**Comment by strengejacke** [comment]
I think it's in, right?

**Comment by DominiqueMakowski** [comment]
The ci method?

**Comment by strengejacke** [comment]
se would be enough, the `ci()` method is actually in parameters (depending on the class).

**Comment by strengejacke** [comment]
But most important is that SE are returned.

**Comment by DominiqueMakowski** [comment]
https://github.com/easystats/effectsize/blob/master/R/standardize_parameters.R#L220

It seems like it
