### ISSUE TITLE
CI argument of the phi() function does not work

### ISSUE THREAD

**Issue by qinyuxiao** [easystats/effectsize#111]
It seems that the CI argument in the phi() function does not work as expected. Regardless of what the input is, it always generates 95% CI.

For example:
```
observed <- rbind(c(20, 3), c(24, 15))
phi.ci <- effectsize::phi(x = observed, CI = 0.60)
```
still generates the 95% CI instead of the 60% CI.

**Specifiations:**
 - `R` Version 4.0.2
 - `effectsize` Version 0.3.2

**Comment by mattansb** [comment]
Nice catch!

``` r
observed <- rbind(c(20, 3), c(24, 15))
effectsize::phi(x = observed, CI = 0.60)
#> Warning in effectsize::phi(x = observed, CI = 0.6): 'CI' argument is deprecated.
#> Use 'ci' instead.
#>  Phi |       60% CI
#> -------------------
#> 0.27 | [0.16, 0.38]
```

<sup>Created on 2020-08-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
