### ISSUE TITLE
CRAN V0 Release

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/effectsize#12]
This is the next CRAN submission. 

- [x] Should we release it as version 0.0.1? Because IMO it's not a "real" release but rather a prerelease (as it cannot be fully used as is, requiring a version of parameters superior to what it will officially state).
- [x] Check documentation
- [x] Check description
- [x] ...?

**Comment by strengejacke** [comment]
can we merge and build website to check the docs?

**Comment by DominiqueMakowski** [comment]
I'll do a final check tomorrow morning and submit if everything seems in order :)

**Comment by DominiqueMakowski** [comment]
Winbuilder doesn't like that it uses non-available functions

```
* installing *source* package 'effectsize' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error: object 'dof' is not exported by 'namespace:parameters'
Execution halted
ERROR: lazy loading failed for package 'effectsize'
```

**Comment by strengejacke** [comment]
replace it with something like `stats::residuals()` for now, or even more secure: `insight::n_obs() - nrow(insight::get_parameters())`, and fix it the next update?

**Comment by DominiqueMakowski** [comment]
I think I'll just comment it out, as the function that uses it (convert_posterior) was not really finished anyway, so it will be for the next update

**Comment by strengejacke** [comment]
sounds good.

**Comment by strengejacke** [comment]
oh my beloved `standardize()`...

![giphy](https://user-images.githubusercontent.com/26301769/67263298-f47c1880-f4a7-11e9-917f-53c16575ae63.gif)

**Comment by DominiqueMakowski** [comment]
GIMME those greenlights

**Comment by strengejacke** [comment]
Does the master pass on winbuilder?

**Comment by DominiqueMakowski** [comment]
yup

**Comment by strengejacke** [comment]
But I think since there were only these URL issues left, it should be fixed now... So...

GO!

**Comment by DominiqueMakowski** [comment]
submitted 🤞

**Comment by DominiqueMakowski** [comment]
(still no answer, but automated checks passed without any problem)

**Comment by strengejacke** [comment]
Initial submissions always take some time, because someone does a manual inspection anyway, despite all passing checks.

**Comment by DominiqueMakowski** [comment]
Please reduce the title to less than 65 chars.

Please always add all authors and copyright holders in the Authors@R
field with the appropriate roles.
 From CRAN policies you agreed to:

"The ownership of copyright and intellectual property rights of all
components of the package must be clear and unambiguous (including from
the authors specification in the DESCRIPTION file). Where code is copied
(or derived) from the work of others (including from R itself), care
must be taken that any copyright/license statements are preserved and
authorship is not misrepresented.
Preferably, an ‘Authors@R’ would be used with ‘ctb’ roles for the
authors of such code. Alternatively, the ‘Author’ field should list
these authors as contributors.
Where copyrights are held by an entity other than the package authors,
this should preferably be indicated via ‘cph’ roles in the ‘Authors@R’
field, or using a ‘Copyright’ field (if necessary referring to an
inst/COPYRIGHTS file)."
e.g. David Stanley, Ken Kelley
Please explain in the submission comments what you did about this issue.


\dontrun{} should be only used if the example really cannot be executed
(e.g. because of missing additional software, missing API keys, ...) by
the user. That's why wrapping examples in \dontrun{} adds the comment
("# Not run:") as a warning for the user.
Does not seem necessary.
Please unwrap the examples if they are executable in < 5 sec, or create
additionally small toy examples to allow automatic testing.
(You could also replace \dontrun{} with \donttest if it takes longer
than 5 sec to be executed, but it would be preferable to have automatic
checks for functions.)

Please fix and resubmit.

**Comment by strengejacke** [comment]
![giphy](https://user-images.githubusercontent.com/26301769/67688091-92d11800-f999-11e9-93b4-5a4e1d9f25bf.gif)

**Comment by strengejacke** [comment]
Can we let examples in `?F_to_partial_eta_squared` also run normally, or is there a reason why these are wrapped in `\donttest{}`?

**Comment by DominiqueMakowski** [comment]
Let's resolve #17 before I resubmit

**Comment by DominiqueMakowski** [comment]
submitted 🤞

**Comment by DominiqueMakowski** [comment]
longest release ever... (still waiting)

**Comment by strengejacke** [comment]
yeah, up to ten days for initial releases (and you needed to resubmit initial release, which will reset the queue...) Have you written some comments in the submission field? This typically increases resubmission slightly, so they can check if and how you addressed their remarks.

**Comment by DominiqueMakowski** [comment]
Yep, I did copy their comments and the answer :) I suspect them to have introduced an algorithm to automatically requeue all easystats packages ^^

**Comment by strengejacke** [comment]
Hope fully this gets on CRAN soon, because there are some packages that need to be updated (due to CRAN check issues from other updated packages, probably mgcv or so) in a certain order. However, this all requires _effectsize_ to be on CRAN... 😫

**Comment by strengejacke** [comment]
![yoda](https://user-images.githubusercontent.com/26301769/68528611-58e70680-02f5-11ea-8d26-f6b5f732be1c.jpg)

**Comment by DominiqueMakowski** [comment]
still no news... maybe it got lost in the void... let us until Monday before we take action :)

**Comment by DominiqueMakowski** [comment]
let's resubmit

**Comment by DominiqueMakowski** [comment]
(it was resubmitted 9 hours ago) 🤞

**Comment by strengejacke** [comment]
![r3mk86_large](https://user-images.githubusercontent.com/26301769/68928025-6b47c100-0789-11ea-90f6-d8b666cef7e4.png)

**Comment by DominiqueMakowski** [comment]
ikr...

**Comment by strengejacke** [comment]
ggeffects, sjstats and insight have been updated on CRAN (the first two mainly to meet the latest insight changes, and insight had warnings in check results due to another package update - survival, I think). So, _insight_ 0.7.0 is now on CRAN, and we can safely submit the next packages (which would be _effectisze_, then _sjPlot_, then _parameters_ and finally _see - all of them in a state that can be submitted right now).

**Comment by DominiqueMakowski** [comment]
*Thanks, your package is on its way to CRAN.* ☺️ 


I think CRAN's staff felt some kind of paranormal feeling today that made them accept. A feeling that we can trace back to ancient myths and legends, in which it is referred to as "LUDECKE'S WRATH OF IMPATIENCE" 😈
