### ISSUE TITLE
Common Language Effect Size (CLES)

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/effectsize#120]
https://osf.io/preprints/sportrxiv/tfx95

line 159-161:

> Therefore, scientists’ intent on using dz should consider reporting the common language effect size (CLES) (McGraw and Wong, 1992), also known as the probability of superiority (Grissom, 1994). In contrast to dz, CLES communicates the probability of a positive (CLES > 0.5) or negative (CLES < 0.5) change occurring in a randomly sampled individual (see below)

**Comment by mattansb** [comment]
Is this what `percentage_to_d()` is trying to do?

**Comment by mattansb** [comment]
``` r
library(effectsize)

(d <- cohens_d(iris$Sepal.Length, iris$Sepal.Width, paired = TRUE))
#> Cohen's d |       95% CI
#> ------------------------
#>      2.84 | [2.49, 3.21]
```

Get directly

``` r
d_to_common_language(d$Cohens_d)
#> $`Cohen's U3`
#> [1] 0.997763
#> 
#> $Overlap
#> [1] 0.1552225
#> 
#> $`Probability of superiority`
#> [1] 0.9777874
```

Or print:

``` r
print(d, append_CL = TRUE)
#> Cohen's d |       95% CI
#> ------------------------
#>      2.84 | [2.49, 3.21]
#> 
#> * Cohen's U3: 99.78%
#> * Overlap: 15.52%
#> * Probability of superiority: 97.78%
```

<sup>Created on 2020-09-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DominiqueMakowski** [comment]
Should we also have a `cles()` function as a shortcut?

**Comment by mattansb** [comment]
I think that's too opaque?

**Comment by DominiqueMakowski** [comment]
effectsize_cl()? I  don't know I never heard about it but mabe it's in fact super used and super popular and that "cles()" would talk to a lot of people but maybe you're right ^^

**Comment by mattansb** [comment]
We can always add it later (:
