### ISSUE TITLE
Reference for `percentage_to_d()`

### ISSUE THREAD

**Issue by mattansb** [easystats/effectsize#121]
@DominiqueMakowski is there any relevant reference for `percentage_to_d()`?

**Comment by DominiqueMakowski** [comment]
🤔 🤔 let me think

**Comment by DominiqueMakowski** [comment]
I don't know where it comes from, but looking at the [formula](https://github.com/easystats/effectsize/blob/master/R/convert_d_to_percentage.R), I don't really understand the logic. 

It seems to take the edges of a distribution of mean=0 SD=1, i.e., where the "bulk" of the distribution is, and then take its ratio as a percentage...? Not sure how it got there. Maybe it was my Mr Hyde side that added this when my Dr Jekyll one was sleeping 🤷‍♂️ 

We can probably delete this 😬 as I don't seem to find any references or logic behind it

**Comment by DominiqueMakowski** [comment]
🔥 🔥
