### ISSUE TITLE
pro_to_odds has `log` argument reversed

### ISSUE THREAD

**Issue by mattansb** [easystats/effectsize#123]
Or something?

Anyway, something weird is going on here....
```R
odds_to_probs(-1.6) # odds can't be negative...
#> [1] 2.666667
```

@DominiqueMakowski @strengejacke don't know if you're using these functions anywhere - but if you are, heads up!

**Comment by mattansb** [comment]
I also have no idea what the use for `probs_to_odds.data.frame` / `odds_to_probs.data.frame` (why do only these get data frame methods? 🤔) - but I'm keeping this as is for now.

**Comment by mattansb** [comment]
![image](https://user-images.githubusercontent.com/35330040/93230325-39740200-f780-11ea-8d69-207f681589f8.png)

**Comment by DominiqueMakowski** [comment]
They are used in modelbased if I recall to transform log odds to probs (hence probably the data.frame method).

As for the formula... doesn't it follow like the standard formula (eg https://www.montana.edu/rotella/documents/502/Prob_odds_log-odds.pdf)?

**Comment by mattansb** [comment]
Yes, but you cannot have negative (non-log) odds.
All I did to fix was replace the calculations with `stats::plogis()` and `stats::qlogis()` - easy fix (:
