### ISSUE TITLE
odds_to_d -> OR_to_d

### ISSUE THREAD

**Issue by mattansb** [easystats/effectsize#125]
@DominiqueMakowski @strengejacke 

The current function name of the `odds_to_d` family incorrectly imply that the input/output are Odds when in fact they are Odds Ratios (OR) - using `odds_to_d` on *odds* (of one group / condition) produces nonsensical results (the *d* between one group / condition and ???).

Should we then **deprecate** these functions in favor of `OR_to_d` family of functions?

(Currently I emphasized in the docs the fact that the input/output (labeled `odds`) is actually the odds *ratio*).

**Comment by DominiqueMakowski** [comment]
Yes indeed, or `oddsratio_to_d` because `OR_to_d` goes a bit against our conventions
