### ISSUE TITLE
add rules mechanism: closest

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/effectsize#13]
Instead of setting boundaries, add mechanisms that find the closest value. I.e., if the rules specify 0.05 = small, then label small values that are *the closer* to 0.05 rather in a particular range.

**Comment by mattansb** [comment]
Like this?

``` r
nearest <- function(x, v){
  names(v)[which.min(abs(x-v))]
}

some_scale <- c(bad = -1,
                ok = 0,
                better = 1,
                best = 2)

nearest(-99, some_scale)
#> [1] "bad"
nearest(0.3, some_scale)
#> [1] "ok"
nearest(0.7, some_scale)
#> [1] "better"
```

<sup>Created on 2019-11-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DominiqueMakowski** [comment]
yup :) 👍 

I think a design option would be to add an internal for that `.interpret_nearest()` somewhere [here](https://github.com/easystats/effectsize/blob/master/R/interpret.R#L55), and then add a `method` arg that takes "below" or "nearest"?

**Comment by DominiqueMakowski** [comment]
Or having it in `rules()`, instead of `if_lower = TRUE` or false
