### ISSUE TITLE
Vignettes need some ❤

### ISSUE THREAD

**Issue by mattansb** [easystats/effectsize#133]
- [x] standardize_data
- [x] standardize_parameters
- [x] ANOVA
- [x] bayesian_models?
- [x] convert
- [x] ~logistic~ (merged with "convert")
- [x] from_test_statistics 
- [x] interpret

**Comment by IndrajeetPatil** [comment]
I know this is besides the point, but I am curious: How did you customize those pretty GitHub labels? ^_^

**Comment by mattansb** [comment]
haha the construction worker? In the label edit (on windows) `Win + .` type `construction` until you find construction`👷‍♂️`
