### ISSUE TITLE
effect sizes report by percentage in each group 

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/effectsize#14]
For Bayesian models, maybe we should transfer the feature that is in `psycho` that reports the effect size interpretation not based on the point estimate but on the whole posterior.

**Comment by DominiqueMakowski** [comment]
PS: this thing will be useful for the future EXIT framework but needs clean and validated standardized posteriors (which we already have the interface for through the new `standardize_posteriors`). Because for now, I am still struggling with how to interpret/create interpretable standardized coefficients

**Comment by mattansb** [comment]
> Because for now, I am still struggling with how to interpret/create interpretable standardized coefficients

lol, yup.

Any progress with this? Is this still needed? (Can I close this?)

**Comment by DominiqueMakowski** [comment]
No progress 🤷 will reopen if I come back to that someday
