### ISSUE TITLE
weight standardization with missing data

### ISSUE THREAD

**Issue by mattansb** [easystats/effectsize#147]
_follow-up https://github.com/easystats/effectsize/commit/46070003e53a24244f4020f679e90de2eaaa7513#commitcomment-42855538_

@strengejacke  I've got one of the examples working now - it didn't work before because of the way `standardize` was dealing with missing data - column-wise, and not case-wise. Added an `na_action` argument (good name? better name?) for dealing with  this better, so now one of your examples works, but I can't figure out why the second one doesn't....

``` r
library(effectsize)
set.seed(1234)
data(iris)

# data setup
iris$weight_me <- runif(nrow(iris))
iris$Sepal.Length[sample(nrow(iris), size = 10)] <- NA
iris$weight_me[sample(nrow(iris), size = 10)] <- NA

# standardize 2nd data set
iris2 <- standardize(iris, select = c("Sepal.Length", "Petal.Width"),
                     na_action = "select")
iris3 <- standardize(iris, select = c("Sepal.Length", "Petal.Width"),
                     weights = "weight_me",
                     na_action = "select")



m1 <- lm(Sepal.Length ~ Species + Petal.Width, data = iris, weights = weight_me)


# weights, missing data, but data isn't weight-stdized
m2 <- lm(Sepal.Length ~ Species + Petal.Width, data = iris2, weights = weight_me)
sm2 <- standardize(m1, weights = FALSE)
testthat::expect_equal(coef(m2), coef(sm2)) #<<<<<<
#> Error: coef(m2) not equal to coef(sm2).
#> 4/4 mismatches (average diff: 0.00529)
#> [1] -0.00455 - -0.00842 ==  0.003869
#> [2] -0.06817 - -0.06942 ==  0.001245
#> [3] -0.00842 - -0.00857 ==  0.000154
#> [4]  0.81406 -  0.82994 == -0.015877

# weights, missing data, and data is weight-stdized
m3 <- lm(Sepal.Length ~ Species + Petal.Width, data = iris3, weights = weight_me)
sm3 <- standardize(m1, weights = TRUE)
testthat::expect_equal(coef(m3), coef(sm3))
```

<sup>Created on 2020-09-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mattansb** [comment]
Okay, got it - it's because the rows with the missing weights were not dropped in `iris2`, but they were then dropped in `m2`. So this does work:

``` r
library(effectsize)
set.seed(1234)
data(iris)

# data setup
iris$weight_me <- runif(nrow(iris))
iris$Sepal.Length[sample(nrow(iris), size = 10)] <- NA
iris$weight_me[sample(nrow(iris), size = 10)] <- NA


# standardize 2nd data set
iris2 <- standardize(iris, select = c("Sepal.Length", "Petal.Width"),
                     na_action = "all") # so also missing weights are dropped
iris3 <- standardize(iris, select = c("Sepal.Length", "Petal.Width"),
                     weights = "weight_me",
                     na_action = "select")


m1 <- lm(Sepal.Length ~ Species + Petal.Width, data = iris, weights = weight_me)


# weights, missing data, but data isn't weight-stdized
m2 <- lm(Sepal.Length ~ Species + Petal.Width, data = iris2, weights = weight_me)
sm2 <- standardize(m1, weights = FALSE)
testthat::expect_equal(coef(m2), coef(sm2))



# weights, missing data, and data is weight-stdized
m3 <- lm(Sepal.Length ~ Species + Petal.Width, data = iris3, weights = weight_me)
sm3 <- standardize(m1, weights = TRUE)
testthat::expect_equal(coef(m3), coef(sm3))
```

<sup>Created on 2020-10-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
The name `na_action` is maybe a bit misleading? If I understand right, you can preserve NA (`"column"`), remove per rowwise for selected columns (`"select"`) , or remove all NAs (`"all"`).

So maybe we could name it `remove_na` and then `"none"`, `"select"` and `"all"`?

**Comment by strengejacke** [comment]
we should call for help and ask the god of naming convention here: @DominiqueMakowski 

![4gwwvi](https://user-images.githubusercontent.com/26301769/94780985-82a39300-03c9-11eb-9846-29c52ab56742.jpg)

**Comment by mattansb** [comment]
> So maybe we could name it remove_na and then "none", "select" and "all"?

Yeah, that is better. Can @DominiqueMakowski top this???

**Comment by DominiqueMakowski** [comment]
> So maybe we could name it remove_na and then "none", "select" and "all"?

The apprentice has become the master. That sounds good, though I would replace "select" by "selection" so that it's clearer that it refers to the selection selected with select :)

Another possibility is to reverse it by 'keep_na' it depends whether we have more 'keep_*' or 'remove_*' args in easystats

**Comment by mattansb** [comment]
Replaced "select" with "selected" (shorted than "selection") (:
