### ISSUE TITLE
Feature request: more xtab effect sizes

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/effectsize#158]
```r
    library(effectsize)

    cramers_v(table(mtcars$am, mtcars$cyl))
    #> Cramer's V |       95% CI
    #> -------------------------
    #>       0.52 | [0.11, 0.85]

    cramers_v(table(mtcars$am))
    #> Error in optim(par = 1.1 * rep(chi, 2), fn = function(x) {: function cannot be evaluated at initial parameters
```

<sup>Created on 2020-10-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by mattansb** [comment]
(note to self: make sure this will also work with htest)

**Comment by mattansb** [comment]
``` r
effectsize::cramers_v(table(mtcars$am))
#> Cramer's V |       95% CI
#> -------------------------
#>       0.19 | [0.00, 0.53]
```

<sup>Created on 2020-10-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by IndrajeetPatil** [comment]
Thanks!

Are you also considering adding support for paired contingency tabs designs (like Cohen's _g_)?

``` r
Performance <-
  matrix(c(794, 86, 150, 570),
         nrow = 2,
         dimnames = list("1st Survey" = c("Approve", "Disapprove"),
                         "2nd Survey" = c("Approve", "Disapprove")))

mcnemar.test(Performance)
#> 
#>  McNemar's Chi-squared test with continuity correction
#> 
#> data:  Performance
#> McNemar's chi-squared = 16.818, df = 1, p-value = 4.115e-05
```

<sup>Created on 2020-10-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mattansb** [comment]
Can you point me in the right direction for these?

**Comment by IndrajeetPatil** [comment]
This is the only implementation I have seen for Cohen's G:
https://rdrr.io/cran/rcompanion/src/R/cohenG.r

I think a lot of the code therein will not be relevant for us (bootstrapping, creating histograms, pairwise comparisons, etc.).

**Comment by mattansb** [comment]
I'll take a look.
If you have any more info (reference?) that'd be great - I can't seem to find anything :/

**Comment by IndrajeetPatil** [comment]
Yeah, that's true. I can also barely find anything over and above what is discussed here :(
http://rcompanion.org/handbook/H_05.html

In general, I am surprised by the dearth of literature when it comes to repeated measures contingency tabs designs.

**Comment by mattansb** [comment]
This was easier than I thought (instead of bootstrapping the CI, I used a parametric approach, based on the P used to compute g - seems to give very very close estimates to the bootstrap):

``` r
library(effectsize)

# From mcnemar.test
Performance <-
  matrix(c(794, 86, 150, 570),
         nrow = 2,
         dimnames = list("1st Survey" = c("Approve", "Disapprove"),
                         "2nd Survey" = c("Approve", "Disapprove")))

rcompanion::cohenG(Performance, ci = TRUE)[[1]][3, ]
#>   Dimensions Statistic Value lower.ci upper.ci
#> 3      2 x 2         g 0.136    0.069    0.197

cohens_g(Performance)
#> Cohen's g |       95% CI
#> ------------------------
#>      0.14 | [0.07, 0.19]


AndersonRainBarrel <- matrix(c(9L, 17L,
                               5L, 15L), nrow = 2)
rcompanion::cohenG(AndersonRainBarrel, ci = TRUE)[[1]][3, ]
#>   Dimensions Statistic  Value lower.ci upper.ci
#> 3      2 x 2         g -0.273  -0.4444   -0.091

cohens_g(AndersonRainBarrel)
#> Cohen's g |       95% CI
#> ------------------------
#>      0.27 | [0.07, 0.40]


M <- matrix(c(794, 86, 150, 
              570, 794, 86, 
              150, 570, 15),
            nrow = 3)

rcompanion::cohenG(M, ci = TRUE)[[1]][3, ]
#>   Dimensions Statistic Value lower.ci upper.ci
#> 3      3 x 3         g   0.3    0.286    0.322

cohens_g(M)
#> Cohen's g |       95% CI
#> ------------------------
#>      0.30 | [0.28, 0.32]
```

<sup>Created on 2020-10-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by IndrajeetPatil** [comment]
This is awesome! Thanks a ton :)

**Comment by IndrajeetPatil** [comment]
To be consistent, can you please also allow `...` in `cohens_g` function?

```r
phi(x, y = NULL, ci = 0.95, adjust = FALSE, CI, ...)

cohens_w(x, y = NULL, ci = 0.95, adjust = FALSE, CI, ...)

cramers_v(x, y = NULL, ci = 0.95, adjust = FALSE, CI, ...)

cohens_g(x, y = NULL, ci = 0.95)
```

**Comment by IndrajeetPatil** [comment]
Thanks. 

Another thing I noticed was `NaN`s are introduced in CIs for some edge cases. 
I am not sure if we should let these be `NaN`s or replace them with 0s.

```r
    library(effectsize)
    library(ggplot2)

    set.seed(123)
    cramers_v(table(msleep$vore, msleep$conservation), ci = 0.990, adjust = TRUE)
    #> Warning in sqrt((chisq/n) - (df/(n - 1))): NaNs produced
    #> Cramer's V (adj.) |    99% CI
    #> -----------------------------
    #>              0.06 | [ , 0.25]
```

<sup>Created on 2020-10-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by mattansb** [comment]
Very weird, that should not happen...
Can you open a separate issue for this?

**Comment by strengejacke** [comment]
In `chisq_to_phi()`, when called from `chisq_to_cramers_v()` for computing CIs, and when `adjust = TRUE`, in the above example following code fails:

```r
    res <- data.frame(
      phi_adjusted = pmax(0, sqrt((chisq / n) -
                                    (df / (n - 1))))
    )
```

because the lower chisq is 0, thus `(chisq / n) - (df / (n - 1))` is negative, and `sqrt()` produces `NA`. Not sure if it's enough to add an `abs()` here?
