### ISSUE TITLE
effectsize with non-pearson correlations

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/effectsize#165]
``` r
effectsize::effectsize(cor.test(iris$Sepal.Width, iris$Sepal.Length, method = "spearman"))
#> Warning in cor.test.default(iris$Sepal.Width, iris$Sepal.Length, method =
#> "spearman"): Cannot compute exact p-value with ties
#> Error in `$<-.data.frame`(`*tmp*`, "CI", value = 0.95): replacement has 1 row, data has 0
```

<sup>Created on 2020-10-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

can we prevent it from failing? needed for https://github.com/easystats/report/blob/dev/R/report.htest.R#L39 😁

**Comment by mattansb** [comment]
Fixed, but it is not possible to get CIs:

``` r
effectsize::effectsize(cor.test(iris$Sepal.Width, iris$Sepal.Length))
#>     r |        95% CI
#> ---------------------
#> -0.12 | [-0.27, 0.04]

effectsize::effectsize(cor.test(iris$Sepal.Width, iris$Sepal.Length, method = "spearman"))
#> Warning in cor.test.default(iris$Sepal.Width, iris$Sepal.Length, method =
#> "spearman"): Cannot compute exact p-value with ties
#>     r
#> -----
#> -0.17

effectsize::effectsize(cor.test(iris$Sepal.Width, iris$Sepal.Length, method = "kendall"))
#>     r
#> -----
#> -0.08
```

<sup>Created on 2020-10-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DominiqueMakowski** [comment]
Why not pulling it from `correlation`? we could export the CI function (https://github.com/easystats/correlation/blob/master/R/cor_to_ci.R#L24) in there, so that you can use it here?

Altough circular dependencies might be a problem since we import effectsize there https://github.com/easystats/correlation/blob/master/DESCRIPTION#L37...

Maybe then we should move the CI method to effectsize and use it in correlation

**Comment by mattansb** [comment]
the htest object does not have the required data to do this (needs the `n`)...

**Comment by DominiqueMakowski** [comment]
but there's the df so n should be df + 2

**Comment by mattansb** [comment]
Nope - no df for spearman or tau.... :/

**Comment by DominiqueMakowski** [comment]
ah right :(

**Comment by strengejacke** [comment]
Does it make sense to have a `effectsize.easycorrelation()` method, that simply extracts the columns from _correlation_?

``` r
effectsize::effectsize(correlation::cor_test(iris, "Sepal.Width", "Sepal.Length", method = "spearman"))
#> Error in standardize_parameters.parameters_model(model, ...): Method 'refit' not supported for 'model_parameters()
class(correlation::cor_test(iris, "Sepal.Width", "Sepal.Length", method = "spearman"))
#> [1] "easycorrelation"  "parameters_model" "data.frame"
```

<sup>Created on 2020-10-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mattansb** [comment]
I guess we can do that, but it seems odd to pass anything correlation-based to `effectsize()` as these are already correlations which are effect sizes, no?

**Comment by strengejacke** [comment]
Well, I thought, if someone uses 

```r
effectsize::effectsize(cor.test(iris$Sepal.Width, iris$Sepal.Length))
```

why would she/he not also use

```r
effectsize::effectsize(correlation::cor_test(iris, "Sepal.Width", "Sepal.Length", method = "spearman"))
```

?

**Comment by mattansb** [comment]
I only did `effectsize::effectsize(cor.test(iris$Sepal.Width, iris$Sepal.Length))` for copletness sake, so that all the `htest`s are supported.

But I guess I can add that too... If you add `model_parameters.easycorrelation` 😝😅😇

**Comment by DominiqueMakowski** [comment]
> I guess we can do that, but it seems odd to pass anything correlation-based to effectsize() as these are already correlations which are effect sizes, no?

it makes sense in other developments such as for example report where the input is fed into effectsize(), and besides, technically, the function behaves as it should behave (it's just people that would do that that are odd maybe 😁)

**Comment by strengejacke** [comment]
>  If you add model_parameters.easycorrelation

Just for the record, an object returned by `correlation::cor_test()` is also of class `parameters_model`, so no need for an extra `model_parameters()` method here... 😛

**Comment by mattansb** [comment]
Touché....

Is there a safe / smart way to find the name of the column that has the correlation coefficient?

**Comment by strengejacke** [comment]
> Is there a safe / smart way to find the name of the column that has the correlation coefficient?

Should always be one of `"r"`, `"rho"` or `"tau"`.

**Comment by strengejacke** [comment]
You _could_ rely on the forthcoming `insight::standardize_name()`, then it is always `"Coefficient"`.

**Comment by DominiqueMakowski** [comment]
Or the easy way: https://github.com/easystats/report/blob/dev/R/report.htest.R#L114-L115

**Comment by strengejacke** [comment]
@DominiqueMakowski for _see_, you have added an attribute `attr(x, "coefficient_name")` to `correlation()`, maybe you can do this for `cor_test()` as well?

**Comment by mattansb** [comment]
> @DominiqueMakowski for see, you have added an attribute attr(x, "coefficient_name") to correlation(), maybe you can do this for cor_test() as well?

Yes, this, and I'll pull it from there.

**Comment by DominiqueMakowski** [comment]
ok good idea
