### ISSUE TITLE
t_to_eta2 vs. t_to_eta2_partial

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/effectsize#17]
I am coming back to this because I am still not sure it is the best way to go in terms of clarity.

@mattansb (if I'm understanding you correctly) I understand the importance of stressing that these are partial indices in the sense that they are adjusted for everything else in the model. However, this is very common in all models. I.e, you know that all parameters of a linear regression are "partial" in that sense. Hence it seems unnecessary to add it in all the names, also because the non-partial version does not exist for these function, so no confusion is possible. I.e., IMO, it is sufficient to mention that partial aspect in the documentation since it applies to all functions.

Another bigger issue is that this "partial" could be confused with Partial eta2, partial Omega 2 as they are defined in the ANOVA framework, I.e. as adjusted *for the sample size*. Thus, if I'm correct that these two partial refer to different things, we should remove the former. 

Another possibility could be to group them all under a function like:

`F_to_r2(x, method = c("eta2", "omega2", "epsilon2")`

@strengejacke

**Comment by mattansb** [comment]
> Another bigger issue is that this "partial" could be confused with Partial eta2, partial Omega 2 as they are defined in the ANOVA framework, I.e. as adjusted for the sample size. Thus, if I'm correct that these two partial refer to different things, we should remove the former.

These two partials are actually the same thing: they refer to indices of variance explained when partialling out any modeled (random or fixed) effects (not adjusting for sample size).
So when F = (SS<sub>effect</sub> / df<sub>effect</sub>) / (SS<sub>error</sub> / df<sub>error</sub>),
The corresponding Partial Eta Squared = SS<sub>effect</sub> / (SS<sub>effect</sub> + SS<sub>error</sub>)
Here ^ we only look at the variance of the effect and the variance to that same effect's error - ignoring any other effects (fixed or random).

The function `F_to_partial_eta_squared` is just a conviniant shortcut for the "real thing". For example, we can compare a "true" partial eta squared (from the `afex` package`) to out "cheat":
``` r
library(effectsize)
library(afex)
data(md_12.1)
fit <- aov_ez("id", "rt", md_12.1,
              within = c("angle", "noise"),
              anova_table = list(correction = "none", es = "pes")
)

# Compare...
fit$anova_table$pes # A true effect size
#> [1] 0.8189831 0.7895522 0.8342857
with(fit$anova_table, { # out cheat
  F_to_partial_eta_squared(`F`, `num Df`, `den Df`)
})
#> [1] 0.8189831 0.7895522 0.8342857
```

<sup>Created on 2019-10-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


All this to say.... I think "partial" should be in the function name to distinguish it from other non-partialled effect sizes.

How about this:
`F_to_partial_r2(f, df, df_error, method = c("eta2", "omega2", "epsilon2", "adj_eta2"))`

**Comment by DominiqueMakowski** [comment]
But is it possible to have `F_to_r2()` (i.e., a non-partial R2?). I mean the fact that the explained variance is partial is a property of the model that is reflected by the provided F value, the conversion function doesn't really partialize anything in itself does it?

**Comment by DominiqueMakowski** [comment]
> nother bigger issue is that this "partial" could be confused with Partial eta2, partial Omega 2 as they are defined in the ANOVA framework, I.e. as adjusted for the sample size. 

Maybe I confused it with "adjusted", although we say [`@param partial If \code{TRUE}, return partial indices (adjusted for sample size).`](https://github.com/easystats/effectsize/blob/master/R/eta_squared.R#L6)

**Comment by mattansb** [comment]
> But is it possible to have F_to_r2() (i.e., a non-partial R2?). I mean the fact that the explained variance is partial is a property of the model that is reflected by the provided F value, the conversion function doesn't really partialize anything in itself does it?

Technically yes - if the F is of the full model against the empty model, this will be a non-partialled R2... but how often does that happen? It is waayyyyyyyy more common to have F of comparing nested models, or Fs of testing effects, or contrasts.... If anything, the fact that it *can*, **in one special case**, return a *non*-partial R2 should be in the documentation.

> Maybe I confused it with "adjusted", although we say @param partial If \code{TRUE}, return partial indices (adjusted for sample size).

Then this description is wrong 😅
There is a "generalized" eta squared that does do something with the total sample, but not sure what that is + never seen it outsize a stats class + no "cheat" way to get it 😁

**Comment by DominiqueMakowski** [comment]
> echnically yes - if the F is of the full model against the empty model, this will be a non-partialled R2...

My point exactly, so since it's always partial (unless the special case where partial = non-partial), and since the fact that the explained variance of a given predictor only reflects that of that predictor is a highly expected and normal thing, I see it as a more natural to name it `F_to_eta2`, and say in the documentation that it is obviously a partial index of variance explained (aside from particular circumstances where partial and non-partial are the same)

> Then this description is wrong 😅

Needs to be changed then 😅

**Comment by mattansb** [comment]
Ah, I see what you mean.... I worry though that some might think that these are some magic functions that give non-partial indices :/ 

Is it the long name that bothers you? We can do `F_to_eta2p`, which is how it appears in pubs anyway, and the `p` will tell the informed user that it's partial, and will be a red flag for the uninformed ~~prior~~ user.

**Comment by DominiqueMakowski** [comment]
The most common use case for this function from users will arguably to provide the column of the F/t and `df_error` columns from the parameters of a model (let it be an ANOVA, LM or whatever), to get the eta2 for the parameters, if so, and if I understand you, you're suggesting that people might confuse these r²-like values outputted with r² of the relationship between the parameters and the outcome that would be obtained outside of the model?

**Comment by mattansb** [comment]
Yeah, basically.

I mean, there *is* a measure called R2, and eta2, etc... I would like the function name reflect the fact that this is **not** that. (As eta2p >= eta2, having users mistake these would be a problem in their interpretation of their effect sizes...)

**Comment by DominiqueMakowski** [comment]
Mmh I see. Well, I still think that it's a 'hella verbose way to remind users of a fact expected by most :) IMO the documentation is sufficient (I like to think that most of users actually *do* read the documentation ^^), we need an 3rd opinion, 🦇 🚨  turning on the strenge-signal to call for @strengejacke

**Comment by mattansb** [comment]
Oh no, not him... 😉

--
Mattan S. Ben-Shachar, PhD student
Department of Psychology & Zlotowski Center for Neuroscience
Ben-Gurion University of the Negev
The Developmental ERP Lab

**Comment by strengejacke** [comment]
As you know, I don't use anova and have nothing to do with those effect sizes... So what's actually the point you like to have a 3rd opinion?

If...

> I see it as a more natural to name it F_to_eta2

I would say...

![dcdf5b42acb95fa3551faa23a2f1e9e4](https://user-images.githubusercontent.com/26301769/67745989-d40f0980-fa25-11e9-8864-67744f505c5a.jpg)

**Comment by DominiqueMakowski** [comment]
It's an issue *beyond* ANOVAs!

-> do you think that the fact that the explained variance returned by these function is related to that of a parameter adjusted for the other parameters in the model (similarly to any other index related to parameters  of a model with more than one parameter) is unexpected or confusing enough to add it in the function name?

**Comment by mattansb** [comment]
add it in the function name = add the smallest `p` to the end of it.

**Comment by strengejacke** [comment]
> a parameter adjusted for the other parameters in the model

But isn't this in general the case, for any parameter-related value (p, test-statistic, se, ...)?

**Comment by DominiqueMakowski** [comment]
That's my perception of it too, hence I am not sure why Master Mattakin is so keen on having it in the name

**Comment by mattansb** [comment]
Because there is another index called eta2... If a user asks for `F_to_eta2`, shouldn't he get an eta2???
(in fact, the `eta_squared` function should have `partial` set to **`FALSE`** by default!)

**Comment by DominiqueMakowski** [comment]
Because in `F_to_eta2`, the fact of being "partial" is a property of F (itself a property of the parameter of a model which is by nature partial). Thus, converting F to eta2 is partial because of the provided input, not because of the computation happening in the conversion function 

(nobody can say that we do not discuss in depth the naming here in easystats 😁)

**Comment by strengejacke** [comment]
The difference between eta2 and partial eta2 is just that the denominator for eta2 is the total sum of squares, while for partial eta2 it is the parameter related ss + residual ss. Hence, is it possible to convert F to both eta2 and partial eta2? If so, I would name it `F_to_eta2` and add a `partial`-argument.

**Comment by mattansb** [comment]
> Because in F_to_eta2, the fact of being "partial" is a property of F

If you assume users to know this, you have better faith than me 😅

> is it possible to convert F to both eta2 and partial eta2?

No, a single F can only give partial eta2...

Okay, I get it... I lost this one... 😭

I will change the function names accordingly... `F_to_eta2`, etc...

**Comment by DominiqueMakowski** [comment]
\**Daniel discreetly stores Dom's 10 dollars bill into his pocket*\*

**Comment by strengejacke** [comment]
@mattansb 

![giphy](https://user-images.githubusercontent.com/26301769/67757449-1cd1bd00-fa3c-11e9-80c1-8811f8b10971.gif)

**Comment by mattansb** [comment]
That's just mean 😅

**Comment by DominiqueMakowski** [comment]
I'd even say it's [***de***mean](https://github.com/easystats/parameters/commit/513691fbaa8f517187ea60528ee7641058e42808#commitcomment-35707444)

**Comment by mattansb** [comment]
![image](https://user-images.githubusercontent.com/35330040/67759805-ca4acd80-fa48-11e9-857d-138202b6994f.png)

**Comment by mattansb** [comment]
@DominiqueMakowski / @strengejacke Recently a colleague was telling me about his usage of `effectsize` and the `F_to_*` functions.
Unfortunately, they were under the impression that these function are for eta squared; when I told them they were for _partial_ eta squared, they asked "why isn't that somewhere in the function name", and "but partial eta is it's own thing".

I know N=1, but see above from my strong priors of this being a problem.

**Comment by DominiqueMakowski** [comment]
since I have the opposite strong prior, this N=1 changes *nuffin* 😈 

jk, okay for the bold, but the capitalized is uglyyyy

**Comment by mattansb** [comment]
How about `F_to_eta2` -> `F_to_eta2p`? 🙏

**Comment by DominiqueMakowski** [comment]
![](https://media.giphy.com/media/JoePLWxLD7cGc/giphy.gif)

**Comment by mattansb** [comment]
https://twitter.com/mattansb/status/1202204182264066048 ....

**Comment by DominiqueMakowski** [comment]
the fact that it's partial is a property of the parameter and not of the function. In a multiple regression model all the indices are "partial" in the sense that they are only related to a given parameter and *"adjusted"* for the others. And we wouldn't create a "partial_pvalue" function?

**Comment by mattansb** [comment]
If there was a non-partial p-value, then yes!

**Comment by DominiqueMakowski** [comment]
![](https://media.giphy.com/media/6185ZmQRRakyk/giphy.gif)

**Comment by mattansb** [comment]
In Hebrew there is a saying: "Don't block the path of a blind man"...
You assume too much of the users here - that they will either know the properties of F, or that they will actually read the documentation (or that they will not forget after using it once what it means when they code-and-paste to re-use their code)...

**Comment by strengejacke** [comment]
Fixed:

``` r
library(effectsize)
F_to_eta2(16.501, 1, 9)
#> 
#> 
#> CAUTION!!! THIS FUNCTION RETURNS THE *P*A*R*T*I*A*L* ETA-SQUARED!!11!
#> [1] 0.6470727
```

<sup>Created on 2019-12-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mattansb** [comment]
I think adding a `p` to the function name would suffice 😂

**Comment by DominiqueMakowski** [comment]
and for a simple regression model with one parameter this functions technically compute... a non-partial eta2. Again, because whether it is partial or not doesn't have anything to do with the function, and the function will return the same output for a given F if it is a partial F and if it's not. Hence, no sense of naming a function with something irrelevant to what it does

> In Hebrew there is a saying: "Don't block the path of a blind man"...

You assume too much of the users here - that they will not read the documentation because they believe they already know. But actually many people do read 😉

**Comment by mattansb** [comment]
It amazes me that you two, who always want clear initiative function names, are so resistant to a simple little `p` that would add clarity to the function's result...

Is the easystats guidelines that function names and outputs should assume users has read the docs?

Why have `distribution_chisquared`? Even if there is chi (not-squared) distribution, isn't the "chi" in practice always squared? Why not have `distribution_chi`? Perhaps it should just be `F_to_eta`?

**Comment by DominiqueMakowski** [comment]
> Why have distribution_chisquared? Even if there is chi (not-squared) distribution, isn't the "chi" in practice always squared? Why not have distribution_chi? Perhaps it should just be F_to_eta?

😅 😅 

even *eta* is an arbitrary name though, only used because of conventions that we must overcome. I suggest `something_to_something`

**Comment by strengejacke** [comment]
We could simply remove that function?

**Comment by DominiqueMakowski** [comment]
and adding this little p unnecessarily (coz it's not about what the function does) breaks the `a_to_b` syntax. We cannot be the ever-present guardians of good practices, if the users misuses that function and thinks that he magically obtained some index related to something else than its parameter, well too bad!

**Comment by DominiqueMakowski** [comment]
*Daniel about the function:*

![](https://media.giphy.com/media/lZhymdRsuFDmU/giphy.gif)

**Comment by mattansb** [comment]
> We cannot be the ever-present guardians of good practices, if the users misuses that function and thinks that he magically obtained some index related to something else than its parameter, well too bad!

You are technically correct. But it is still my opinion that a little `p` will do much more good than harm (what harm does it do?)

**Comment by mattansb** [comment]
wait - @DominiqueMakowski @strengejacke are you so Bayesian and anti p-value that you won't add the `p` to the function name??

What next?? will `parameters` become `arameters`??

**Comment by DominiqueMakowski** [comment]
> what harm does it do?

it breaks the beauty of the `a_to_b` syntax, and since easystats is beauty, you wouldn't wanna break easystats would you?

**Comment by DominiqueMakowski** [comment]
> What next?? will parameters become arameters??

You'll notice that there is no p in Dominique Makowski, Daniel Lüdecke and Mattan Ben-Sachar... 

![](https://media.giphy.com/media/51UdTLvbyReqNK3Bic/giphy.gif)

**Comment by mattansb** [comment]
> it breaks the beauty of the a_to_b syntax

Not sure how `F_to_eta2p` breaks this?

> You'll notice that there is no p in Dominique Makowski, Daniel Lüdecke and Mattan Ben-Sachar...

![image](https://user-images.githubusercontent.com/35330040/70146795-9b5cf280-16ab-11ea-823e-0e663864b407.png)

**Comment by strengejacke** [comment]
`F_to_eta2_partial()` would be the name according to our naming convention, if I interprete our rules right (and if we want to denote the "partial" property in the function name).

Since I will probably never convert an F into an eta2 or any other greek letter, I'm actually not so keen about this function name...

**Comment by DominiqueMakowski** [comment]
<sub>psss, Daniel, could you furtively add to the our convetions "the name of a function should be related to what the function does"</sub>

**Comment by mattansb** [comment]
Does the function not compute a partial eta square? pls explain

**Comment by strengejacke** [comment]
<sub>We could mention an unwritten rule that conversion functions are only allowed to have one proncounceable greek letter before and after "to"</sub>

**Comment by strengejacke** [comment]
> Does the function not compute a partial eta square? pls explain

![image](https://user-images.githubusercontent.com/26301769/70147974-98f79a00-16a5-11ea-9fd5-5e40bd7ef27a.gif)

**Comment by mattansb** [comment]
![image](https://user-images.githubusercontent.com/35330040/70148098-335bdb80-16ae-11ea-97b5-d897fe9772d0.png)

**Comment by mattansb** [comment]
As maintainer...............

**Comment by DominiqueMakowski** [comment]
> As maintainer...............

Oh no, what have we done!

![](https://media.giphy.com/media/l3vRlInF7QViJNOow/giphy.gif)
