### ISSUE TITLE
Rename eta_sq as eta2

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/effectsize#173]
A breaking feature probably, but it will increase consistency between the column name and the printing (in which it is written eta2), would be consistent with other square indices like R2 and most importantly would shorten it for instance in the case of `Eta_sq_partial`. 

I'm saying that because in report I need to prepend its CI by the name of the index, and `Eta_sq_partial_CI_low` is quite terrible, whereas `Eta2_partial_CI_low` is a bit less terrible ^^

**Comment by mattansb** [comment]
I'm thinking that wanting shorted column names in `report` is not a good enough justification for such a breaking change...?

``` r
nchar("Eta2_partial_CI_low")
#> [1] 19
nchar("Eta_sq_partial_CI_low")
#> [1] 21
```

<sup>Created on 2020-10-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DominiqueMakowski** [comment]
> is not a good enough justification

I know, that's why I mentioned consistency 😁 

But I agree, maybe it's not worth it. Though I'm not *that* worried about breaking changes since we're still in beta and the reverse dependencies are for now people that we are in contact with. But yeah, it's a call we need to make 🤷‍♂️ @strengejacke what do you think?

**Comment by strengejacke** [comment]
we currently don't have a rule for "squared", maybe we could indeed think about finding another code-convention here?

**Comment by mattansb** [comment]
Yeah, we need to think for a rule for numerical operations (squared, squared-root, log)... Any suggestions?

**Comment by strengejacke** [comment]
Whereat we should distinguish between "print" (e.g. coefficient names in `model_parameters()`), and the _column names_. For column names, I think we don't have sqrt or log very often.

**Comment by mattansb** [comment]
For `exponentiate = TRUE` in parameters, what is the column name / print output?

**Comment by strengejacke** [comment]
https://github.com/easystats/parameters/blob/f012b95410710e860bef7c9ece6f58fd6d81a4d4/R/utils_model_parameters.R#L27

**Comment by mattansb** [comment]
I'm really torn here - on the one hand, `Eta_Sq` seems more "propper" than `Eta2` as a strictly string name.
On the other hand, we have `R2` and not `R_Sq`. 

And also `Cohens_f_Sq_partial` is ridiculous...

So I think I'm changing my vote, and suggesting to the easy-committee to mark "squared" in column names / attributes with a "2" suffix instead of the "_Sq" suffix. What say you?

**Comment by IndrajeetPatil** [comment]
I definitely prefer `_Sq` suffixes. It is more intuitive for me and immediately clarifies what it refers to. If this is borne out of consistency concerns, I would vote for printing `Eta_Sq` than changing to something like `Eta_2`. 

Also, when I see functions with numeric suffixes (esp. 2), I invariably think that they reflect the revised version of that function (e.g., `forcats::fct_reorder2` and `forcats::fct_reorder`, etc.).  Maybe it's just me, but just saying.

**Comment by mattansb** [comment]
@IndrajeetPatil Sorry, not clear - are you suggest also printing (in the pretty format) `Eta Sq (partial)`? Or just for the column names?

**Comment by DominiqueMakowski** [comment]
> I'm really torn here - on the one hand, Eta_Sq seems more "propper" than Eta2 as a strictly string name.
On the other hand, we have R2 and not R_Sq.

I agree, sq seems more proper but 2 is much more convenient - I hear the explicitness argument from @IndrajeetPatil (and I'd even go further: in France often eta2 is named "éta deux" like "eta two" instead of "eta carré" which would be eta squared). Still though, I'd favour the 2, mainly for the reason that it is an ASCII place holder of the ². And we would expect people (or in supported formats) to transform these 2 into ²

**Comment by IndrajeetPatil** [comment]
> Sorry, not clear - are you suggest also printing (in the pretty format) Eta Sq (partial)? Or just for the column names?

Yes, the former. 

But, I also see your points. 
Ultimately, I don't think it will be that big of a change at the current stage (we're still not above `1.0.0`), so better to make these changes now if there is consensus than hold off on them.

**Comment by mattansb** [comment]
So I think I'll go with "2", somewhat reluctantly.

The function names, however, I will keep as `eta_squared()` (but `F_to_eta2()` 🤷‍♂️) etc.

**Comment by DominiqueMakowski** [comment]
We could have an alias for eta2()?

**Comment by mattansb** [comment]
Overkill IMO

**Comment by strengejacke** [comment]
> in France often eta2 is named "éta deux" like "eta two" instead of "eta carré" which would be eta squared). Still though, I'd favour the 2, mainly for the reason that it is an ASCII place holder of the ². 

But I mean, this (éta deux) is French-stlye, or not? Being as lazy as possible according to language/words... (éta carré is one more syllable) 😄 Isn't _Où t'es_ a short form of _Où est-ce que tu es_?

**Comment by DominiqueMakowski** [comment]
>  Isn't Où t'es a short form of Où est-ce que tu es?

True true but we're not that commonly lazy where it comes to language tho (wait until you hear [Singaporean english](https://www.youtube.com/watch?v=PytkcPJ9oLA&ab_channel=TheSmilingAfro) 🤯), I think it this case it comes from a legit lack of knowledge that it represents a square... I even heard several times "éta petit-deux" (eta-little-two) so that tells you something 😅 ...

**Comment by mattansb** [comment]
> "éta petit-deux"

That's adorable! T-shirt idea!
