### ISSUE TITLE
Set partial to FALSE when only one IV modeled

### ISSUE THREAD

**Issue by philchalmers** [easystats/effectsize#180]
Thanks for writing this package; I've found it very handy when presenting ANOVAs to students. 

I have a small, non-urgent formatting request: when models include only one independent variable the `partial` flag should be set to `FALSE` by default (or otherwise ignored) as the statistics are not partial relationships in any sense. Hence, this output:

```r
data(mtcars)

dat <- within(mtcars, {
  fcyl <- factor(cyl)
})


mod1 <- aov(mpg ~ fcyl, dat)
effectsize::eta_squared(mod1)

## Parameter | Eta2 (partial) |       90% CI
## -----------------------------------------
## fcyl      |           0.73 | [0.57, 0.82]
```

should really print this output by default

```r
## Parameter | Eta2 |       90% CI
## -------------------------------
## fcyl      | 0.73 | [0.57, 0.82]
```
I believe this better matches the convention seen in the literature too. Thank you in advance.

**Comment by mattansb** [comment]
Hi @philchalmers !

I fear that this may cause some confusion with more complex models where you can have just one IV, but still have a partial effect size, such as repeated measures anova (`aovlist`) and mixed models.
So I wonder what would be less confusing, that the argument is ignored in a very limited set of cases, or the label of the effect size.

I would also have to see how this plays with other non `aov` / `lm` based models, behind the scenes.

Thanks for the suggestion!

**Comment by DominiqueMakowski** [comment]
Though I supposed indeed have an `is_partial` attribute (could be extended to other ESs), that would dictate whether to pretty-print `(partial)` or not, that could be set to FALSE is the very specific case of aov() with one IV

**Comment by mattansb** [comment]
I suppose we can add a note when printing / print differently for the case of a one-way-between-subject anova.
I'll take a look at this at some point between diper changes

**Comment by mattansb** [comment]
``` r
effectsize::eta_squared(aov(Sepal.Length ~ Species, data = iris))
#> For one-way between subjects designs, partial eta squared is equvilant to eta squared.
#> Returning eta squared.
#> Parameter | Eta2 |       90% CI
#> -------------------------------
#> Species   | 0.62 | [0.54, 0.68]
```

<sup>Created on 2020-12-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
