### ISSUE TITLE
rules() for threshold

### ISSUE THREAD

**Issue by strengejacke** [easystats/effectsize#194]
https://easystats.github.io/effectsize/reference/rules.html

Shouldn't the first example return:
```r
#> significant < 0.05 <= not significant
```

**Comment by DominiqueMakowski** [comment]
We'd need to find a programmatical way of displaying custom rulesets 😕

**Comment by strengejacke** [comment]
But as a user, how do I know if the function considers `0.5` as "significant" or "not significant"? I think being pragmatical here only leads to confusion on the user-side.

**Comment by mattansb** [comment]
Fixed (: 

``` r
library(effectsize)
rules(c(0.05), c("significant", "not significant"),
      name = "default", right = FALSE)
#> # Reference thresholds (default)
#> 
#> significant < 0.05 <= not significant
```

<sup>Created on 2020-11-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
