### ISSUE TITLE
Column names for F_to_eta2_adj incorrect?

### ISSUE THREAD

**Issue by strengejacke** [easystats/effectsize#195]
Is it intentional that the column name for `F_to_eta2_adj()` is `"Epsilon2_partial"`?

``` r
colnames(effectsize::F_to_eta2_adj(f = 2,7, df = 2, df_error = 5, ci = .9))
#> [1] "Epsilon2_partial" "CI"               "CI_low"           "CI_high"
```

<sup>Created on 2020-11-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mattansb** [comment]
Yup.
From the docs:

![image](https://user-images.githubusercontent.com/35330040/98217167-c94d5580-1f52-11eb-8107-fd56cda42f92.png)

**Comment by mattansb** [comment]
I really love Mordkoff (2019), where they introduce the adjusted eta, how unbiased it is, and all its good properties, and then, at the very end they're like "oh, btw, this is actually exactly epsilon..." 😂

**Comment by strengejacke** [comment]
Ok, thanks!
