### ISSUE TITLE
Rename "master" branch to "main" branch

### ISSUE THREAD

**Issue by mattansb** [easystats/effectsize#201]
(Once review on JOSS is done)

As per various suggestions for the use of more inclusive language in programming (and specifically as suggested by @trashbirdecology).

**Comment by strengejacke** [comment]
> Change master branch to main branch

What does this exactly mean?

**Comment by mattansb** [comment]
Just to rename the branch. [This was raised earlier this year in a much broader scope](https://www.zdnet.com/article/github-to-replace-master-with-main-starting-next-month).

**Comment by mattansb** [comment]
https://github.com/easystats/effectsize/tree/main

Since I don't have "settings" privilege's, I will let you know when it's safe to do the switch (:
(Please do not PR from or to this branch currently)

**Comment by trashbirdecology** [comment]
@strengejacke, newly created repositories in GH now default to "main" branch, but old ones will need to be manually migrated over to "main".

**Comment by strengejacke** [comment]
Thanks for clarification! I recall having read something like that, but meanwhile forgot it...

**Comment by IndrajeetPatil** [comment]
Closed in https://github.com/easystats/effectsize/commit/1f20820389e04ac960f48353768feb3e82d02643
