### ISSUE TITLE
effect size for non-parametric comparisons

### ISSUE THREAD

**Issue by mattansb** [easystats/effectsize#211]
Mann–Whitney U test, and Wilcoxon signed-rank test

``` r
Input =("
 Speaker  Likert
 Pooh      3
 Pooh      5
 Pooh      4
 Pooh      4
 Pooh      4
 Pooh      4
 Pooh      4
 Pooh      4
 Pooh      5
 Pooh      5
 Piglet    2
 Piglet    4
 Piglet    2
 Piglet    2
 Piglet    1
 Piglet    2
 Piglet    3
 Piglet    2
 Piglet    2
 Piglet    3
")

Data <- read.table(textConnection(Input), header = TRUE)
```

<details>

Based on https://lindeloev.github.io/tests-as-linear

``` r
rank_biserial_r <- function(x, y = NULL, data = NULL, paired = FALSE, ci = 0.95) {
  require("effectsize")
  require("parameters")
  
  out <- effectsize:::.deal_with_cohens_d_arguments(x, y, data)
  x <- out$x
  y <- out$y
  
  if (is.null(y)) {
    y <- 0
    paired <- TRUE
  }
  
  if (paired) {
    o <- stats::complete.cases(x,y)
    x <- x[o]
    y <- y[o]
    
    rnk <- ranktransform(x - y, sign = TRUE)
    m <- stats::lm(rnk ~ 1)
    m <- model_parameters(m)[1,]
  } else {
    rnk <- ranktransform(c(x, y))
    g <- c(rep("b", length(y)), rep("a", length(x)))
    m <- stats::lm(rnk ~ g)
    m <- model_parameters(m)[2,]
  }
  
  # add tie warnings?
  t_to_r(m$t, m$df_error, ci = ci)
}
```

</details>

``` r
wilcox.test(Likert ~ Speaker, data = Data)
#> Warning in wilcox.test.default(x = c(2L, 4L, 2L, 2L, 1L, 2L, 3L, 2L, 2L, :
#> cannot compute exact p-value with ties
#> 
#>  Wilcoxon rank sum test with continuity correction
#> 
#> data:  Likert by Speaker
#> W = 5, p-value = 0.0004713
#> alternative hypothesis: true location shift is not equal to 0
rank_biserial_r(Likert ~ Speaker, data = Data)
#> Loading required package: effectsize
#> Loading required package: parameters
#>     r |         95% CI
#> ----------------------
#> -0.81 | [-0.90, -0.59]
rcompanion::wilcoxonR(Data$Likert, Data$Speaker, ci = TRUE)
#>        r lower.ci upper.ci
#> 1 -0.792   -0.897   -0.597


wilcox.test(Likert ~ Speaker, data = Data, paired = TRUE)
#> Warning in wilcox.test.default(x = c(2L, 4L, 2L, 2L, 1L, 2L, 3L, 2L, 2L, :
#> cannot compute exact p-value with ties
#> 
#>  Wilcoxon signed rank test with continuity correction
#> 
#> data:  Likert by Speaker
#> V = 0, p-value = 0.005144
#> alternative hypothesis: true location shift is not equal to 0
rank_biserial_r(Likert ~ Speaker, data = Data, paired = TRUE)
#>     r |         95% CI
#> ----------------------
#> -0.90 | [-0.95, -0.67]
# validate?
```

<sup>Created on 2020-11-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mattansb** [comment]
It's really interesting that vastly different methods for estimating the effect size yield such close values (estimates and CIs)!

@DominiqueMakowski @strengejacke @IndrajeetPatil The name of the effect size is the Rank-biserial correlation - should this be the name of the function? Any ideas?

**Comment by IndrajeetPatil** [comment]
Dude, DID YOU READ MY MIND?!

Today I was going to raise an issue about whether you would be open to also supporting effect sizes for non-parametric tests and then you tag me in this 😅

https://i.giphy.com/media/V7R5INxZGatWg/giphy.webp

As for the name, shorter the better. I like just `rank_biserial`. I feel like the additional `_r` would be a bit redundant? 
But that's just my opinion.

**Comment by mattansb** [comment]
If you have any more information about such effect sizes (and their CIs), please share it! (Baby is taking up all of my reading time 👼)

(This won't make it into the xmax release, but hopefully into the next one.)

**Comment by IndrajeetPatil** [comment]
Of course, no hurry at all!

To be honest, most of what I know about non-parametric effect sizes comes from here: https://rcompanion.org/handbook/

**Comment by IndrajeetPatil** [comment]
Would you also consider supporting this effect size for one-sample non-parametric tests?

**Comment by mattansb** [comment]
So far I was thinking:
- For Two-sample Mann–Whitney U Test (`wilcox.test(paired = FALSE)`) to have the [*rank-biserial correlation*](https://en.wikipedia.org/wiki/Mann%E2%80%93Whitney_U_test#Rank-biserial_correlation), with CI based on ["tests as linear models"](https://lindeloev.github.io/tests-as-linear/#51_independent_t-test_and_mann-whitney_u).
- For Wilcoxon signed-rank test (`wilcox.test(paired = TRUE)`) also to have the [*rank-biserial correlation*](https://en.wikipedia.org/wiki/Wilcoxon_signed-rank_test#Effect_size). But not sure how to get the CI for this, as I would need to account for the dependence.
- For a Sign Test we can have `P = max(p_larger_med, p_smaller_med)` as an effect size. CIs can be extracted from `prop.test()`. (I think that makes sense? Have to read up about this some more...)

Not sure what the effect size would be for a 1 sample non-parametric test (assuming your talking about 1 sample Wilcox?). Distance of mean signed-rank from 0? The only thing I found was from [here](https://rcompanion.org/handbook/F_02.html).

Overall, any ideas or contributions here are welcome - I literally have NEVER actually used a non-parametric test (outside of teaching), so I don't know what is common / possible here....

**Comment by IndrajeetPatil** [comment]
All of those effect sizes make sense to me!

For one-sample Wilcoxon test, there is a version of rank biserial correlation coefficient in `rcompanion`: https://rdrr.io/cran/rcompanion/src/R/wilcoxonOneSampleRC.r

I will try to see how much I can contribute. I really never use it either, but do support it in the package, so need to brush up on it once in a while. 😀

**Comment by IndrajeetPatil** [comment]
While we are on this topic, I think `effectsize` can also support the following effect sizes for non-parametric ANOVAs:

- [ ] effect size for `stats::kruskal.test` (https://rdrr.io/cran/rcompanion/src/R/ordinalEtaSquared.r)
- [ ] effect size for `stats::friedman.test` (https://rdrr.io/cran/rcompanion/src/R/kendallW.r)

**Comment by mattansb** [comment]
Yes. Hope to get to this soon(ish).
You can help by maybe hunting down (the?) papers that describe these effect sizes and their computations - I don't like just copying code from `rcompanion` (and they tend not to fully cite the equations' sources).

**Comment by IndrajeetPatil** [comment]
Sure, I will try to list the references here and keep updating the list as I find new resources. 

The main one seems to be-
> Maciej Tomczak and Ewa Tomczak. The need to report effect size estimates revisited. An overview of some recommended measures of effect size. _Trends in Sport Sciences_. 2014; 1(21):19-25.

- epsilon-squared

![image](https://user-images.githubusercontent.com/11330453/101916752-a8b69200-3bc7-11eb-9cf7-2f48a111b0ff.png)


- Kendall's _W_

![image](https://user-images.githubusercontent.com/11330453/101916443-39d93900-3bc7-11eb-8e02-3a8de33e45b3.png)

**Comment by mattansb** [comment]
The rank biserial correlation (*r<sub><sub>RB</sub></sub>*) is implemented (not yet in `\R`, currently still in `\WIP`):

```R
A <- c(48, 48, 77, 86, 85, 85)
B <- c(14, 34, 34, 77)
rank_biserial(A, B)
#> r_rank_biserial |       95% CI
#> ------------------------------
#>            0.83 | [0.38, 1.00]

x <- c(1.83,  0.50,  1.62,  2.48, 1.68, 1.88, 1.55, 3.06, 1.30)
y <- c(0.878, 0.647, 0.598, 2.05, 1.06, 1.29, 1.06, 3.14, 1.29)
rank_biserial(x, y, paired = TRUE)
#> r_rank_biserial |         95% CI
#> --------------------------------
#>           -0.78 | [-1.00, -0.20]
```

The functions in `rcompanion` give (slightly?) different results - they seem to be using slightly different methods for obtaining *r<sub><sub>RB</sub></sub>*, but our implementation here replicates the results from the original papers describing them, so I feel okay about that (:

**Comment by IndrajeetPatil** [comment]
Awesome, thanks!

Will this also work for one-sample design? 
`rcompanion` also supports (rRB) for such designs: https://rdrr.io/cran/rcompanion/src/R/wilcoxonOneSampleRC.r

**Comment by mattansb** [comment]
Yes, like Cohen's d, the one sample == the paired sample on diffs.

**Comment by mattansb** [comment]
- [ ] Add CI to Kendall's W
- [ ] Add Kendall's W to effectsize()
- [ ] Add rank_epsilon_squared to effectsize()
- [ ] is_effectsize_name

**Comment by mattansb** [comment]
closing this in favor of #258
