### ISSUE TITLE
cohens_d returns the wrong sign

### ISSUE THREAD

**Issue by mattansb** [easystats/effectsize#22]
`cohens_d`, `hedges_g` and `glass_delta` all return the wrong sign of the effect size (compared with the `t.test` function):

``` r
library(effectsize)

x <- 1:3
y <- 2:4

t.test(x,y)$statistic
#>         t 
#> -1.224745
cohens_d(x,y)
#> [1] 1
hedges_g(x,y)
#> [1] 0.8
glass_delta(x,y)
#> [1] 1
```

<sup>Created on 2019-12-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DominiqueMakowski** [comment]
Good catch, needs to be swapped then!

**Comment by mattansb** [comment]
Found this while building next weeks lesson!

I assigned you to this, as I'm not 100% clear on the internals (but is this @strengejacke 's function?)

**Comment by DominiqueMakowski** [comment]
I think it's mine 😁 (it should be fixed once we merge dev)

**Comment by strengejacke** [comment]
Mine would of course work properly. :-P
