### ISSUE TITLE
Support even more htests

### ISSUE THREAD

**Issue by mattansb** [easystats/effectsize#224]
https://github.com/easystats/insight/issues/258

For the next round of updates....

**Comment by mattansb** [comment]
Would prob need to split the code into a separate `effectsize.htest` file, as it is getting too bulky to maintain...

**Comment by IndrajeetPatil** [comment]
Do you think it would be possible to get effect size for `mcnemar.test` via `effectsize::effectsize` with these new changes?

**Comment by mattansb** [comment]
That's the plan!

--
Mattan S. Ben-Shachar, PhD student
Department of Psychology & Zlotowski Center for Neuroscience
Ben-Gurion University of the Negev
The Developmental ERP Lab

**Comment by mattansb** [comment]
Need to add `verbose` arg here too.

**Comment by IndrajeetPatil** [comment]
Listing a few other `htest` objects that can possibly be supported in `effectsize` (not necessarily for `0.4.5` release):
(cf. https://github.com/easystats/effectsize/issues/211#issuecomment-743186076)
- [ ] `stats::kruskal.test` 
- [ ] `stats::friedman.test`
- [ ] `stats::mcnemar.test`

**Comment by mattansb** [comment]
Yes, for those to work I would first need to finish #211 - I hope to get to this soon(ish).

**Comment by mattansb** [comment]
Closing this as at this point it is a duplicate of #211
