### ISSUE TITLE
readme

### ISSUE THREAD

**Issue by strengejacke** [easystats/effectsize#23]
seems we have done our job quite well when it comes to [documentation](https://blog.r-hub.io/2019/12/03/readmes/) (there are even some explicit examples from _effectsize_).

**Comment by DominiqueMakowski** [comment]
😍 top quality 👌 

(Leaves me wondering @strengejacke do you send bots everyday to search the internet for new mentions of easystats? 😁)

**Comment by mattansb** [comment]
Yeah, we're awesome ^_^

**Comment by strengejacke** [comment]
> do you send bots everyday to search the internet for new mentions of easystats?

My students. ;-)

No, actually I have feedly and twitter, and this post was in feedly.
