### ISSUE TITLE
ss_function for all effect size

### ISSUE THREAD

**Issue by mcfanda** [easystats/effectsize#243]
To make it easier to use the package in other packages and software, it will be nice to let the user choose which "anova" function to employ to compute the SS for all effect sizes (based on anova)

add ss_function option to the eta epsilon and omega
cheers
marcello

**Comment by mcfanda** [comment]
Solved by passing, for instance car::Anova() results to the effect size functions directly
thanks for the great package

**Comment by mattansb** [comment]
Ha, just what I was gonna suggest (:
Essentially for any `foo()` that give an anova-like table, `eta_squared(foo(model))` should work.

**Comment by mattansb** [comment]
Closing this (unless there's anything else)

**Comment by mcfanda** [comment]
great, thanks
