### ISSUE TITLE
CI for glass_delta

### ISSUE THREAD

**Issue by mattansb** [easystats/effectsize#255]
With the help of some simulations, I've found that CI's for `galss_delta` are totally f$*@ed up; the ncp method used for all other effect sizes seems to fail here, and I was unable to successfully implement the method suggested by [Hedges (1981; pp. 111)](https://sci-hub.st/10.3102/10769986006002107#).

Since bootstrapped CIs are on their way into `effectsize` (see #211 ), I am inclined to revert to doing the same here.

@DominiqueMakowski @IndrajeetPatil @strengejacke Any thoughts / suggestions / ideas?

**Comment by DominiqueMakowski** [comment]
Yeah, bootsrapped CIs seems to be a good alternative.

For my psycho package back in the days I think I remember implementing a bootstrapping-helper function to make it easy and consistent to get bootstrapped stuff. And @strengejacke if I recall correctly there was something like this in sjstats too no? Maybe we could add something like that somewhere at the base (insight or bayestestR?), as it could be potentially reused (in effectsize, parameters, performance, correlation...)

**Comment by mattansb** [comment]
Hmm I was thinking of simply using `boot` to do this (very fast). Not good?

**Comment by IndrajeetPatil** [comment]
I also think that bootstrapping is a good alternative, and we can just use `boot` to do this.

I think we already had routines to do this? What do we use for bootstrapping in `model_parameters` when `bootstrap = TRUE`?

**Comment by strengejacke** [comment]
Happy new year everyone!

> I think we already had routines to do this

https://github.com/easystats/parameters/blob/91a3bea7941751d975b1bd02e520ea662898efd2/R/describe_distribution.R#L54

**Comment by mattansb** [comment]
> https://github.com/easystats/parameters/blob/91a3bea7941751d975b1bd02e520ea662898efd2/R/describe_distribution.R#L54

Yup, this is exactly how I was going to do it (:
