### ISSUE TITLE
feature request: adding a new `Effectsize_Type` column for `htest` objects

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/effectsize#262]
This column would contain a more detailed description of the effect size than just the column name (kind of like `Method` column in `parameters::model_parameters`).

For example, in the following example, the `Effectsize_Method` column might have a value:
> Kendall's coefficient of concordance 

``` r
library(parameters)
library(effectsize)

wb <- aggregate(warpbreaks$breaks,
                by = list(w = warpbreaks$wool,
                          t = warpbreaks$tension),
                FUN = mean)

as.data.frame(model_parameters(friedman.test(x ~ w | t, data = wb)))
#>        Chi2 df         p                 Method
#> 1 0.3333333  1 0.5637029 Friedman rank sum test

as.data.frame(kendalls_w(x ~ w | t, data = wb))
#> Loading required namespace: boot
#>   Kendalls_W   CI CI_low CI_high
#> 1       0.25 0.95   0.25       1
```

<sup>Created on 2021-01-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
> Kendall's coefficient of concordance

But a coefficient is no method?

**Comment by mattansb** [comment]
Not sure what you mean - what method are Cohen' d, Phi, Cohen's f, OR?

**Comment by IndrajeetPatil** [comment]
Sorry, I was just trying to be consistent with `parameters` in terms of column names.

It can also be `Effectsize_Type`, etc. I am not committed to any one particular name.

**Comment by IndrajeetPatil** [comment]
> But a coefficient is no method?  🤷‍♂️ 

``` r
as.data.frame(correlation::correlation(iris))
#>     Parameter1   Parameter2          r     CI_low     CI_high         t  df
#> 1 Sepal.Length  Sepal.Width -0.1175698 -0.2726932  0.04351158 -1.440287 148
#> 2 Sepal.Length Petal.Length  0.8717538  0.8270363  0.90550805 21.646019 148
#> 3 Sepal.Length  Petal.Width  0.8179411  0.7568971  0.86483606 17.296454 148
#> 4  Sepal.Width Petal.Length -0.4284401 -0.5508771 -0.28794993 -5.768449 148
#> 5  Sepal.Width  Petal.Width -0.3661259 -0.4972130 -0.21869663 -4.786461 148
#> 6 Petal.Length  Petal.Width  0.9628654  0.9490525  0.97298532 43.387237 148
#>              p  Method n_Obs
#> 1 1.518983e-01 Pearson   150
#> 2 5.193337e-47 Pearson   150
#> 3 9.301992e-37 Pearson   150
#> 4 1.353994e-07 Pearson   150
#> 5 8.146457e-06 Pearson   150
#> 6 2.805002e-85 Pearson   150
```

<sup>Created on 2021-01-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mattansb** [comment]
In effectsize the column name would be `Person's r`.

**Comment by mattansb** [comment]
Still not sure what exactly this column would convey - a full description of what the coefficient represents?

**Comment by IndrajeetPatil** [comment]
> Still not sure what exactly this column would convey - a full description of what the coefficient represents?

Exactly. Just like the `Method` column gives a more detailed description of which `htest` results are reported. 

Sometimes the names themselves are clear enough, e.g., `Effectsize_Type = "Partial eta-squared"` won't add much to the output, which already contains this column. But sometimes it is more abstract, e.g., Kendall's _W_, where a little more context is helpful.

This is helpful mostly in the context where `broom`-naming conventions converts all effect size names to `estimate` and this information is lost, but if there was a column where this information was available, it would continue to be retained. 

https://github.com/easystats/insight/blob/55e042195d0bf1f63bb53ff0cb4769c31fca135d/R/standardize_names.R#L182-L185

**Comment by IndrajeetPatil** [comment]
For example, the following makes it very easy to write functions around `effectsize` functions (since the effect size is always called `estimate`), but leads to loss of valuable information about what the estimate represents:

``` r
library(effectsize)
library(insight)

Performance <-
  matrix(c(794, 86, 150, 570),
         nrow = 2,
         dimnames = list("1st Survey" = c("Approve", "Disapprove"),
                         "2nd Survey" = c("Approve", "Disapprove")))

standardize_names(cohens_g(Performance), "broom")
#>    estimate ci.width   conf.low conf.high
#> 1 0.1355932     0.95 0.07247554 0.1943674

standardize_names(cohens_d(1:10, y = c(7:20)), "broom")
#>    estimate ci.width  conf.low conf.high
#> 1 -2.131182     0.95 -3.140714 -1.091045
```

<sup>Created on 2021-01-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by mattansb** [comment]
This seems less of a "*`effectsize` should have this feature*" issue,
and more "*the `broom` convention of wiping meaning from column names is bad*"...

Like, should there be a method column here saying "linear regression coefficient"?
``` r
insight::standardize_names(
  parameters::model_parameters(
    lm(mpg ~ cyl + am, mtcars)
  )
  , style = "broom"
)
#>          term  estimate std.error    conf.low conf.high statistic df.error
#> 1 (Intercept) 34.522443 2.6031842 29.19833304 39.846552 13.261621       29
#> 2         cyl -2.500958 0.3608282 -3.23893412 -1.762981 -6.931159       29
#> 3          am  2.567035 1.2914280 -0.07423217  5.208302  1.987749       29
#>        p.value
#> 1 7.694408e-14
#> 2 1.284560e-07
#> 3 5.635445e-02
```

<sup>Created on 2021-01-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by IndrajeetPatil** [comment]
Agreed, but this issue is relevant **only** for `htest` objects. The `broom` conventions totally make sense for regression model objects, but they do not anticipate us adding effect size measures in `model_parameters` to `htest` outputs. 

But, as I said, having a consistent naming schema like this makes the life of package developers who are relying on these packages really easy because then they don't have to worry about every possible name one might encounter.

**Comment by mattansb** [comment]
`effectsize` (the package) has a consistent naming scheme - the name of the effect size is always clearly given as the column name in the df and in printing, that developers can rely upon. The problem you are describing here only arises when using additional packages / functions to sanitize the naming scheme. So your asking to add a column that in most cases would be redundant for when the column names are changed making the additional column not redundant?

If you want to preserve the effect size name after sanitation, you can:
``` r
library(effectsize)

model <- wilcox.test(1:4, 7:9)
ES <- effectsize(model, type = "g")
#> Loading required namespace: boot

na.omit(get_effectsize_label(colnames(ES)))
#> [1] "r (rank biserial)"
#> attr(,"na.action")
#> [1] 2 3 4
#> attr(,"class")
#> [1] "omit"
```

(this functions was specifically written with developers in mind!)

----

> but this issue is relevant only for htest objects.

`effectsize()` (the function) does not extract test info from the `htest`. In most cases, the output from `effectsize.htest()` is indistinguishable from the other functions because under the hood those other functions are called - data is recovered from the `htest` object, which is then discarded like an empty shell, a lifeless husk, a distant memory of something that once was but is no more. If someone wants both info about the object, and an effect size - that is what `parameters` is for, no?

**Comment by IndrajeetPatil** [comment]
Hmm, okay, that's fair enough. Thanks for indulging in my request. 😸 

Okay, I will close this here and I will make a `PR` in `parameters` to address this issue. You are right that this is more well-suited for `parameters` 👍 

Although the problem is that `parameters` allows multiple effect sizes to be returned simultaneously, which means the effect size description column would have to collate multiple descriptions. 

>  which is then discarded like an empty shell, a lifeless husk, a distant memory of something that once was but is no more

![image](https://user-images.githubusercontent.com/11330453/103875980-5cca1080-50d3-11eb-8171-2b667f76a4d7.png)

Has anyone administered the Voight-Kampff test to Mattan yet?!

**Comment by mattansb** [comment]
<img src="https://user-images.githubusercontent.com/35330040/103877413-b8999700-50dd-11eb-8cf4-d7bb1b61dabd.png" width="200"/>

**Comment by IndrajeetPatil** [comment]
Thanks for providing the alternative solution involving `get_effectsize_label`; it's working well for me. 

But I found an instance where it fails:

```r
library(statsExpressions)
library(effectsize)

mod <- 
  afex::aov_ez(
  id = "subject",
  dv = "desire",
  data = bugs_long,
  within = "condition"
)
#> Warning: Missing values for following ID(s):
#> 2, 10, 42, 64, 80
#> Removing those cases from the analysis.

ES <- eta_squared(mod)

get_effectsize_label(ES)
#> [1] NA NA NA NA NA
```

**Comment by mattansb** [comment]
Both `get_effectsize_label()` and `is_effectsize_name()` take a char vector, so `colnames` must be passed directly:

``` r
library(statsExpressions)
library(effectsize)

mod <- 
  afex::aov_ez(
    id = "subject",
    dv = "desire",
    data = bugs_long,
    within = "condition"
  )
#> Warning: Missing values for following ID(s):
#> 2, 10, 42, 64, 80
#> Removing those cases from the analysis.

(ES <- as.data.frame(eta_squared(mod)))
#>   Parameter Eta2_partial  CI    CI_low   CI_high
#> 1 condition     0.191355 0.9 0.1199495 0.2559906

get_effectsize_label(colnames(ES))
#> [1] NA               "Eta2 (partial)" NA               NA              
#> [5] NA
```

to be used for example, like this:

``` r
colnames(ES)[is_effectsize_name(colnames(ES))] <- 
  get_effectsize_label(colnames(ES))[is_effectsize_name(colnames(ES))]
ES
#>   Parameter Eta2 (partial)  CI    CI_low   CI_high
#> 1 condition       0.191355 0.9 0.1199495 0.2559906
```

<sup>Created on 2021-01-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by IndrajeetPatil** [comment]
Oh! Oops. 

I realized the code I was using was `get_effectsize_label(colnames(ES))[[1]]` and that returned `NA` only for eta- and omega-squared. I now see why. Switched to using `stats::na.omit` now, and it works just fine!

Sorry for the false positive.
