### ISSUE TITLE
inconsistent column names across one-way between-and within-subject ANOVAs

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/effectsize#266]
I understand that for one-way designs, the partial and non-partial eta- and omega-squared estimates are going to be the same. 
But the column name `effectsize` returns seems to depend on whether the design is repeated measures or not.

Shouldn't they be `Eta2 (partial)` and `Omega2 (partial)` in both cases, since the function defaults to `partial = TRUE`?

(Also, this is an inconsequential inconsistency for all intents and purposes, but one design returns a `Parameter` column, while the other doesn't.)

``` r
set.seed(123)
library(ipmisc)
library(effectsize)

# one-way between subjects ANOVA
mod_b <- oneway.test(extra ~ group, data = sleep)
  
# one-way within subjects ANOVA
mod_w <- 
  afex::aov_ez(
    id = "subject",
    dv = "desire",
    data = bugs_long,
    within = "condition"
  )

# eta-squared
eta_squared(mod_b, partial = TRUE)
#> Warning: `var.equal = FALSE` - effect size is an approximation.
#> Eta2 |       90% CI
#> -------------------
#> 0.16 | [0.00, 0.42]

eta_squared(mod_w, partial = TRUE)
#> Parameter | Eta2 (partial) |       90% CI
#> -----------------------------------------
#> condition |           0.19 | [0.12, 0.26]

# omega-squared
omega_squared(mod_b, partial = TRUE)
#> Warning: `var.equal = FALSE` - effect size is an approximation.
#> Omega2 |       90% CI
#> ---------------------
#> 0.11   | [0.00, 0.36]

omega_squared(mod_w, partial = TRUE)
#> Parameter | Omega2 (partial) |       90% CI
#> -------------------------------------------
#> condition |             0.08 | [0.03, 0.13]
```

<sup>Created on 2021-01-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by mattansb** [comment]
Not quite sure what the question is?

Throwing some stuff up:
1. partial and non-partiap are the same for one-way *between* designs (not equal in within designs).  
2. Elsewhere it was decided that for these cases, the "partial" title is misleading as nothing is actually partialled out.

Does this answer your Q?

**Comment by IndrajeetPatil** [comment]
> Elsewhere it was decided that for these cases, the "partial" title is misleading as nothing is actually partialled out.

Yes, this is what I was looking for!

I think I missed this conversation, but for me personally, I am not sure how it is misleading to return `"Eta2 (partial)"` as column name when `partial = TRUE`. In fact, it is more confusing for the user when it is `"Eta2"`. 

Also, since both of these estimates are identical for between-subjects design, this naming schema is not even _incorrect_. 
So, for the sake of consistency, I would expect these two contexts to return different column names **even if** they are going to be the same: 
- `"Eta2 (partial)"` if  `partial = TRUE`
- `"Eta2"` if  `partial = FALSE`
(same for omega)

The documentation already clears it up that they are going to be the same. So this shouldn't cause any confusion.

What do you think? (Happy to read the other discussion that took place that lead to this decision.)

**Comment by mattansb** [comment]
You can see it here: https://github.com/easystats/effectsize/issues/180

I think the issue is that `htest` and `afex_aov` don't give the same message - I need to add this there as well:

``` r
library(effectsize)

m <- lm(mpg ~ factor(cyl), mtcars)

eta_squared(m, partial = TRUE)
#> For one-way between subjects designs, partial eta squared is equvilant to eta squared.
#> Returning eta squared.
#> Parameter   | Eta2 |       90% CI
#> ---------------------------------
#> factor(cyl) | 0.73 | [0.57, 0.82]
```

<sup>Created on 2021-01-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by IndrajeetPatil** [comment]
Okay, thanks. I will leave this open then, as a reminder to add the same message for `htest` and `afex`.

**Comment by mattansb** [comment]
Done!

This actually forced me to simplify some of the code - which is good!

``` r
library(afex)
#> Loading required package: lme4
#> Loading required package: Matrix
#> Registered S3 methods overwritten by 'car':
#>   method                          from
#>   influence.merMod                lme4
#>   cooks.distance.influence.merMod lme4
#>   dfbeta.influence.merMod         lme4
#>   dfbetas.influence.merMod        lme4
#> ************
#> Welcome to afex. For support visit: http://afex.singmann.science/
#> - Functions for ANOVAs: aov_car(), aov_ez(), and aov_4()
#> - Methods for calculating p-values with mixed(): 'KR', 'S', 'LRT', and 'PB'
#> - 'afex_aov' and 'mixed' objects can be passed to emmeans() for follow-up tests
#> - NEWS: library('emmeans') now needs to be called explicitly!
#> - Get and set global package options with: afex_options()
#> - Set orthogonal sum-to-zero contrasts globally: set_sum_contrasts()
#> - For example analyses see: browseVignettes("afex")
#> ************
#> 
#> Attaching package: 'afex'
#> The following object is masked from 'package:lme4':
#> 
#>     lmer
library(effectsize)

mtcars$id <- seq_len(nrow(mtcars))

a1 <- aov_ez("id", "mpg", mtcars, between = "gear")
#> Converting to factor: gear
#> Contrasts set to contr.sum for the following variables: gear
eta_squared(a1)
#> For one-way between subjects designs, partial eta squared is equvilant to eta squared.
#> Returning eta squared.
#> Parameter | Eta2 |       90% CI
#> -------------------------------
#> gear      | 0.43 | [0.18, 0.59]

mo <- oneway.test(mpg ~ factor(gear), mtcars, var.equal = T)
eta_squared(mo)
#> For one-way between subjects designs, partial eta squared is equvilant to eta squared.
#> Returning eta squared.
#> Eta2 |       90% CI
#> -------------------
#> 0.43 | [0.18, 0.59]
```

<sup>Created on 2021-01-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
