### ISSUE TITLE
Should effect sizes for contingency table be adjusting to continuity correction?

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/effectsize#268]
I am showing an example here with Cramer's _V_, although the same issue also holds for Cohen's _g_.

Although chi-squared values change depending on whether this correction is applied, the effect sizes values don't, and I am not sure if that's the expected behavior.

``` r
library(effectsize)

x <- table(mtcars$am, mtcars$vs)

chisq.test(x, correct = TRUE)
#> 
#>  Pearson's Chi-squared test with Yates' continuity correction
#> 
#> data:  x
#> X-squared = 0.34754, df = 1, p-value = 0.5555

chisq.test(x, correct = FALSE)
#> 
#>  Pearson's Chi-squared test
#> 
#> data:  x
#> X-squared = 0.90688, df = 1, p-value = 0.3409

as.data.frame(cramers_v(x, correct = TRUE))
#>   Cramers_v   CI CI_low   CI_high
#> 1 0.1683451 0.95      0 0.5146525

as.data.frame(cramers_v(x, correct = FALSE))
#>   Cramers_v   CI CI_low   CI_high
#> 1 0.1683451 0.95      0 0.5146525
```

<sup>Created on 2021-01-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by mattansb** [comment]
This intentional. Look at this example:

``` r
library(effectsize)

M <- matrix(
  c(1, 4,
    4, 1), nrow = 2
)

Xsq1 <- chisq.test(M)[[1]]
#> Warning in chisq.test(M): Chi-squared approximation may be incorrect
chisq_to_cramers_v(Xsq1, n = sum(M), nrow = 2, ncol = 2, ci = NULL)
#> Cramer's V
#> ----------
#> 0.40

Xsq2 <- chisq.test(M * 100)[[1]]
chisq_to_cramers_v(Xsq2, n = sum(M * 100), nrow = 2, ncol = 2, ci = NULL)
#> Cramer's V
#> ----------
#> 0.60
```

The **magnitude** of the dependency is not changed between `M` and `M * 10`, but the effect size does due to the adjustment.

Should be:
``` r
cramers_v(M, ci = NULL)
#> Cramer's V
#> ----------
#> 0.60


cramers_v(M * 100, ci = NULL)
#> Cramer's V
#> ----------
#> 0.60
```

There are “adjusted” versions of these effect sizes, but I’m not quit sure how comparable these are in theory / practice:

``` r
cramers_v(M, ci = NULL, adjust = T)
#> Cramer's V (adj.)
#> -----------------
#> 0.53

cramers_v(M * 100, ci = NULL, adjust = T)
#> Cramer's V (adj.)
#> -----------------
#> 0.60
```

<sup>Created on 2021-01-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by IndrajeetPatil** [comment]
If I am not mistaken, you are talking about **bias correction** for Cramer's _V_, while my question is about **continuity correction** for chi-squared value, which doesn't seem to affect Cramer's _V_ in `effectsize`, correct?

Or are these two things related to each other?

**Comment by mattansb** [comment]
Yes, you're right - these are two separate things!

The continuity correction is a correction to the chisq statistic, ... but for the effect size, the "raw" statistic should be used as there is no issue with continuity, which is more to do with the shape of the sampling distribution than chisq the statistic (though maybe in the CI estimation? Might have to think about that some more...).

The bias correction is a separate thing altogether.

**Comment by mattansb** [comment]
Closing this for now as it is not relevant for the estimation of the effect size.

It is relevant for the CI, but...
1. Only in the 2x2 case.
2. Only for very small samples.
3. I don't know how to account for this in the CI 🤪
