### ISSUE TITLE
Bug in adjust() when multilevel is TRUE

### ISSUE THREAD

**Issue by strengejacke** [easystats/effectsize#274]
https://github.com/easystats/effectsize/blob/e6cc9dfdda271b12adf25b79b853291532d93e34/R/adjust.R#L172-L183

```r
      # Frequentist
    } else {
      if (multilevel) {
        if (!requireNamespace("lme4", quietly = TRUE)) {
          stop("This function needs `lme4` to be installed. Please install by running `install.packages('lme4')`.")
        }
        model <- insight::get_residuals(lme4::lmer(paste(formula, formula_random), data = data))
      } else {
        model <- lm(formula, data = data)
      }
    }
  }

  adjusted <- insight::get_residuals(model)
```

in the above code, `model` contains the residuals (`model <- insight::get_residuals(lme4::`),  and then you want to retrieve the residuals from the residuals later (see last line above).

**Comment by mattansb** [comment]
@DominiqueMakowski take a look?

**Comment by strengejacke** [comment]
I think you just need to remove `insight::get_residuals()` from line 176 and just keep the call to `lmer()`.

**Comment by strengejacke** [comment]
This bug actually broke quite some functionality in _correlation_, I think... 😢

**Comment by mattansb** [comment]
@strengejacke can you add some test/s?

I guess I can submit again soon, as an emergency patch?

**Comment by strengejacke** [comment]
I already added tests (https://github.com/easystats/effectsize/commit/d649d31b423bbf2163cbc2bc1a97dc6059da59d2).
