### ISSUE TITLE
rollback to 3.4

### ISSUE THREAD

**Issue by mattansb** [easystats/effectsize#277]

**Comment by mattansb** [comment]
@IndrajeetPatil @strengejacke 
I just can't get the R3.4 checks to pass... Will `effectsize` even install on 3.4 like this?

**Comment by strengejacke** [comment]
Not yet, only after parameters is accepted and effectsize is submitted to CRAN.

**Comment by mattansb** [comment]
Right, but that's not what's causing the fails...

**Comment by strengejacke** [comment]
For win: temporary
For Mac/Lin: File LICENSE is not mentioned in the DESCRIPTION file.

**Comment by mattansb** [comment]
Got it!
Now it's just failing on windows for some reason... any clues?

**Comment by IndrajeetPatil** [comment]
Hmm, this is a rather cryptic error, the one I've encountered exclusively with `easystats` packages:

```r
The downloaded source packages are in
	'C:\Users\runneradmin\AppData\Local\Temp\RtmpCSsgQQ\downloaded_packages'
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/easystats/bayestestR/contents/DESCRIPTION?ref=HEAD'
Calls: saveRDS ... download -> base_download -> base_download_noheaders
Execution halted
Error: Process completed with exit code 1.
```

I have no idea why it occurs, but usually just re-running the jobs solves it. I've restarted the job a couple of times, but the error is still observed, so not sure what to do here. 

It _might_ go away once `bayestestR` is no longer in `Remotes`.

**Comment by IndrajeetPatil** [comment]
Hmm, weird, if I remove `bayestestR`, I then see (https://github.com/easystats/effectsize/pull/297):

```r
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/easystats/parameters/contents/DESCRIPTION?ref=HEAD'
Calls: saveRDS ... download -> base_download -> base_download_noheaders
Execution halted
Error: Process completed with exit code 1.
```

**Comment by IndrajeetPatil** [comment]
It's fixed now. I think this had something to do with the `GitHub API` for `easystats`.

**Comment by mattansb** [comment]
Weird. Thanks!
