### ISSUE TITLE
non-bootstrap CI for r_BS

### ISSUE THREAD

**Issue by mattansb** [easystats/effectsize#279]
https://github.com/jasp-stats/jasp-desktop/blob/a45e080ba8d1afeb051867604c904e0ea5ed2b8e/JASP-Engine/JASP/R/ttestindependentsamples.R#L285-L304

https://github.com/jasp-stats/jasp-desktop/blob/a45e080ba8d1afeb051867604c904e0ea5ed2b8e/JASP-Engine/JASP/R/ttestonesample.R#L246-263

**Comment by IndrajeetPatil** [comment]
Do you think this will be part of `effectsize 0.5`?

**Comment by mattansb** [comment]
Yeah, think so.

I would like to find a reference for this equation tho... :/

**Comment by bwiernik** [comment]
That appears to be the "effective sample size" for a dichotomous variable with uneven split. Hedges and Olkin 1985.

**Comment by mattansb** [comment]
@bwiernik I can't seem to find that in "Statistical methods for meta-analysis 1985"... :/
