### ISSUE TITLE
standardize_parameters() refit disrepancy with standardize()

### ISSUE THREAD

**Issue by IsadoraBM** [easystats/effectsize#292]
From [standardize_parameter vignette](https://cran.r-project.org/web/packages/effectsize/vignettes/standardize_parameters.html#refit-re-fitting-the-model-with-standardized-data): 
_"refit": Re-fitting the model with standardized data
This method is based on a complete model re-fit with a standardized version of data. Hence, this method is equal to standardizing the variables before fitting the model._ 

Yet, if I standardize the data with `df_z<- standardize(df, two_sd = TRUE)` first and run the model, the estimates are not similar (not a rounding issue) to standardize_parameter. I'm running lfe::felm() in case that matters. 

Shouldn't they be the same? 

Example of output differences:
From `lfe::felm( model, data = df_z)`
```r
 Age  EducationMedium     EducationLow EducationUnknown       GenderMale 
         0.09020          0.03106          0.04371         -0.03286         -0.05206 
           Media         Year2019 
         0.02237         -0.05911 
```
From `effectsize::standardize_parameters(model, method = "refit", two_sd = TRUE, robust = FALSE)`
model
```r
# Standardization method: refit

Parameter        | Coefficient (std.) |       95% CI
------------------------------------------------------
Age              |               0.18 | [ 0.16,  0.20]
EducationMedium  |               0.06 | [ 0.04,  0.08]
EducationLow     |               0.09 | [ 0.06,  0.12]
EducationUnknown |              -0.07 | [-0.10, -0.03]
GenderMale       |              -0.10 | [-0.12, -0.09]
Media            |               0.04 | [ 0.03,  0.06]
Year2019         |              -0.12 | [-0.14, -0.10]
```

**Comment by mattansb** [comment]
@IsadoraBM I am unable to reproduce the issue with other data.

``` r
library(lfe)
#> Loading required package: Matrix
library(effectsize)
```

<details>
<summary>
Make data
</summary>

``` r
set.seed(42)
n <- 1e3

d <- data.frame(
  # Covariates
  x1 = rnorm(n),
  x2 = rnorm(n),
  # Individuals and firms
  id = factor(sample(20, n, replace=TRUE)),
  firm = factor(sample(13, n, replace=TRUE)),
  # Noise
  u = rnorm(n)
)

# Effects for individuals and firms
id.eff <- rnorm(nlevels(d$id))
firm.eff <- rnorm(nlevels(d$firm))

# Left hand side
d$y <- d$x1 + 0.5*d$x2 + id.eff[d$id] + firm.eff[d$firm] + d$u
```

</details>

``` r
## Estimate the model and print the results
est <- felm(y ~ x1 + x2 | id + firm, data = d)

standardize(est, two_sd = TRUE)
#>     x1     x2 
#> 1.0505 0.4857

standardize_parameters(est, two_sd = TRUE)
#> # Standardization method: refit
#> 
#> Parameter | Coefficient (std.) |       95% CI
#> ---------------------------------------------
#> x1        |               1.05 | [0.99, 1.11]
#> x2        |               0.49 | [0.42, 0.55]
#> 
#> - Scaled by two SD(s) from the mean.
```

<sup>Created on 2021-02-11 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>


 Can you share a full reprex?

**Comment by strengejacke** [comment]
Could it be due to missing data? Standardization by refitting the model is based on the complete observations in the model, standardization of the data before fitting the model just looks for each variable separately, and if some variables have (more) missing data, there might be different results.

**Comment by IsadoraBM** [comment]
I didn't consider this :woman_facepalming:  Thanks!
So the estimates from the standardized data pre-modeling are the accurate ones, thanks for clarifying. Might be worth putting a warning or note in the standardize_parameters vignette

**Comment by mattansb** [comment]
Hmmm this actually is already in the docs - see the `remove_na` argument in [`standardize()`](https://easystats.github.io/effectsize/reference/standardize.html).

**Comment by IsadoraBM** [comment]
So maybe a link to that in standardize_parameters (?), probably not everyone will read both. I did and I still missed it (that aside, they were impressively well written I have to say). Thanks again for the info.

Isadora

________________________________

**Comment by mattansb** [comment]
Done (:

Thanks @IsadoraBM !
