### ISSUE TITLE
Adding `Interpretation` and `Rule` column to outputs?

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/effectsize#294]
Doing so would force users to confront the interpretability of their effect sizes and doesn't introduce an additional burden of using a different function to interrogate their effect sizes.

And, of course, the relevant functions will gain a `rule` argument that lets users choose a rule of their liking.

For example,

```r
cohens_d(sleep$extra, sleep$group, rule = "cohen1988")
#> Cohen's d |        95% CI | Interpretation | Rule
#> --------------------------------------------------
#> -0.83     | [-1.74, 0.10] | Large | cohen1988
#> 
#> - Estimated using pooled SD.
```

What do you think?

**Comment by mattansb** [comment]
I def don't like this as the default behavior - not a huge fan of these rules of thumb in general, which don't account for measurement error, differences between fields and sub-fields, design, etc.

But maybe we can add these as printing options?

**Comment by IndrajeetPatil** [comment]
Hmm, then we don't have to make this a default behavior. 

We can have `rule = NULL` as a default, and then only if the users choose a rule will the function return interpretation. 
We can then assume that the user is going to choose a rule of thumb most relevant for their field/sub-field.

How does that sound?

**Comment by mattansb** [comment]
For the printing? Yeah, that sounds good!

This will require some tinkering with the way I have the various printing functions set up - will have to see what makes most sense.

**Comment by DominiqueMakowski** [comment]
well but it's easier to show it by default to bring the user's attention onto it, enabling then an informed disregarding or tweaking. Otherwise people don't know the feature exist, and then just continue applying Cohen's rules anyway without being invited to read more about them. I.e., having a default intepretation 1) help people discover that there more rules of thum that the sacred Cohen, and 2) thus also adds some mitigation and 3) invites thinking in depth about it

**Comment by DominiqueMakowski** [comment]
That said, I'm not convinced of the additional column for printing, in general columns should be used for stuff that can vary in the columns rather than for fixed, and I don't see why the rules should vary: people should decide on one framework, justify it, and then stick to it

**Comment by mattansb** [comment]
> well but it's easier to show it by default

It's def not easier - look, rn it shows nothing, and that is super easy to implement ^_^

 > That said, I'm not convinced of the additional column for printing

Maybe as a footer, then? 

---

This is why the `interpret_*` function belong in `report` - are we gonna start adding `interpert_r2()` in `performance`? Or `interpert_bf()` in `bayestestR`? or `interpret_oddsratio()` is `parameters`?
I think not - interpretation is on the *next* level of statistical work, when reporting.

(Just convincing me more that this is not a great idea to have *here*... Once `report` is on CRAN I think this issue will be obsolete,  instead we will have `report` methods for `effectsizes`'s effect sizes...)

**Comment by IndrajeetPatil** [comment]
> Once report is on CRAN I think this issue will be obsolete

But this assumes that once `report` is on `CRAN`, all users of `effectsize`, `performance`, and `bayetestR` are going to just abandon these packages in favor of using only `report`. 

There will continue to be a large base of users who will use these packages outside `report` context, and this feature will be helpful for them. 

> This is why the interpret_* function belong in report - are we gonna start adding interpert_r2() in performance? Or interpert_bf() in bayestestR? or interpret_oddsratio() is parameters?

That would be neat as well 😅
But the first place where I'd actually _expect_ such a feature is a package dedicated entirely to effect sizes.

**Comment by IndrajeetPatil** [comment]
> It's def not easier - look, rn it shows nothing, and that is super easy to implement ^_^

Amen to that 🤣

**Comment by IndrajeetPatil** [comment]
And once you provide these in a dataframe, people can do whatever their heart desires with them

``` r
library(effectsize)
library(dplyr)
library(ggstatsplot)
library(ggplot2)
library(ggrepel)

mod <- stats::lm(formula = wt ~ am * cyl, data = mtcars)

df <-
  eta_squared(mod) %>%
  dplyr::mutate(interpretation = c("large", "medium", "small")) %>%
  parameters::standardize_names(style = "broom")

ggcoefstats(df) + geom_label_repel(aes(label = interpretation))
```

![](https://i.imgur.com/bXsePSz.png)

<sup>Created on 2021-02-15 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by mattansb** [comment]
I am 100% against having these by default, anywhere. (Yes, I know I'm a pain in the @$$ but it's a package deal!)

The best I can do is accommodate an *optional* adding of these in the printing or by passing the data.frame to the interpret function (extract the right column with is_effectsize_name? I'll look into this)?

@IndrajeetPatil in the mean time, do you want to add in to all the examples the use of the relevant interpret functions? And/or expand on the interpretation vignette?

**Comment by IndrajeetPatil** [comment]
> @IndrajeetPatil in the mean time, do you want to add in to all the examples the use of the relevant interpret functions? And/or expand on the interpretation vignette?

I am not sure what you mean. Add `interpret_` functions to all relevant examples?

Should I not first wait and see the changed behavior of the primary effect size functions to understand how I can add interpretations to the existing examples via these functions, and not `interpret_` functions?

**Comment by mattansb** [comment]
> I am not sure what you mean. Add interpret_ functions to all relevant examples?

Yes.

> Should I not first wait and see the changed behavior of the primary effect size functions...

I don't think this will be directly implemented in these functions - maybe in the print / allow for data.frame input in the `interpret_ *()` functions (I like this idea most - it's clean, will return a data.frame...). 
Anyway, if you're main concern is discoverability of the `interpret_*()`, I just thought a good first step would be to add them as examples.

**Comment by IndrajeetPatil** [comment]
Oh, I see. 

Sure, will do that. When are you planning to submit to CRAN?

**Comment by mattansb** [comment]
I need to submit by 26/2 without the vignettes (:

**Comment by IndrajeetPatil** [comment]
I can add a new function to interpret Cramer's _V_, but I am not sure if you are happy with following these conventions:

https://rcompanion.org/handbook/H_10.html

<img width="1109" alt="Screenshot 2021-02-21 at 10 42 12" src="https://user-images.githubusercontent.com/11330453/108621208-965f9c80-7431-11eb-972c-4e5f64da1983.png">

Also, it's not going to be as straightforward since the interpretation depends on the value of `k`.

**Comment by strengejacke** [comment]
I would prefer to keep such information as attribute, not as column. And for print, it should probably indeed go into the footer.

**Comment by IndrajeetPatil** [comment]
I agree that the exact rule should be returned as an attribute, and not a column. 

But how is interpretation going to be an attribute when there is more than one term in the output? 
Will the attribute be a `list` then?

For example,

``` r
library(effectsize)

mod <- lm(formula = wt ~ am * cyl, data = mtcars)

eta_squared(mod)
#> Parameter | Eta2 (partial) |       90% CI
#> -----------------------------------------
#> am        |           0.63 | [0.44, 0.75]
#> cyl       |           0.47 | [0.24, 0.63]
#> am:cyl    |       2.26e-03 | [0.00, 0.09]
```

<sup>Created on 2021-02-21 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by mattansb** [comment]
> I can add a new function to interpret Cramer's V, but I am not sure if you are happy with following these conventions:

Looks fine - also phi and cohens_w (which are the same). Feel free to make a PR.
(I am never happy with any convention of interpretation!)

---

> D: I would prefer to keep such information as attribute, not as column. And for print, it should probably indeed go into the footer.

> I: But how is interpretation going to be an attribute when there is more than one term in the output?

I agree with both of you. For single index it would be easy to add to the footnote.

```R
cohens_d(1:3)
#> Cohen's d |        95% CI
#> -------------------------
#> 2.00      | [-0.16, 5.03]
#> 
#> - Interpretation [cohen1988]: large
```

For multiple values, I was thinking of something like this, maybe?

```R
mod <- lm(formula = wt ~ am * cyl, data = mtcars)

interpret_eta_squared(eta_squared(mod))
#> Parameter | Eta2 (partial) | Interpretation
#> -------------------------------------------
#> am        |           0.63 |          large
#> cyl       |           0.47 |          large
#> am:cyl    |       2.26e-03 |     very small
#> 
#> - Interpretation rule: field2013
```

But I'd have to see how practical it is to detect the correct column in all cases?

Open to suggestions... Maybe it's okay to have different "test" vs "model" outputs?

**Comment by strengejacke** [comment]
> But how is interpretation going to be an attribute when there is more than one term in the output?

True, a column might be better then, or simply put the complete rule into the footer (like `* = p < 0.05; ** = p < 0.01, *** = p < 0.001`).

**Comment by IndrajeetPatil** [comment]
But I think it would be better to follow one convention across contexts (one term or many terms):
either we have it in a column **or** we add it as an attribute.

Otherwise, it would be very difficult for people (including me) to write functions around `effectsize` functions because the output will depend on the number of terms.

**Comment by IndrajeetPatil** [comment]
@mattansb Do you think this will be resolved in time for the next release?

**Comment by mattansb** [comment]
Have we even come to an agreement as to what this would look like? 😳

**Comment by mattansb** [comment]
Yes, this sounds good.
But I don't think it will make it into the small-update this week. But will for the next (when I finally have some time to actually work-work!)

**Comment by IndrajeetPatil** [comment]
Do you think this will by any chance be part of the next cycle?

**Comment by mattansb** [comment]
Doubt.... Sorry mate... 

What do you think about an `add_interpretation()` function (with no default method!) that adds the column (+ method as an attr that will be printed).

This can then be used like so (mockup):

```R
lm(formula = wt ~ am * cyl, data = mtcars) |>
  eta_squared() |>
  add_interpretation(rules = "field2013")
#> # Effect Size for ANOVA (Type I)
#> 
#> Parameter | Eta2 (partial) |       90% CI | Interpretation
#> ----------------------------------------------------------
#> am        |           0.63 | [0.44, 0.75] | large
#> cyl       |           0.47 | [0.24, 0.63] | large
#> am:cyl    |       2.26e-03 | [0.00, 0.09] | very small
#>
#> (Interpretation rules: field2013)
```

**Comment by bwiernik** [comment]
That looks good to me so long as we require users to tell us which rules they want

**Comment by DominiqueMakowski** [comment]
> we require users 

Since we explicitly print the rules I think having defaults is fine, the info is not hidden

**Comment by mattansb** [comment]
> Since we explicitly print the rules I think having defaults is fine, the info is not hidden

No 🙃

---

``` r
library(effectsize)

cohens_d(mpg ~ am, data = mtcars) |>
  add_interpretation(x, rules = "cohen1988")
#> Cohen's d |         95% CI | Interpretation
#> -------------------------------------------
#> -1.48     | [-2.27, -0.67] |          large
#> 
#> - Estimated using pooled SD.
#> (Interpretation rule: cohen1988)

glass_delta(mpg ~ am, data = mtcars) |>
  add_interpretation(x, rules = "cohen1988")
#> Glass' delta |         95% CI | Interpretation
#> ----------------------------------------------
#> -1.17        | [-1.93, -0.39] |          large
#> 
#> (Interpretation rule: cohen1988)

cohens_d(mpg ~ am, data = mtcars) |>
  add_interpretation(x, rules = rules(1, c("tiny", "yeah okay")))
#> Cohen's d |         95% CI | Interpretation
#> -------------------------------------------
#> -1.48     | [-2.27, -0.67] |      yeah okay
#> 
#> - Estimated using pooled SD.
#> (Interpretation rule: Custom rules)

lm(formula = wt ~ am * cyl, data = mtcars) |>
  eta_squared() |>
  add_interpretation(rules = "field2013")
#> # Effect Size for ANOVA (Type I)
#> 
#> Parameter | Eta2 (partial) |       90% CI | Interpretation
#> ----------------------------------------------------------
#> am        |           0.63 | [0.44, 0.75] |          large
#> cyl       |           0.47 | [0.24, 0.63] |          large
#> am:cyl    |       2.26e-03 | [0.00, 0.09] |     very small
#> 
#> (Interpretation rule: field2013)

X <- chisq.test(mtcars$am, mtcars$cyl == 4)
#> Warning in chisq.test(mtcars$am, mtcars$cyl == 4): Chi-squared approximation may
#> be incorrect
oddsratio(X) |> add_interpretation("chen2010")
#> Odds ratio |        95% CI | Interpretation
#> -------------------------------------------
#> 8.53       | [1.62, 45.06] |          large
#> 
#> (Interpretation rule: chen2010)
cramers_v(X) |> add_interpretation("lovakov2021")
#> Cramer's V |       95% CI | Interpretation
#> ------------------------------------------
#> 0.47       | [0.13, 0.82] |          large
#> 
#> (Interpretation rule: lovakov2021)
```

<sup>Created on 2021-07-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by mattansb** [comment]
Changes the function name to be a method of `interpert()`:

``` r
library(effectsize)

cohens_d(mpg ~ am, data = mtcars) |>
  interpret(d, rules = "cohen1988")
#> Cohen's d |         95% CI | Interpretation
#> -------------------------------------------
#> -1.48     | [-2.27, -0.67] |          large
#> 
#> - Estimated using pooled SD.
#> (Interpretation rule: cohen1988)
```

<sup>Created on 2021-07-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by bwiernik** [comment]
Do we want to add a message saying "You probably don't want Cohen 1988"?

**Comment by mattansb** [comment]
lol

I think that's currently the default in `interpret_d`. Do you want to change that there + add a note? I'm down for that!

**Comment by bwiernik** [comment]
Let me which up a quick vignette on the 20 other benchmarks that exist

**Comment by mattansb** [comment]
You are more than welcome to do so!

**Comment by strengejacke** [comment]
We need a `format_interpretation()` or `format_rule()` function ;-)

**Comment by mattansb** [comment]
What would that do? 🤔

**Comment by DominiqueMakowski** [comment]
format_rule would change `cohen1998` to like `"Cohen et al. (1998)"` right?

**Comment by strengejacke** [comment]
Yes, something like that.

**Comment by strengejacke** [comment]
https://easystats.github.io/parameters/reference/format_df_adjust.html
https://easystats.github.io/parameters/reference/format_p_adjust.html

**Comment by mattansb** [comment]
Custom rules can be used here, so it can essentially be anything:

``` r
library(effectsize)

myRules <- rules(c(0.05, 0.1), c("Tiny", "Large", "Super Duper HUGE!"), 
                 name = "my awesome rules that everyone should use.pdf")

lm(mpg ~ ., mtcars) |> 
  eta_squared(ci = NULL) |>
  interpret(rules = myRules)
#> # Effect Size for ANOVA (Type I)
#> 
#> Parameter | Eta2 (partial) |    Interpretation
#> ----------------------------------------------
#> cyl       |           0.85 | Super Duper HUGE!
#> disp      |           0.20 | Super Duper HUGE!
#> hp        |           0.06 |             Large
#> drat      |           0.10 | Super Duper HUGE!
#> wt        |           0.34 | Super Duper HUGE!
#> qsec      |           0.03 |              Tiny
#> vs        |       8.79e-04 |              Tiny
#> am        |           0.09 |             Large
#> gear      |       6.54e-03 |              Tiny
#> carb      |       2.75e-03 |              Tiny
#> 
#> (Interpretation rule: my awesome rules that everyone should use.pdf)
```

<sup>Created on 2021-08-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by DominiqueMakowski** [comment]
yes but for the ones that correspond to a citation it'd be nice to print the "formatted" citation, it's basically copying and exporting this function :)

https://github.com/easystats/report/blob/fb509f8b7ea2c2b959173f38dc838c0eea855589/R/report_effectsize.R#L90-L113

**Comment by DominiqueMakowski** [comment]
aktchually we could have a generic `format_reference()` in insight/datawizard where we list a lot of them, since we have also methods called with ref names like that throughout easystats, so having one function to try to recognize and format would be convenient

**Comment by strengejacke** [comment]
One day we end up having a single function that generates complete papers. :-)

**Comment by bwiernik** [comment]
> aktchually we could have a generic format_reference() in insight/datawizard where we list a lot of them, since we have also methods called with ref names like that throughout easystats

Ooh! we could even include an option to format these as pandoc citations for use in RMarkdown documents!

**Comment by IndrajeetPatil** [comment]
At this rate, we are heading towards a new package called `{easyformat}` with all the formatting functions for text and tables 😅

**Comment by bwiernik** [comment]
I would import that...

**Comment by IndrajeetPatil** [comment]
I think it might just be worth it given how much headache formatting is. But let’s finish with these cycles first 🥵
