### ISSUE TITLE
R CMD check on current pkgs

### ISSUE THREAD

**Issue by strengejacke** [easystats/effectsize#295]
@mattansb could you please check effectsize if all tests pass the current insight on CRAN and the current master/main of parameters? In particular checks for parameters is important, because I'm planning to submit soon.

**Comment by mattansb** [comment]
Checking... https://github.com/easystats/effectsize/actions/runs/571112965

**Comment by IndrajeetPatil** [comment]
Nope, tests related to `standardize_parameters (exponentiate)` are failing. 

But we will be submitting `effectsize` to `CRAN` pretty soon anyway, won't we?

**Comment by mattansb** [comment]
@IndrajeetPatil why do you assume this error is in `effectsize`??

---

It seems that `parameters` no longer allows for `exponentiate` for gaussian models (it use to), which is what causes the error.

``` r
mod_b <- glm(am ~ mpg + cyl + hp,
             data = mtcars,
             family = gaussian()
)

parameters::model_parameters(mod_b)
#> Parameter   | Coefficient |       SE |        95% CI | t(28) |     p
#> --------------------------------------------------------------------
#> (Intercept) |       -0.77 |     0.81 | [-2.35, 0.81] | -0.96 | 0.347
#> mpg         |        0.06 |     0.02 | [ 0.02, 0.10] |  3.01 | 0.005
#> cyl         |       -0.15 |     0.08 | [-0.31, 0.01] | -1.87 | 0.072
#> hp          |    5.75e-03 | 1.73e-03 | [ 0.00, 0.01] |  3.33 | 0.002


parameters::model_parameters(mod_b, exponentiate = TRUE) # does nothing
#> Parameter   | Coefficient |       SE |        95% CI | t(28) |     p
#> --------------------------------------------------------------------
#> (Intercept) |       -0.77 |     0.81 | [-2.35, 0.81] | -0.96 | 0.347
#> mpg         |        0.06 |     0.02 | [ 0.02, 0.10] |  3.01 | 0.005
#> cyl         |       -0.15 |     0.08 | [-0.31, 0.01] | -1.87 | 0.072
#> hp          |    5.75e-03 | 1.73e-03 | [ 0.00, 0.01] |  3.33 | 0.002
```

<sup>Created on 2021-02-16 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by IndrajeetPatil** [comment]
Perdón

![giphy](https://user-images.githubusercontent.com/11330453/108046098-88caa100-7044-11eb-8bad-9b01f5cea87f.gif)

**Comment by mattansb** [comment]
I guess that's what you get with [56% coverage](https://codecov.io/gh/easystats/parameters) :P

**Comment by strengejacke** [comment]
> It seems that parameters no longer allows for exponentiate for gaussian models (it use to)

Should we revert that change? I did this because of `compare_parameters()`. When you have, say, linear and logistic regression, and you want regular coefficient and odds ratios (i.e. exponentiated log-odds), `exponentiate` should not apply to linear models. Does this make sense?

**Comment by mattansb** [comment]
I think if anyone is comparing two completely different models, they have other issues...

Anyway, exp(b) in a gaussian likelihood is still informative sometimes, so I suggest adding it back.

**Comment by strengejacke** [comment]
> I think if anyone is comparing two completely different models, they have other issues...

Probably the same issues as when using exp(b) for Gaussian models ;-)

But I'll revert the change.

**Comment by strengejacke** [comment]
Ok, done. Please do final check before submission

**Comment by mattansb** [comment]
I'll be home in about 2 hours. If you want before, feel free to push some white space changes to trigger a test (:

**Comment by strengejacke** [comment]
No hurry...

**Comment by IndrajeetPatil** [comment]
I reran the tests on the `main` branch of `effectsize` and they pass with the master branch of `parameters`, which is in `Remotes`.

The builds which are failing don't have anything to do with failing tests, but other things.

<img width="321" alt="Screenshot 2021-02-16 at 14 59 23" src="https://user-images.githubusercontent.com/11330453/108072820-a78e5f00-7067-11eb-9f3f-b26445e657d8.png">

**Comment by mattansb** [comment]
I'll be home soon and will take a look to make sure (:

--
Mattan S. Ben-Shachar, PhD student
Department of Psychology & Zlotowski Center for Neuroscience
Ben-Gurion University of the Negev
The Developmental ERP Lab

**Comment by mattansb** [comment]
Looks good on `parameters`.

Any idea what that weird error is on macOS current?

**Comment by strengejacke** [comment]
> Any idea what that weird error is on macOS current?

I _think_ there also needs to be a vignette-folder with "additional.rmd" as file present. Try to build a source package and inspect the tar-ball, in your current settings, the "additional.rmd" file is in `inst/docs`, but no vignettes-folder.

**Comment by mattansb** [comment]
But it's not in that folder (if you look there...) - and it is in the vignette-folder.
Or am I missing something?

**Comment by strengejacke** [comment]
Not after building the source package

**Comment by mattansb** [comment]
How do I change that? 😲

**Comment by strengejacke** [comment]
I'm not sure which regex-style RBuildignore uses, but I excluded all vignette-files except this one:
https://github.com/easystats/parameters/blob/main/.Rbuildignore

**Comment by mattansb** [comment]
This https://github.com/easystats/effectsize/commit/3d4826ea7d345765af5e8d456f219f12c7fd2fd3 seems to have solved it (I hate regexp...).

@DominiqueMakowski Are you submitting bayestestR soon? I'll submit after you...

**Comment by IndrajeetPatil** [comment]
Closing this as there is no longer a need to submit these packages asap.
