### ISSUE TITLE
LaTeX equations in vignettes are not rendered on CRAN

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/effectsize#302]
For example, for [this vignette](https://cran.r-project.org/web/packages/effectsize/vignettes/anovaES.html), I see:

<img width="1106" alt="Screenshot 2021-02-28 at 17 47 59" src="https://user-images.githubusercontent.com/11330453/109426319-55e1bf00-79ed-11eb-8cc3-e0bf0d410de2.png">

I think the solution is going to look something like the following:
https://tex.stackexchange.com/questions/171711/how-to-include-latex-package-in-r-markdown

That said, `pkgdown` does render the equations properly on the website, but I think a non-substantial users look at the vignettes on CRAN, so this is worth fixing.

**Comment by mattansb** [comment]
Looks like an Indra-kind of issue ^_^
