### ISSUE TITLE
Allow a `reference` arg to be passed to standardize()

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/effectsize#314]
Similarly to `unstandardize()` we could allow a `reference` argument to be passed to `standardize()`, to standardize the data at hand not based on the actual location/scale of the data, but of that of some other data. That would be super useful for instance for data/visualization grids where one could standardize the predictors a posterior, or in case of test/training sets or other subsets of some original data.

**Comment by mattansb** [comment]
This would be like the `range` arg in `change_scale()`, yes?

So this would be:
1. Find (2)sd/mad from a reference vector / data frame
2. Use that to standardize a different vector / data frame?

Sounds easy enough. Wanna try a PR for this?

I don't see how this can work for `group_df` objects though... Thoughts?

**Comment by DominiqueMakowski** [comment]
> Wanna try a PR for this?

I can give it a go in a few days once I'm out the forest but if you have an idea how don't hesitate :)

> I don't see how this can work for group_df

Mmh good question 🤔

**Comment by mattansb** [comment]
I just finished moving apartments (which is why I've been so incognito lately - have you missed me??), still playing catch up with a zillion other things...

**Comment by DominiqueMakowski** [comment]
haha no worries I'll put that on my todo list, enjoy your new nest :)

**Comment by bwiernik** [comment]
I would think that the same grouping would be applied in the reference frame.

**Comment by mattansb** [comment]
So both the `x` and the `reference` would have to be `grouped_df`s?

What if one have groups the other doesn't? 🤔

**Comment by DominiqueMakowski** [comment]
I'd say we error if the reference doesn't have the same groups as the input, because any other solutions (e.g., grouping the reference a posteriori) seems risky

**Comment by bwiernik** [comment]
Yeah, exactly. I think so long as the data frames have the same grouping variables and all of the group levels in `x` are present in `reference`, we are fine. If the user wants something else (e.g., standardized against the total sample), they can adjust their data frames beforehand.

**Comment by mattansb** [comment]
@DominiqueMakowski think this can happen for v0.5?

**Comment by DominiqueMakowski** [comment]
what's the deadline for v0.5 ^^

**Comment by IndrajeetPatil** [comment]
lol, no deadline. It will be good for `statsExpressions` to go without a breakage for more than a month 😭
