### ISSUE TITLE
revisiting defaults for Cohen's d and Hedges' g

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/effectsize#316]
In light of https://psyarxiv.com/tu6mp/, should we change our defaults here to `FALSE` to follow the best practices?

https://github.com/easystats/effectsize/blob/b767843d2913b62c7a90bd4bd7836a6d57376794/R/cohens_d.R#L96

and

https://github.com/easystats/effectsize/blob/b767843d2913b62c7a90bd4bd7836a6d57376794/R/cohens_d.R#L142

The differences are minimal, so this shouldn't be a troublesome change either for the users or for the developers.

**Comment by mattansb** [comment]
I'm actually not against this - the default for `t.test()` is `var.equal = FALSE`!

However, aren't most people expecting a pooled SD? 🤔

@DominiqueMakowski @strengejacke @bwiernik thoughts?

**Comment by bwiernik** [comment]
If we compute the effect size from an htest or model object, we should compute following the treatment of sigma in that object. 

Otherwise, I think most folks will be expecting a pooled SD. So computing based on means/SDs or raw data should probably default to pooled IMO.

As an aside, I have code to compute standardized mean differences and intervals from lm objects. Remind me to make a P.R. or both that.

**Comment by mattansb** [comment]
> If we compute the effect size from an htest or model object, we should compute following the treatment of sigma in that object.

That is already implemented 🤗
``` r
t.test(mtcars$mpg ~ factor(mtcars$am)) %>% 
  effectsize::cohens_d()
#> Cohen's d |         95% CI
#> --------------------------
#> -1.41     | [-2.26, -0.53]
#> 
#> - Estimated using un-pooled SD.

t.test(mtcars$mpg ~ factor(mtcars$am), var.equal = TRUE) %>% 
  effectsize::cohens_d()
#> Cohen's d |         95% CI
#> --------------------------
#> -1.48     | [-2.27, -0.67]
#> 
#> - Estimated using pooled SD.
```

<sup>Created on 2021-05-10 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

> As an aside, I have code to compute standardized mean differences and intervals from lm objects. Remind me to make a P.R. or both that.

Yes please!

**Comment by mattansb** [comment]
Unless anyone has anything to add, I think we'll leave the default as is;

The fact that the `htest` object is treated properly, and that the docs now mention that the unpooled version should be used with Welch's test seems to me to be enough.

**Comment by DominiqueMakowski** [comment]
I don't have much to add here I trust your judgment

**Comment by strengejacke** [comment]
> I don't have much to add here I trust your judgment

I agree.
