### ISSUE TITLE
supporting `ci_method` attribute for all effect sizes

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/effectsize#320]
Follow up of https://github.com/easystats/effectsize/issues/280

The `ci_method` attribute currently contains some additional information about how confidence intervals were computed.

And this is available for some effect sizes:

``` r
library(effectsize)

# helper
get_ci_method <- purrr::compose(tibble::as_tibble, purrr::attr_getter("ci_method"))

# compute effect sizes
mod <- effectsize::cohens_d(sleep$extra, sleep$group)
mod2 <- effectsize::rank_biserial(c(48, 48, 77, 86, 85, 85), c(14, 34, 34, 77))

# contains attribute
get_ci_method(mod)
#> # A tibble: 1 x 2
#>   method distribution
#>   <chr>  <chr>       
#> 1 ncp    t
get_ci_method(mod2)
#> # A tibble: 1 x 2
#>   method    iterations
#>   <chr>          <dbl>
#> 1 bootstrap        200
```

But not consistently for others:

```r
# data
M <- rbind(
  c(150, 130, 35, 55),
  c(100, 50, 10, 40),
  c(165, 65, 2, 25)
)
dimnames(M) <- list(
  Study = c("Psych", "Econ", "Law"),
  Music = c("Pop", "Rock", "Jazz", "Classic")
)

Performance <- rbind(
  c(794, 86),
  c(150, 570)
)
dimnames(Performance) <- list(
  "1st Survey" = c("Approve", "Disapprove"),
  "2nd Survey" = c("Approve", "Disapprove")
)

# doesn't contain attribute
get_ci_method(phi(M))
#> # A tibble: 0 x 0
get_ci_method(cramers_v(M))
#> # A tibble: 0 x 0
get_ci_method(cohens_g(Performance))
#> # A tibble: 1 x 1
#>   method  
#>   <chr>   
#> 1 binomial
```

<sup>Created on 2021-05-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by mattansb** [comment]
Very weird - they should all have that!

I'll fix it (:

**Comment by mattansb** [comment]
Super weird - it was just for those two.

Anyway, fixed!

**Comment by mattansb** [comment]
Yeah, I just would like to close #316, #314 and maybe #279 first.

**Comment by IndrajeetPatil** [comment]
Sounds good!

**Comment by bwiernik** [comment]
Let's add this information to the print and report methods too!

**Comment by IndrajeetPatil** [comment]
Here is another context where this information is missing:

``` r
library(afex)
library(statsExpressions) # for data
library(effectsize)

# helper to extract relevant attributes
get_ci_method <- purrr::compose(tibble::as_tibble, purrr::attr_getter("ci_method"))

set.seed(123)
  
mod <- aov_ez("id", "value", iris_long, within = "condition")

# present
get_ci_method(effectsize::eta_squared(mod))
#> # A tibble: 1 x 2
#>   method distribution
#>   <chr>  <chr>       
#> 1 ncp    t

# absent
get_ci_method(effectsize::omega_squared(mod))
#> # A tibble: 0 x 0
```

<sup>Created on 2021-05-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by mattansb** [comment]
How do you catch these!

```R
library(afex)
#> Loading required package: lme4
#> Loading required package: Matrix
#> Registered S3 methods overwritten by 'car':
#>   method                          from
#>   influence.merMod                lme4
#>   cooks.distance.influence.merMod lme4
#>   dfbeta.influence.merMod         lme4
#>   dfbetas.influence.merMod        lme4
#> ************
#> Welcome to afex. For support visit: http://afex.singmann.science/
#> - Functions for ANOVAs: aov_car(), aov_ez(), and aov_4()
#> - Methods for calculating p-values with mixed(): 'KR', 'S', 'LRT', and 'PB'
#> - 'afex_aov' and 'mixed' objects can be passed to emmeans() for follow-up tests
#> - NEWS: library('emmeans') now needs to be called explicitly!
#> - Get and set global package options with: afex_options()
#> - Set orthogonal sum-to-zero contrasts globally: set_sum_contrasts()
#> - For example analyses see: browseVignettes("afex")
#> ************
#> 
#> Attaching package: 'afex'
#> The following object is masked from 'package:lme4':
#> 
#>     lmer
library(statsExpressions) # for data
library(effectsize)

# helper to extract relevant attributes
get_ci_method <- purrr::compose(tibble::as_tibble, purrr::attr_getter("ci_method"))

mod <- aov_ez("id", "value", iris_long, within = "condition")

# present
get_ci_method(effectsize::eta_squared(mod))
#> # A tibble: 1 x 2
#>   method distribution
#>   <chr>  <chr>       
#> 1 ncp    F

get_ci_method(effectsize::omega_squared(mod))
#> # A tibble: 1 x 2
#>   method distribution
#>   <chr>  <chr>       
#> 1 ncp    F
```

**Comment by bwiernik** [comment]
> Report - yes.
> 
> Printing - seems a bit too verbose? The methods are well documented in all of the functions docs...

This might be my personal pet peeve, but it matters a lot whether a CI is a pivot, normal approximation, profile likelihood, percentile bootstrap, BCa bootstrap, MCMC, test inversion, etc. Folks constantly treat these as interchangeable, and in my opinion it should be standard practice to report the method of confidence interval alongside its level when reporting results.

**Comment by mattansb** [comment]
> it should be standard practice to report the method of confidence interval alongside its level when reporting results.

I agree, but I'm not sure adding even more verbosity to our printing methods will help.
Hmm... 

Anyway,
How would you concisely display the 3 methods used in `effectsize`:
- Percentile bootstrap
- Normal approximations
- NCP (this is what you meant by "test inversion", right?)

**Comment by IndrajeetPatil** [comment]
Should we be more verbose in description of the method here? 

`ncp` is rather uninformative for someone who would like to know more about the method.

```r
get_ci_method(effectsize::eta_squared(mod))
#> # A tibble: 1 x 2
#>   method distribution
#>   <chr>  <chr>       
#> 1 ncp    F
```

> Percentile bootstrap

Currently, we mention only `bootstrap`, should we be more explicit here? 
(For example, this would avoid someone confusing these to be BCa CIs)

**Comment by bwiernik** [comment]
> ncp

I think this might be enough if the function documentation goes into tutorial details.

> bootstrap 

Yes, we should be clear there. May also want to add a boot_method argument to open possibility for BCa, studentized, basic, or ABC bootstrap CIs

**Comment by mattansb** [comment]
> I think this might be enough if the function documentation goes into tutorial details.

Agreed.

> Currently, we mention only bootstrap, should we be more explicit here?

Yes, I've changed it to "percentile bootstrap". I've also switched to using `boot::boot.ci`, so we can think how we might support other methods in the future.
