### ISSUE TITLE
LaTeX errors (again)

### ISSUE THREAD

**Issue by mattansb** [easystats/effectsize#337]
> LaTeX errors found:
! Package inputenc Error: Unicode char − (U+2212)
(inputenc)                not set up for use with LaTeX.

@strengejacke HELP!!!

https://win-builder.r-project.org/incoming_pretest/effectsize_0.4.5_20210525_093112/Windows/00check.log

**Comment by DominiqueMakowski** [comment]
need to replace somewhere the long dash for a short one I suppose, search all for "−"

**Comment by strengejacke** [comment]
done.

**Comment by mattansb** [comment]
Saint @strengejacke - how did you find it!?

**Comment by strengejacke** [comment]
1. Open `cmd.exe`
2. Enter

```
> set PATH=C:\Program Files\R\R-4.1.0\bin\x64;%PATH%
> R CMD Rd2pdf D:\mail\Documents\Coding\R\effectsize_0.4.4-2.tar.gz
```

3. A folder `.Rdpdf.....` is created, with log-files
4. Open generated `.tex` file in [TexWorks](http://www.tug.org/texworks/)
5. Compile tex-file.
6. Error line is explicitly mentioned, search that phrase in the package source.

**Comment by mattansb** [comment]
So... magic?

**Comment by IndrajeetPatil** [comment]
Yikes! There ought to be a better way to detect characters like these.

**Comment by strengejacke** [comment]
> Yikes! There ought to be a better way to detect characters like these.

It's not always characters. In this case, there probably would have been indeed an easier way...
