### ISSUE TITLE
remove `datawizard` functions 

### ISSUE THREAD

**Issue by mattansb** [easystats/effectsize#340]
https://github.com/easystats/datawizard/issues/3

- [x] adjust
- [x] change_scale
- [x] normalize
- [x] ranktransform (make sure to import!)
- [x] standardize (but not the default method! Make sure to import)
- [x] unstandardize

**Comment by mattansb** [comment]
@IndrajeetPatil Where does this stand?

Can I start removing these and add `remotes: easystats/datawizrd`?

**Comment by IndrajeetPatil** [comment]
I just need to work on the `README` a bit, and then we should be ready for submission.

Please don't remove them yet. Let's wait until `datawizard` is actually on CRAN.
