### ISSUE TITLE
Add `approximate` attr to outputs

### ISSUE THREAD

**Issue by mattansb** [easystats/effectsize#345]
See https://github.com/easystats/report/issues/184

### Set to FALSE unless passes to `effectsize.htest()`
- [x] effectsize.BFBayesFactor()
- [x] cohens_d() hedges_g() glass_delta()
- [x] phi() cohens_w() cramers_v() oddsratio() riskratio() cohens_h() cohens_g()
- [x] rank_biserial() cliffs_delta() rank_epsilon_squared() kendalls_w()

### Depends...
- [x] effectsize.htest() - depends on data recovery
- [x] eta_squared() omega_squared() epsilon_squared() cohens_f() cohens_f_squared() - depends on true SS use

@IndrajeetPatil The "From Test Statistics" functions (`F/z/t/chisq_to_*`) won't get this attribute, because there's no way to know where the input is from.
And the "Between Effect Sizes" function also wont get, because these function only return single numerics.
(Same for `standardize_parameters()` - I think it is meaningless there anyway).

How does that sound?

**Comment by IndrajeetPatil** [comment]
All of that sounds good to me! Thanks.

**Comment by mattansb** [comment]
Closing in favor of #348
