### ISSUE TITLE
adding `interpret_cramers_v()`?

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/effectsize#347]
I would also like to work soon on adding support for chi-squared tests in `report` package, and we will need interpretation guidelines for Cramer's _V_ before I can do that.

I have seen guidelines online (like the one in the link below), but I can't seem to find any references for these.
https://www.ibm.com/docs/en/cognos-analytics/11.1.0?topic=terms-cramrs-v

What do you think?

**Comment by DominiqueMakowski** [comment]
Here are some more:

- https://www.real-statistics.com/chi-square-and-f-distributions/effect-size-chi-square/
- https://peterstatistics.com/CrashCourse/3-TwoVarUnpair/NomNom/NomNom-2c-Effect-Size.html
- https://www.sigmaxl.com/Chi-Square-Nominal.shtml
- https://www.researchgate.net/publication/326885374_User%27s_guide_to_correlation_coefficients/figures?lo=1 (last table)

**Comment by mattansb** [comment]
Since Phi and V are equal to Pearson's r for a 2*2 xtab, I would suspect that it should have the same interpretation for the \*magnitude\* of association.

**Comment by IndrajeetPatil** [comment]
> Since Phi and V are equal to Pearson's r for a 2*2 xtab

But we should also pre-meditate and cover one-way tests and non-2*2-tests, no?

``` r
library(effectsize)

effectsize(chisq.test(mtcars$cyl))
#> Cramer's V |       95% CI
#> -------------------------
#> 0.05       | [0.00, 0.00]

effectsize(chisq.test(mtcars$am, mtcars$cyl))
#> Warning in chisq.test(mtcars$am, mtcars$cyl): Chi-squared approximation may be
#> incorrect
#> Cramer's V |       95% CI
#> -------------------------
#> 0.52       | [0.11, 0.85]
```

<sup>Created on 2021-06-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by mattansb** [comment]
It's the same measure in all those cases, I'm just pointing the equality in a specific case, so I _think_ V can be interpreted similarly in all cases (like Pearson's r).
(But not phi, which in cases other than 2*2 can be larger than 1).

@bwiernik have any insight here?

**Comment by bwiernik** [comment]
Oh, I wrote a reply this morning that I must not have sent. 

Yes, we can apply the same benchmarks for Cramer’s V and phi as for Pearson r. There is some nuance that distributions impact the maximum observable r (Oscar Olveira’s work here is great), and these are most noticeable for discrete variables. But these are fairly small concerns and as a first approximation, Pearson benchmarks are fine.

**Comment by mattansb** [comment]
👆

Do we even need a separate function? Will an alias do here?

**Comment by DominiqueMakowski** [comment]
I guess alias is fine, until some "specific" rules of thumb are published (if ever)
