### ISSUE TITLE
CI of Rank Biserial correlation

### ISSUE THREAD

**Issue by austincy** [easystats/effectsize#358]
Hello there,

I came across these codes while looking for the CI of Rank Biserial correlation. I found Willson (1976) (https://doi.org/10.1177/001316447603600207) was quite useful, but your codes seem different. I think the main point is for the following line:

confint <- tanh(rf + c(-1, 1) * qnorm(1 - alpha / 2) * rfSE)

Here rf is the transferred r_rbs using fisher's z transfer and rfSE is the SE of r_rbs. I think the equation (10) in Willson (1976) would be the correct one to use.

Best regards,

Austin

**Comment by bwiernik** [comment]
Yes, the current CIs for adjusted correlations are not correct: https://github.com/easystats/correlation/issues/181

This will hopefully be fixed in the near future. 

Closing as duplicate.

**Comment by mattansb** [comment]
Hi @austincy ,

Please note that eq 10 from Willson (1976) gives the shape of the sampling distribution under the null hypothesis, so it's probably no valid re-arrange it for constructing confidence intervals.

For correlations, there are many methods for obtaining confidence intervals, all should have similar(ish) coverage - here we've chosen Fisher's Z transformation.
