### ISSUE TITLE
When can `cohens_d()`/`effectsize()` compute Compute Cohen's d from a t-test

### ISSUE THREAD

**Issue by charlottetate77** [easystats/effectsize#359]
**Describe the bug**

The `cohens_d()` and `effectsize()` functions default to an h-test when the function is wrapped around the t.test() function input, but only for the two-sample _t_-test.

**To Reproduce**
Loading the mtcars data for a reproducible example:
```R
`data("mtcars")`
Running the two-sample t-test:
`t.test(mpg ~ vs, data = mtcars)`
#> Welch Two Sample t-test
#>
#>data:  mpg by vs
#>t = -4.6671, df = 22.716, p-value = 0.0001098
#>alternative hypothesis: true difference in means is not equal to 0
#>95 percent confidence interval:
#> -11.462508  -4.418445
#>sample estimates:
#>mean in group 0 mean in group 1 
#>               16.61667        24.55714 
```

**Expected behavior**

Running cohens_d() function to get expected answer:

```R
cohens_d(mpg ~ vs, data = mtcars)`
#> Cohen's d |         95% CI
#> --------------------------
#> -1.73     | [-2.55, -0.90]
#>
#> - Estimated using pooled SD.
```
But, now, using the cohens_d() function as a wrapper around the t.test() function input provides the unexpected behavior:

```R
cohens_d(t.test(mpg ~ vs, data = mtcars))
#> Cohen's d     |         95% CI
#> ----------------------
#> -1.96 | [-2.94, -0.95]
#> Warning message:
#> In effectsize.htest(x, type = "d", ci = ci, verbose = verbose) :
#> Unable to retrieve data from htest object. Using t_to_d() approximation.
```

But, the wrapper works for all one-sample and paired-samples forms:

## one sample:
`cohens_d(t.test(mtcars$mpg, mu = 25))` is the same as ``cohens_d(mtcars$mpg, mu = 25)``

## paired samples:
`cohens_d(t.test(mtcars$drat, mtcars$wt, paired = T))` is the same as `cohens_d(mtcars$drat, mtcars$wt, paired = T)`

**Specifiations (please complete the following information):**
 - `R` Version [version]: 3.6.1
 - `effectsize` Version [version]: 0.4.5.

**Comment by mattansb** [comment]
# The issue

This actually has nothing to do with one-/paired-/two-sample t-test,
instead is has to do with how the data is input to `t.test()`.

## Formula + data input

Generally speaking, when the input to `t.test()` is a `formula` + `data`,
it is impossible to recover the original data:

``` r
one <- t.test(wt ~ 1, data = mtcars)
paired <- t.test(Pair(wt, hp) ~ 1, data = mtcars)
two <- t.test(mpg ~ am, data = mtcars)

insight::get_data(one)
#> NULL
insight::get_data(paired)
#> NULL
insight::get_data(two)
#> NULL
```

(This is **not** a bug - it is simply a reflection of the limited information stored in `h.test` objects.)

In these cases a warning is given, and the `t_to_d()` approximation is used:

``` r
effectsize::cohens_d(one)
#> Warning in effectsize.htest(x, type = "d", ci = ci, verbose = verbose): Unable
#> to retrieve data from htest object. Using t_to_d() approximation.
#> d    |               95% CI
#> ---------------------------
#> 3.34 | [    2.44,     4.24]
effectsize::cohens_d(paired)
#> Warning in effectsize.htest(x, type = "d", ci = ci, verbose = verbose): Unable
#> to retrieve data from htest object. Using t_to_d() approximation.
#> d     |         95% CI
#> ----------------------
#> -2.15 | [-2.78, -1.50]
effectsize::cohens_d(two)
#> Warning in effectsize.htest(x, type = "d", ci = ci, verbose = verbose): Unable
#> to retrieve data from htest object. Using t_to_d() approximation.
#> d     |         95% CI
#> ----------------------
#> -1.76 | [-2.82, -0.67]
```

## Vector input

When the input to `t.test()` is a vactor,
there is no problem recovering the original data:

``` r
# (same t.tests)
one <- t.test(mtcars$wt)
paired <- t.test(mtcars$wt, mtcars$hp, paired = TRUE)
two <- t.test(mtcars$mpg[mtcars$am==0], mtcars$mpg[mtcars$am==1])

insight::get_data(one)    |> head(2)
#>      wt
#> 1 2.620
#> 2 2.875
insight::get_data(paired) |> head(2)
#>      wt  hp
#> 1 2.620 110
#> 2 2.875 110
insight::get_data(two)    |> head(2) # ignore the ugly column names
#>   am == 0] am == 1]
#> 1     21.4       21
#> 2     18.7       21
```

In these cases a direct and exact estimated is used:

``` r
effectsize::cohens_d(one)
#> Cohen's d |               95% CI
#> --------------------------------
#> 3.29      | [    2.44,     4.24]
effectsize::cohens_d(paired)
#> Cohen's d |         95% CI
#> --------------------------
#> -2.11     | [-2.78, -1.50]
effectsize::cohens_d(two)
#> Cohen's d |         95% CI
#> --------------------------
#> -1.41     | [-2.26, -0.53]
#> 
#> - Estimated using un-pooled SD.
```

<sup>Created on 2021-06-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

---

This is true for all h.test objects (results from functions from the `stat` package that end in `*.test()`).

---

# Solution(s)

1. Either use vector notation only in your t-test, then pass to `cohens_d()`/`effectsize()`
2. Pass the arguments directly (not the t-test) to `cohens_d()`.

**Comment by IndrajeetPatil** [comment]
@mattansb I think it might be a good idea to write FAQ vignette and add these details there. I do this for [`ggstatsplot`](https://indrajeetpatil.github.io/ggstatsplot/articles/web_only/faq.html).

This will not be the last time someone will ask this question, and you won't have to invest time in responding with a new answer each time. You can then just direct to FAQ-xx link.

**Comment by bwiernik** [comment]
Perhaps even a message in the function when formula notation is used?

**Comment by bwiernik** [comment]
Could you put together a reprex showing the difference in returns from formula versus vector inputs? I can post to the R core listserv and maybe they might consider making them more consistent?

**Comment by mattansb** [comment]
> @mattansb I think it might be a good idea to write FAQ vignette and add these details there. 

I was thinking of just pointing people to here from now on (: That's why I wrote out such a detailed comment.

> Could you put together a reprex showing the difference in returns from formula versus vector inputs? I can post to the R core listserv and maybe they might consider making them more consistent?

It's actually not formula vs vector, it's formula + data vs vector 🤦‍♂️
## Formula + data input

``` r
oneFD <- t.test(wt ~ 1, data = mtcars)
pairedFD <- t.test(Pair(wt, hp) ~ 1, data = mtcars)
twoFD <- t.test(mpg ~ am, data = mtcars)

# The captured name of the `data` arg is actually missing from `data.name`
oneFD$data.name 
#> [1] "wt"
pairedFD$data.name 
#> [1] "Pair(wt, hp)"
twoFD$data.name 
#> [1] "mpg by am"
```

## Vector input

``` r
# (same t.tests)
oneV <- t.test(mtcars$wt)
pairedV <- t.test(mtcars$wt, mtcars$hp, paired = TRUE)
twoV <- t.test(mtcars$mpg[mtcars$am==0], mtcars$mpg[mtcars$am==1])

# `data.name` has all the info required for data recovery
oneV$data.name
#> [1] "mtcars$wt"
pairedV$data.name
#> [1] "mtcars$wt and mtcars$hp"
twoV$data.name
#> [1] "mtcars$mpg[mtcars$am == 0] and mtcars$mpg[mtcars$am == 1]"
```

## Explicit formula input

``` r
# (same t.tests)
oneF <- t.test(mtcars$wt ~ 1)
pairedF <- t.test(Pair(mtcars$wt, mtcars$hp) ~ 1)
twoF <- t.test(mtcars$mpg ~ mtcars$am)

# `data.name` has all the info required for data recovery
oneF$data.name
#> [1] "mtcars$wt"
pairedF$data.name
#> [1] "Pair(mtcars$wt, mtcars$hp)"
twoF$data.name
#> [1] "mtcars$mpg by mtcars$am"
```

<sup>Created on 2021-07-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by DominiqueMakowski** [comment]
It's true that a vignette could useful, perhaps a more general one like "how to correctly run basic tests in R", and talk about base h-tests, anovas, how to specify them at best, and what alternative packages to use

**Comment by bwiernik** [comment]
@mattansb How does that contrast to the `lm` case with formula+data?

**Comment by mattansb** [comment]
In 2 ways:

1. `lm` has a `$model` element that actually holds the model frame.
2. `lm` has a `$call` element that can also be used to recover the data.

**Comment by bwiernik** [comment]
Okay. That's really helpful. It seems like htest could be augmented with those elements without any backwards incompatibility issues. Could you give a code example of using those in lm for effectsize?

**Comment by IndrajeetPatil** [comment]
> I was thinking of just pointing people to here from now on (: That's why I wrote out such a detailed comment.

@mattansb But users are much more likely to come across an article on the website over a GitHub issue. If they do try to raise an issue, GitHub even automatically suggests similar prior issues. So it's good that you wrote a detailed answer here, but I feel like it's worth copy-pasting to a dedicated FAQ vignette. My 2 cents.

**Comment by mattansb** [comment]
> It seems like htest could be augmented with those elements without any backwards incompatibility issues.

Yes!

> Could you give a code example of using those in lm for effectsize?

Not sure I understand?
