### ISSUE TITLE
Variance estimation in effectsize

### ISSUE THREAD

**Issue by TabeaSchoeler** [easystats/effectsize#36]
Dear all,

I have used  the function ’t_to_d()’ to estimate d from a t-test value, based on a repeated-measures design.

Just wondering if there are ways to also estimate the corresponding variance of d with your package?

I am currently using the following formula:
  d= t / sqrt(df) 
  var.d=(2*(1-r)/n)+(d/(2*n-2))
  l.d=d-1.96 * sqrt(var.d)
  u.d=d+1.96 * sqrt(var.d)
  se.d = (u.d-l.d)/(2*1.96) # calculate the standard error
  z.d = d/se.d
  pval.d=2*pnorm(-abs(z.d))

Best wishes,
Tabea

**Comment by mattansb** [comment]
What do you mean by variance of d? The standard error of the estimate?

**Comment by TabeaSchoeler** [comment]
Yes, standard error would be ideal, then can estimate the confidence intervals for d

**Comment by mattansb** [comment]
There is no implementation of this here (yet).
Care to share where your method is from?

**Comment by TabeaSchoeler** [comment]
Ok, thanks!
I gathered the formula from a number of papers:
- Cohen's d Statistic, DOI: https://dx.doi.org/10.4135/9781412961288.n58
- A review of effect sizes and their confidence intervals, Part I: The Cohen's d family, DOI: 10.20982/tqmp.14.4.p242

**Comment by mattansb** [comment]
Added NCP methods for `t/z/F_to*` functions.

E.g.,
``` r
library(effectsize)

res <- t.test(extra ~ group, sleep)

t_to_d(res$statistic, res$parameter)
#>            d   CI    CI_low   CI_high
#> t -0.8826937 0.95 -1.844756 0.1018923
```

<sup>Created on 2020-03-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
