### ISSUE TITLE
Error when calling `effectsize()` over an "lm" object that was created in a custom wrapper function

### ISSUE THREAD

**Issue by emmansh** [easystats/effectsize#364]
**Describe the bug**
Calling `effectsize()` over an object of class `"lm"` results in error, when the model object was created in the following manner:
1. when `lm()` is wrapped inside a user-defined function; **and**
2. when `lm()`'s `formula` argument is fed with a `as.formula` object rather than specifying the formula within `lm()`.

**To Reproduce**
``` r
library(dplyr, warn.conflicts = FALSE)
library(effectsize)

my_lm_external_formula <- function(.dat, predicted, predictor){
  
  my_formula <- as.formula(paste0(predicted, "~", predictor))
  
  lm(formula = my_formula, data = .dat)
}
## the following line fails
my_lm_external_formula(.dat = mtcars, predicted = "mpg", predictor =  "am") %>% effectsize()
#> Error in stats::model.frame(formula = my_formula, data = data_std, drop.unused.levels = TRUE): object 'my_formula' not found
```

<sup>Created on 2021-08-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Expected behavior**
If I had defined the custom function differently, it would have given the correct output, such as:
``` r
library(dplyr, warn.conflicts = FALSE)
library(effectsize)

my_lm_built_in_formula_via_pipe <- function(.dat, predicted, predictor){
  
  .dat %>%
    select(my_predicted = {{ predicted }}, my_predictor = {{ predictor }}) %>%
    lm(my_predicted ~ my_predictor, data = .)
}

my_lm_built_in_formula_via_pipe(.dat = mtcars, predicted = "mpg", predictor = "am") %>% effectsize()
#> # Standardization method: refit
#> 
#> Parameter    | Coefficient (std.) |        95% CI
#> -------------------------------------------------
#> (Intercept)  |           2.94e-17 | [-0.29, 0.29]
#> my_predictor |               0.60 | [ 0.30, 0.90]
```

<sup>Created on 2021-08-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Why not simply go with the second method (i.e., `my_lm_built_in_formula_via_pipe()`)**
The necessity to build a custom function arises when I have a long formula to pass to `lm()` when fiting a multiple regression. For example, with many, somewhat repetitive, interaction terms. In such cases, I might want to use some string processing to build the formula, rather than explicitly typing it into `lm()`.  See [this StackOverflow](https://stackoverflow.com/questions/52168127/how-to-select-which-columns-to-use-in-a-regression) post for a similar issue.

**I have posted a question on StackOverflow about this specific issue and was given a solution**
See [here ](https://stackoverflow.com/questions/68792225/why-am-i-getting-an-error-about-statsmodel-frame-when-passing-an-lm-model) for my question, and see also the answer given by the user StupidWolf. 

**Specifiations (please complete the following information):**
 - `R` Version 
   - `4.1.0` 
 - `effectsize` Version
   - `0.4.5`

**Comment by mattansb** [comment]
This isn't a bug in `effectsize`, but an issue on R overall.

``` r
my_lm_external_formula <- function(.dat, predicted, predictor){
  
  my_formula <- as.formula(paste0(predicted, "~", predictor))
  
  lm(formula = my_formula, data = .dat)
}


m <- my_lm_external_formula(.dat = mtcars, predicted = "mpg", predictor =  "am")


# Can't update data
std_data <- insight::get_data(m) |> datawizard::standardize()
stats::update(m, data = std_data)
#> Error in stats::model.frame(formula = my_formula, data = std_data, drop.unused.levels = TRUE): object 'my_formula' not found

# Can't update formula
stats::update(m, formula = mpg ~ 1)
#> Error in is.data.frame(data): object '.dat' not found
```

However, you can use other methods of standardization that don’t refit the model:

``` r
effectsize::standardize_parameters(m, method = "basic")
#> # Standardization method: basic
#> 
#> Parameter   | Coefficient (std.) |       95% CI
#> -----------------------------------------------
#> (Intercept) |               0.00 | [0.00, 0.00]
#> am          |               0.60 | [0.30, 0.90]
```

<sup>Created on 2021-08-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by bwiernik** [comment]
The issue here is that what is stored in the lm object’s ‘call’ slot is the object name ‘’my_formula”, which only exists in the internal scope of the wrapper function. 

You can fix this by fixing that within your wrapper function. 

```r

my_lm_external_formula <- function(.dat, predicted, predictor){
  
  my_formula <- as.formula(paste0(predicted, "~", predictor))
  
  mod <- lm(formula = my_formula, data = .dat)
  mod$call$formula <- my_formula
  return(mod)
}
```

**Comment by bwiernik** [comment]
``` r
my_lm_external_formula <- function(.dat, predicted, predictor) {
  my_formula <- as.formula(paste(predicted, "~", paste(predictor, collapse = " + ")))
  my_model <- lm(my_formula, data = .dat)
  my_model$call$formula <- my_formula
  return(my_model)
}

m1 <- my_lm_external_formula(mtcars, "mpg", c("hp", "disp"))
effectsize::standardize(m1)
#> 
#> Call:
#> lm(formula = mpg ~ hp + disp, data = data_std)
#> 
#> Coefficients:
#> (Intercept)           hp         disp  
#>  -6.623e-17   -2.826e-01   -6.240e-01
```

<sup>Created on 2021-08-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by bwiernik** [comment]
@mattansb We could make `standardize()` work even when a model's `call$formula` slot is messy like this by using `tryCatch()`:

Something ala:

```r
tryCatch(update(m1, data = mtcars[1:6,]), error = function(e) {
    m1$call$formula <- formula(terms(m1))
    return(update(m1, data = mtcars[1:6,]))
})
```

**Comment by mattansb** [comment]
Why do we need `terms()`? Can't we just `formula(m1)`?

**Comment by bwiernik** [comment]
Oh I guess that would work too

**Comment by mattansb** [comment]
The fix suggested by Brenton would have too many exceptions.
Instead, I've opted to fail with an informative error:

``` r
my_lm_external_formula <- function(.dat, predicted, predictor){
  
  my_formula <- as.formula(paste0(predicted, "~", predictor))
  
  lm(formula = my_formula, data = .dat)
}


m <- my_lm_external_formula(mtcars, "mpg", "am")

library(effectsize)
standardize_parameters(m, method = "refit")
#> Error: Unable to refit the model with standardized data.
#> Failed with the following error:
#> "Error in stats::model.frame(formula = my_formula, data = data_std, drop.unused.levels = TRUE): object 'my_formula' not found
#> "
#> 
#> Try instead to standardize the data (standardize(data)) and refit the model manually.

## There will give the same error:
# standardize(m)
# effectsize(m)
```

<sup>Created on 2021-08-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
