### ISSUE TITLE
default to 95% confidence interval for effect size conversion functions?

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/effectsize#365]
Both in `{bayestestR}` and `{parameters}`, we have changed function argument defaults to `ci = 0.95`, but a number of test-statistic-to-effect-size conversion functions still default to `ci = 0.90`:

https://easystats.github.io/effectsize/reference/F_to_eta2.html

<img width="868" alt="Screenshot 2021-08-16 at 09 33 20" src="https://user-images.githubusercontent.com/11330453/129527489-c84b610f-fd3b-4ea1-a23e-8671660880ee.png">

Both for within-package consistency (because all other functions have `ci = 0.95`) and between-package consistency, this change will be worth it.

**Comment by mattansb** [comment]
(I received this same comment just last week in a review 🙃)

For an alpha of 5%, CIs for one sided test statistics (F, Chi^2) should be at a 90% level.
This ensures that the CI and the NHST are complimentary to one another.

See Steiger (2004) *Beyond the F test*, the section titled *The Relationship Between Confidence Intervals and
Hypothesis Tests—Choosing the Appropriate Interval*:

![image](https://user-images.githubusercontent.com/35330040/129536657-84df9c34-e71c-485a-b4b8-7bff069ad0b7.png)

**Comment by mattansb** [comment]
What I'm saying is that this actually *is* consistent (:

**Comment by IndrajeetPatil** [comment]
Thanks for the detailed explanation! Makes sense.

Do you think it might be worth it to add this explanation to the documentation (either manual or vignette) itself? 
If two people have wondered about this in a couple of weeks, maybe there are many more who just didn't raise an issue?

> For an alpha of 5%, CIs for one sided test statistics (F, Chi^2) should be at a 90% level.

I see, but then why `ci = 0.95` is the default for Chi^2 conversion functions?
https://easystats.github.io/effectsize/reference/chisq_to_phi.html

<img width="1196" alt="Screenshot 2021-08-16 at 10 57 49" src="https://user-images.githubusercontent.com/11330453/129538199-b03374ac-405b-424d-8e95-609037bb48f4.png">

**Comment by mattansb** [comment]
> Do you think it might be worth it to add this explanation to the documentation (either manual or vignette) itself?

Yup! Will do.

> I see, but then why ci = 0.95 is the default for Chi^2 conversion functions?

Oops... Now *that's* a consistency issue!

Will address both.

**Comment by bwiernik** [comment]
The alternative would be a 95% one-tailed test. 

Either way, I think a message here explaining this for users would be good in the print output

**Comment by mattansb** [comment]
> The alternative would be a 95% one-tailed test.

I'm sure users will loooooove `95% CI [0.04, Inf]` :(

> I think a message here explaining this for users would be good in the print output

I think in the help page is enough ^_^

**Comment by bwiernik** [comment]
It is the CI that corresponds to their hypothesis test 😜

**Comment by bwiernik** [comment]
In terms of things that would be surprising to users, I think getting one bound with a 1-tailed CI is less alarming than a discrepancy in `ci` defaults or the sort of significance-mismatch you note if they change `ci` to .95.

**Comment by mattansb** [comment]
I think most people, even if they don't know how CI and NHST are related know that "if 0 is not in CI, it's significant", so they will be surprised by a discrepancy.
And no one is saying that a 90% CI has 95% coverage. I will add a note to the docs on that also.

**Comment by bwiernik** [comment]
I think it's similarly confusing to have a different alpha rate than usual as default and in the table header. I suspect a fair number of users change it to .95, potentially making opening that door for confusion. Or, if they leave it .90, they run the risk of reviewer pushback like you got. I can imagine this being a source of "QRP questionable research practice" accusations by a reviewer if they didn't understand the nuance here.

**Comment by bwiernik** [comment]
If we want to ensure the CI and test are consistent, I think the safest way to do that is to make the construction consistent by matching the number of tails.
