### ISSUE TITLE
Interpretation of Cohen's g

### ISSUE THREAD

**Issue by ddauber** [easystats/effectsize#376]
**Describe the bug**
I am quite certain that the function `interpret_g()` is not referring to the right benchmarks if it is meant to interpreted Cohen's g. The correct benchmarks are found in Cohen (1988, pp. 147). Instead, the limits for Cohen's d seem to be applied.

Below I provide examples for the correct benchmarks (as a comment) against what `interpret_g()` produces.

Maybe I misunderstood the function, but my expectation was that it interprets Cohen's g (as outlined on the website). happy to elaborate.

**To Reproduce**
``` r
library(effectsize)

# Negligible g < 0.05
interpret_g(0.04)
#> [1] "very small"
#> (Rules: cohen1988)
# Small 0.05 <= g < 0.15
interpret_g(0.10)
#> [1] "very small"
#> (Rules: cohen1988)
# Medium 0.15 <= g < 0.25
interpret_g(0.20)
#> [1] "small"
#> (Rules: cohen1988)
# Large g >= 0.25 
interpret_g(0.30)
#> [1] "small"
#> (Rules: cohen1988)
```

**Specifiations (please complete the following information):**
 - `R` Version [4.1.0]
 - `effectsize` Version [0.4.5]

**Comment by mattansb** [comment]
Thanks @ddauber !
The intention was to interpret Hedges' g, but as you point out the name is too ambiguous...

Need to:
1. Make the function names more explicit
2. Add a function for interpreting Cohen's g

Thanks for bringing this to our attention!

**Comment by bwiernik** [comment]
What is Cohen's g?

**Comment by ddauber** [comment]
Thanks for the swift reply, @mattansb.

I was wondering whether it is supposed to be Hedges g. That clarifies it.

@bwiernik
Cohen's g provides the effect size for proportion tests where the null hypothesis assumes that the proportion is 50% (i.e. _P = 0.5_). Thus, it tests the proportions in a 2x2 matrix.  I hope that makes sense. If not, I recommend taking a look at Cohen (1988) 😉

**Comment by bwiernik** [comment]
Yeah, that makes sense. Always hard to remember which random letters Cohen picked for his various indices 😜

**Comment by mattansb** [comment]
``` r
library(effectsize)

interpret_g(0.2)
#> Warning: 'interpret_g' is deprecated.
#> Use 'interpret_hedges_g' instead.
#> See help("Deprecated")
#> [1] "small"
#> (Rules: cohen1988)

interpret_hedges_g(0.2)
#> [1] "small"
#> (Rules: cohen1988)

interpret_cohens_g(0.2)
#> [1] "large"
#> (Rules: cohen1988)
```

<sup>Created on 2021-09-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by ddauber** [comment]
That was ultra-fast. Thanks. I guess it will be a lot easier for my students to interpret that effect size in the coming academic year. 

Hugely appreciate your packages. Makes teaching R to my students so much easier. 😉

**Comment by mattansb** [comment]
😊

**Comment by ddauber** [comment]
PS: Is 0.2 not medium and 0.25 large? 🤔

**Comment by mattansb** [comment]
Och, damnit... :/ Good eye!

Fixed? 

``` r
interp <- effectsize::interpret_cohens_g(g <- seq(0, 0.5, by = 0.05))

data.frame(g, interp)
#>       g     interp
#> 1  0.00 very small
#> 2  0.05      small
#> 3  0.10      small
#> 4  0.15     medium
#> 5  0.20     medium
#> 6  0.25      large
#> 7  0.30      large
#> 8  0.35      large
#> 9  0.40      large
#> 10 0.45      large
#> 11 0.50      large
```

<sup>Created on 2021-09-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by ddauber** [comment]
That looks right. Thanks. 😉
