### ISSUE TITLE
Phi for goodness of fit with non-uniform expected frequencies 

### ISSUE THREAD

**Issue by mattansb** [easystats/effectsize#379]
Phi for goodness-of-fit gives off results when expected frequencies are non uniform.

Here is the simplest example:

``` r
library(effectsize)

(tab1D <- table(mtcars$am))
#> 
#>  0  1 
#> 19 13

phi(tab1D, p = c(0.001, 0.999))
#> Phi   |        95% CI
#> ---------------------
#> 18.75 | [16.46, 1.00]
#> 
#> - One-sided CIs: upper bound fixed at (1).
```

<sup>Created on 2021-09-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Questions:

1. Is this the correct estimate (still baes on `chi/N`)
2. Is there a way to know the upper bound in such a case?
(For uniform expected values the max is `sqrt(k-1)`:

``` r
cbind(0, 0, 0, 0, 100) |>
  effectsize::phi()
#> Phi  |       95% CI
#> -------------------
#> 2.00 | [1.83, 2.00]
#> 
#> - One-sided CIs: upper bound fixed at (2).
```

<sup>Created on 2021-09-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

@bwiernik @IndrajeetPatil @strengejacke ?

**Comment by bwiernik** [comment]
phi is an index of bivariate correlation. It should only be computed for 2x2 tables. For larger bivariate tables, Cramer's V is a generalization.

**Comment by mattansb** [comment]
But in such cases, V can be outside [0,1] as it is `chi / (N * (k-1))`:

``` r
library(effectsize)

tab1D <- table(mtcars$am)

cramers_v(tab1D, p = c(0.001, 0.999))
#> Cramer's V |        95% CI
#> --------------------------
#> 18.75      | [16.46, 1.00]
#> 
#> - One-sided CIs: upper bound fixed at (1).
```

<sup>Created on 2021-09-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

It seems that the max for V is: 

sqrt(odds(max([P<sub>exp</sub>, 1-P<sub>exp</sub>]))/(k-1))

**Comment by bwiernik** [comment]
You can't compute phi/V with one dimension. They are only applicable with 2-dimensional tables.

**Comment by bwiernik** [comment]
The Rand index would be a similar sort of coefficient applicable for a 1-dimensional table.

**Comment by bwiernik** [comment]
phi/V functions should error when they are given a table with more or fewer than 2 dimensions

**Comment by mattansb** [comment]
Just consolted with a statiastician on a (closed) forum; he says:
- Phi is ok for goodness of fit
- V is not

He also suggested using *Pearson's contingency coefficient*
![image](https://user-images.githubusercontent.com/35330040/134966497-766b26bd-c769-4e4d-830b-3be5756e5c7c.png)

Any parametric method for getting CIs for the Rand index?

**Comment by mattansb** [comment]
In #381
