### ISSUE TITLE
CI for all effect sizes

### ISSUE THREAD

**Issue by mattansb** [easystats/effectsize#38]
With bootstrap?

To do:
- Effect size for ANOVA
  - [x] `cohens_f()`
  - [x] `eta_squared()`
  - [x] `eta_squared(partial = TRUE)`
  - [x] `omega_squared()`
  - [x] `omega_squared(partial = TRUE)`
  - [x] `epsilon_squared()` / `eta_squared_adj()`
  - [x] `epsilon_squared(partial = TRUE)` / `eta_squared_adj(partial = TRUE)`
  - [x] ***UPDATE DOCS:*** Some of these use bootstrapping, and some use the `F_to_*()` functions.
- Effect size for differences
  - [x] `cohens_d()`
  - [x] `glass_delta()`
  - [x] `hedges_g()`
- Effect size for contingency tables
  - [x] `phi()`
  - [x] `cramers_v()`
- Effect size for regression (Parameters standardization)
  - [x] `parameters::model_parameters()` has CIs

**Comment by mattansb** [comment]
@DominiqueMakowski now that JOSS is not happening... ^_^

**Comment by DominiqueMakowski** [comment]
But I also need this thing called "inspiration" which hits at random intervals for random things ^^ 
I'll try to find it for this issue tho ☺️

**Comment by mattansb** [comment]
I've started working on the anova ESs (making the code across Omega, Eta and Epsilon more concise).

**Comment by strengejacke** [comment]
I have lost the overview of mentions here in the ES package... can you ping me again if I can help somewhere?

**Comment by DominiqueMakowski** [comment]
> I've started working on the anova ESs (making the code across Omega, Eta and Epsilon more concise).

Nice! aiming at having the best-maintained package I see? 😁 

On a side note, I think that the next big thing, the MVP will be Bayesian effect sizes (or how to compute standardized effect sizes for complex models without proper test parameters - that could hence be applied for both frameworks), that's the field we have to invest where's there is currently a big gap

**Comment by mattansb** [comment]
@strengejacke will do 😁

@DominiqueMakowski #8 is still open...

**Comment by IndrajeetPatil** [comment]
For Cohen's _d_ and Hedge's _g_ measures, are we also planning to add support for non-central  *t*-distributions for computing the confidence intervals?

In case this is of any help, there is implementation of this in `statsExpressions` package:
https://github.com/IndrajeetPatil/statsExpressions/blob/1bbbda6a5f11d7b9b92503e66990389521d741fc/R/helpers_effsize_ci.R#L97-L287

I can then rely on `effectsize` in my package :D

**Comment by mattansb** [comment]
We have the non-central method implemented in `t_to_d()`. I can just `cbind()` is to output...
@IndrajeetPatil what do you think?

**Comment by IndrajeetPatil** [comment]
I think that would work. Is it possible to see what the output might look like? 

From looking at the website examples, I was under the impression that we currently don't support the CIs for Cohen's _d_ but Hedge's _g_: https://easystats.github.io/effectsize/reference/cohens_d.html#examples

That's why I raised this issue. Glad to know that it's already implemented!

**Comment by mattansb** [comment]
We don't directly, but do under the test statistic conversion functions (:

**Comment by mattansb** [comment]
Okay, that was a bit harder than I thought, but I thing I got it!

``` r
library(effectsize)

cohens_d(len ~ supp, data = ToothGrowth)
#>     Cohens_d   CI    CI_low    CI_high
#> 1 -0.4945201 0.95 -1.023626 0.02187782
effsize::cohen.d(len ~ supp, ToothGrowth, hedges.correction = FALSE)
#> 
#> Cohen's d
#> 
#> d estimate: 0.4945201 (small)
#> 95 percent confidence interval:
#>       lower       upper 
#> -0.03016123  1.01920151

hedges_g(len ~ supp, data = ToothGrowth)
#>     Hedges_g   CI    CI_low   CI_high
#> 1 -0.4880978 0.95 -1.010332 0.0215937
effsize::cohen.d(len ~ supp, ToothGrowth, hedges.correction = TRUE)
#> 
#> Hedges's g
#> 
#> g estimate: 0.4880978 (small)
#> 95 percent confidence interval:
#>       lower       upper 
#> -0.02957129  1.00576689

glass_delta(len ~ supp, data = ToothGrowth)
#>   Glass_delta   CI     CI_low     CI_high
#> 1  -0.4476152 0.95 -0.8339054 -0.06951978
```
