### ISSUE TITLE
Unable to find interpret_rank_biserial

### ISSUE THREAD

**Issue by alxndrdiaz** [easystats/effectsize#382]
Hello. After computing a rank biserial corrrelation using the function _rank_biserial()_ I am unable to find the function _interpret_rank_biserial()_ described in the [documentation](https://easystats.github.io/effectsize/reference/interpret_r.html) using the code shown below. Is it possible to use _interpret_r()_ function instead?, I am using effectsize version 0.4.5.

`library(effectsize) ;
packageVersion("effectsize")`
`[1] ‘0.4.5’`
`?interpret_rank_biserial`
`No documentation for ‘interpret_rank_biserial’ in specified packages and libraries:
you could try ‘??interpret_rank_biserial’`

**Comment by mattansb** [comment]
@alxndrdiaz This function is available only in the development version of `effectsize`.

You can install the dev version by
```R
install.packages("effectsize", repos = "https://easystats.r-universe.dev")
```
