### ISSUE TITLE
standardize_parameters() and offset - does it work?

### ISSUE THREAD

**Issue by fboetzl** [easystats/effectsize#396]
**Question and context**
Hi, I am modelling data that unfortunately (partly) differ in sampling effort. To compare between coefficients, I want to standardize them. 

If I run models using weights, everything seems to work (sampling effort log transformed as poisson family also involves log transformation):

```
M_1 <- glmmTMB(y~ x + (1|site), family= poisson, zi =~ 0, weights=log_sampling_effort, data=data)
standardize_parameters(M_1)

# Parameter                 | Coefficient (std.) |        95% CI
# ---------------------------------------------------------
# (Intercept)               |               2.18 | [ 2.02, 2.34]
# x_B                       |          -1.95e-03 | [-0.13, 0.13]
```

However, as far as I understand, what I really want for my problem is an offset on sampling effort (as far as I understand, weights are more a measure of preciseness or accuracy, while offsets are representing elemental design limitations). The same model with offset, however, produces an error in strandardize_parameters:

```
M_2 <- glmmTMB(y~ x + (1|site), family= poisson, zi =~ 0, offset=log_sampling_effort, data=data)
standardize_parameters(M_2)

# Error: Unable to refit the model with standardized data.
# Failed with the following error:
# "Error in eval(offsub, data, enclos = environment(formula)): object 'log_sampling_effort' not found"

# Try instead to standardize the data (standardize(data)) and refit the model manually.

```
Are offsets not implemented in standardize_parameters? I did not find anything related to this in the manual. 

(Just to add, of course another solution to my problem would be adding sampling effort as a fixed effect to my models ('M_3 <- glmmTMB(y~ x + log_sampling_effort + (1|site), family= poisson, zi =~ 0, data=data)' - this, however, seems much less elegant to me).

Please forgive me for mistakes, I am very new to github. Many thanks for your help!

**Comment by mattansb** [comment]
There are two issues here:

## 1. The model is failing to refit 
.... with standardized data (due to https://github.com/easystats/insight/issues/472 and the fact that `glmmTMB` doesn't like vectors with attributes). This can be resolved by fitting the model manually with the standardized data:

``` r
library(glmmTMB)
library(parameters)
library(effectsize)

m <- glmmTMB(mpg ~ hp, offset = cyl, data = mtcars)
model_parameters(m)
#> # Fixed Effects
#> 
#> Parameter   | Coefficient |   SE |         95% CI |     z |      p
#> ------------------------------------------------------------------
#> (Intercept) |       27.09 | 1.86 | [23.46, 30.73] | 14.60 | < .001
#> hp          |       -0.09 | 0.01 | [-0.11, -0.07] | -7.83 | < .001
#> 
#> # Random Effects
#> 
#> Parameter     | Coefficient |       95% CI
#> ------------------------------------------
#> SD (Residual) |        4.39 | [3.43, 5.60]

standardize_parameters(m, method = "refit") # error:
#> Error: Unable to refit the model with standardized data.
#> Failed with the following error:
#> "Error in eval(offsub, data, enclos = environment(formula)): object 'cyl' not found
#> "
#> 
#> Try instead to standardize the data (standardize(data)) and refit the model manually.

mtcars_z <- standardize(mtcars) # standardize
mtcars_z <- lapply(mtcars_z, c) |> as.data.frame() # strip attributes

m_z <- glmmTMB(mpg ~ hp, offset = cyl, data = mtcars_z)
model_parameters(m_z)
#> # Fixed Effects
#> 
#> Parameter   | Coefficient |   SE |         95% CI |        z |      p
#> ---------------------------------------------------------------------
#> (Intercept) |    3.59e-08 | 0.18 | [-0.36,  0.36] | 1.95e-07 | > .999
#> hp          |       -1.61 | 0.19 | [-1.97, -1.24] |    -8.61 | < .001
#> 
#> # Random Effects
#> 
#> Parameter     | Coefficient |       95% CI
#> ------------------------------------------
#> SD (Residual) |        1.04 | [0.81, 1.33]
```

<sup>Created on 2021-11-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

However these is a bigger issue here:

##  2.  How to standardize offset variables?

Since the coefficient of the offset variable is fixed at 1, it don't really make sense to standardize the offset variable *or* the response variable, so as to keep the "1" unit coefficient valid.

I am currently inclined to have an error if an offset is detected and `standardize(include_response = TRUE)`.

@strengejacke @bwiernik Any thoughts?

----

In the mean time, if possible, I suggest using the post-hoc methods of coefficient standardization:

``` r
standardize_parameters(m, method = "basic")
#> # Standardization method: basic
#> 
#> Parameter   | Coefficient (std.) |         95% CI
#> -------------------------------------------------
#> (Intercept) |               0.00 | [ 0.00,  0.00]
#> hp          |              -1.02 | [-1.28, -0.77]
```

<sup>Created on 2021-11-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by strengejacke** [comment]
But wouldn't fix `offset` the coefficient to 1, no matter on which scale the offset variable is?

**Comment by bwiernik** [comment]
I think we add an `include_offset` option alongside `include_response`. 

In most cases where an offset is used, like in Poisson models, I don't really see a context where you would want to standardize the response. 

I think the solution here might be to do 2 things:
1. Add `include_offset`
2. Only default to `include_response = TRUE` for normal (and maybe lognormal?) models, not binomial or count models, etc

**Comment by mattansb** [comment]
> Only default to `include_response = TRUE` for normal (and maybe lognormal?) models, not binomial or count models, etc

This is already the case 👍

What would `include_offset` default to? 
I can't think of any example where standardizing the offset variables makes sense...

**Comment by mattansb** [comment]
@strengejacke if we have `y ~ offset(z) + x` and you then standardize `z`, you are changing the scale of `z` but not the coefficient (fixed at 1) and so the nature of the relationship between `y ~ x` is also affected.

<details>
<summary><i>Example</i></summary>

``` r
library(parameters)
library(effectsize)

# Tests are unaffected by scalling:
m <- lm(mpg ~ cyl + hp, data = mtcars)

m |> model_parameters()
#> Parameter   | Coefficient |   SE |         95% CI | t(29) |      p
#> ------------------------------------------------------------------
#> (Intercept) |       36.91 | 2.19 | [32.43, 41.39] | 16.85 | < .001
#> cyl         |       -2.26 | 0.58 | [-3.44, -1.09] | -3.93 | < .001
#> hp          |       -0.02 | 0.02 | [-0.05,  0.01] | -1.27 | 0.213
#> 
#> Uncertainty intervals (equal-tailed) and p values (two-tailed) computed using a
#>   Wald t-distribution approximation.

m |> standardize() |> model_parameters()
#> Parameter   | Coefficient |   SE |         95% CI |     t(29) |      p
#> ----------------------------------------------------------------------
#> (Intercept) |   -4.10e-18 | 0.09 | [-0.19,  0.19] | -4.41e-17 | > .999
#> cyl         |       -0.67 | 0.17 | [-1.02, -0.32] |     -3.93 | < .001
#> hp          |       -0.22 | 0.17 | [-0.57,  0.13] |     -1.27 | 0.213
#> 
#> Uncertainty intervals (equal-tailed) and p values (two-tailed) computed using a
#>   Wald t-distribution approximation.


# Tests ARE affected by scalling:
m <- lm(mpg ~ cyl + offset(hp), data = mtcars)

m |> model_parameters()
#> Parameter   | Coefficient |    SE |           95% CI | t(30) |      p
#> ---------------------------------------------------------------------
#> (Intercept) |       88.94 | 25.54 | [ 36.78, 141.10] |  3.48 | 0.002 
#> cyl         |      -34.83 |  3.97 | [-42.94, -26.73] | -8.77 | < .001
#> 
#> Uncertainty intervals (equal-tailed) and p values (two-tailed) computed using a
#>   Wald t-distribution approximation.

m |> standardize() |> model_parameters()
#> Parameter   | Coefficient |   SE |         95% CI |    t(30) |      p
#> ---------------------------------------------------------------------
#> (Intercept) |    7.64e-17 | 0.15 | [-0.31,  0.31] | 5.03e-16 | > .999
#> cyl         |       -1.68 | 0.15 | [-2.00, -1.37] |   -10.92 | < .001
#> 
#> Uncertainty intervals (equal-tailed) and p values (two-tailed) computed using a
#>   Wald t-distribution approximation.
```

<sup>Created on 2021-11-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>


</details>

**Comment by bwiernik** [comment]
Hmm, I think default to treating offset the same as response. 

One context where you could use an offset is if you wanted to analyze a difference score (post - baseline), rather than freely estimating a baseline covariate coefficient. That would be standardized.

**Comment by strengejacke** [comment]
I think offsets mostly occur for count-data, and for those, we don't standardize the response anyway. So, we could add offset-terms to the list of variables that are excluded from standardization, and add a message. If users explicitly want that, they should standardize their data before fitting the model.

**Comment by strengejacke** [comment]
> Hmm, I think default to treating offset the same as response.
> 
> One context where you could use an offset is if you wanted to analyze a difference score (post - baseline), rather than freely estimating a baseline covariate coefficient. That would be standardized.

That's a good point. Still, would be a warning/message sufficient?

**Comment by mattansb** [comment]
> One context where you could use an offset is if you wanted to analyze a difference score (post - baseline), rather than freely estimating a baseline covariate coefficient. That would be standardized.

But you would standardize them together, not separately, no?

The solution I'm going with is: if an offset is present, don't standardize it or the response and give a little warning:

```R
# If there's an offset, don't standardize offset OR response
  os <- insight::find_offset(x)
  if (include_response && length(os)) {
    if (verbose) warning("Offset detected - response will not be standardized.", call. = FALSE)
    include_response <- FALSE
  }
```

>  If users explicitly want that, they should standardize their data before fitting the model.

Agree.

**Comment by bwiernik** [comment]
I think it could suffice to standardize both offset and response if `include_response = TRUE`

**Comment by mattansb** [comment]
Okay, I'm going with:
- If `include_response = TRUE`, standardize offset and give warning
- If `include_response = FALSE` don't standardize offset and give warning

**Comment by mattansb** [comment]
No, this just doesn't make sense to me... When an offset is used, we are by definition making a statement about the units of the outcome and the offset variables and how they relate to each other. Standardizing any of them *separately* makes no sense as that "1" coefficient loses its fixed meaning.

I'm sticking with my previous call, but you're welcome to try and change my mind 9:

**Comment by bwiernik** [comment]
Don't get caught up on the "coefficient = 1" bit. If we are standardizing the response, we by definition don't have a coefficient of 1 for the offset on the original scale. The meaning of the offset coefficient is dependent on both the scale of the offset variable and the response variable. 

The general purpose of an offset is to model a difference as the response. This mostly happens in 2 contexts:

1. Modeling log(events / time) = log(events) - log(time) = log(events), offset log(time)

2. Modeling posttest - pretest = posttest, offset(pretest)


For (1), that's going to be some form of GLM, so we won't standardize either response or offset by default.

For (2), that's generally going to be a normal likelihood, so we would standardize the response. But for this difference score to be meaningful, the response and the offset need to be on the same scale. I don't really see a purpose for doing an offset in a normal likelihood model other than in a case like this. So, our default really should be to keep the two variables on the same scale.

**Comment by mattansb** [comment]
> But for this difference score to be meaningful, the response and the offset need to be on the same scale. [...] So, our default really should be to keep the two variables **on the same scale**.

Right, but this would require that `pretest` be standardized like so: `(pretest - mean(pretests)) / `**`sd(posttest)`**, which is something we currently don't/can't do. No?

**Comment by strengejacke** [comment]
![Download](https://user-images.githubusercontent.com/26301769/143267997-762f091a-e633-46ab-8362-edc45586a742.png)

**Comment by mattansb** [comment]
@bwiernik if `two_sd = TRUE` should the offset be standardized by 1 SD (like the response) or by 2 SD (like the predictors)?

**Comment by strengejacke** [comment]
![data_good_question](https://user-images.githubusercontent.com/26301769/143402567-2e37887a-fc6a-4332-b710-cc1c09f43763.jpg)

**Comment by strengejacke** [comment]
(sorry for spam)

**Comment by bwiernik** [comment]
You can post as many memes as you want Daniel

I'd say 1 SD

**Comment by mattansb** [comment]
Done (on #391 )

**Comment by fboetzl** [comment]
Many thanks for your quick answer and your efforts - it is much appreciated! (the memes are as well! ;-) )
