### ISSUE TITLE
Swapped "alternative" for oddsratio, cohens_h and cramers_v compared to the documentation

### ISSUE THREAD

**Issue by hugesingleton** [easystats/effectsize#397]
According to the documentation:

> 
> alternative
> 
>  a character string specifying the alternative hypothesis; Controls the type of CI returned: "two.sided" (two-sided CI; default for Cramer's V, phi (ϕ
> ), and Cohen's w), "greater" (default for OR, RR, Cohen's h and Cohen's g) or "less" (one-sided CI). Partial matching is allowed (e.g., "g", "l", "two"...)
> 

But in the function body:
```

> effectsize::cramers_v
function (x, y = NULL, ci = 0.95, alternative = "greater", 

```
And that's OK - V is bounded by 0.

and
```

> effectsize::oddsratio
function (x, y = NULL, ci = 0.95, alternative = "two.sided",

```
And that's OK - OR is "bi-directional"

and
```

> effectsize::cohens_h
function (x, y = NULL, ci = 0.95, alternative = "two.sided", 
    ...) 

```
Which is also OK :)

But the documentation should be corrected (and also the hint in Rstudio for the parameter) as it's confusing.

**Comment by mattansb** [comment]
oops! 🤭

Fixed - thanks
