### ISSUE TITLE
Replace wrong word?

### ISSUE THREAD

**Issue by thyagoleal** [easystats/effectsize#408]
https://github.com/easystats/effectsize/blob/5ed3f13da55ca806bc0a6eecd0f08f1bdc243cec/man/cohens_d.Rd#L60

Where it reads "two sample" should be "one sample"?

**Comment by bwiernik** [comment]
No it should be two samples. In a one value test, the null parameter is the true mean. In a two sample test, it is the difference between the two means.

**Comment by thyagoleal** [comment]
Got it. I misunderstood thinking it was just a one case parameter. Sorry.
