### ISSUE TITLE
Deal with ellipsis 

### ISSUE THREAD

**Issue by mattansb** [easystats/effectsize#417]
Use `match.call()` instead of `list(...)` where possible.
This preserves lazy evaluation.

**Comment by bwiernik** [comment]
I think `alist(...)` should also preserve lazy evaluation.

**Comment by mattansb** [comment]
Hmmm... Am I using it wrong?

``` r
foo1 <- function(...) {
  bar <- alist(...)
  bar[["a"]]
}

foo2 <- function(...) {
  bar <- list(...)
  bar[["a"]]
}

foo3 <- function(...) {
  bar <- match.call()
  eval(bar[["a"]])
}

foo1(a = 1, stop("BAD"))
#> NULL
foo2(a = 1, stop("BAD"))
#> Error in foo2(a = 1, stop("BAD")): BAD
foo3(a = 1, stop("BAD"))
#> [1] 1
```

<sup>Created on 2022-02-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by bwiernik** [comment]
Nope I must be wrong
