### ISSUE TITLE
Working on caret based models

### ISSUE THREAD

**Issue by asheetal** [easystats/effectsize#445]
repeat of [question ](https://github.com/ModelOriented/ingredients/issues/144)
I want to use model agnostic caret objects to extract effect size. Wondering how to go about that.

**Comment by mattansb** [comment]
Can you give more information, perhaps an example of what you are looking for?

Non-parametric models (like xgboot) don't really lend themselves to predictor specific effect sizes. There are variable importance measures you might want to look at:
 https://topepo.github.io/caret/variable-importance.html
