### ISSUE TITLE
Fix tests failing on older R

### ISSUE THREAD

**Issue by mattansb** [easystats/effectsize#455]
From https://github.com/easystats/effectsize/pull/453

**Comment by IndrajeetPatil** [comment]
Some fail because testthat can't seem to run tests in parallel on R 3.4.

**Comment by mattansb** [comment]
Bug in testthat?

**Comment by IndrajeetPatil** [comment]
Maybe. Can't say for sure.

What I do know is that they don't test on `R 3.4`:
https://github.com/r-lib/testthat/blob/main/.github/workflows/R-CMD-check.yaml

**Comment by IndrajeetPatil** [comment]
The oldest version they test is `R 3.5.3`.

**Comment by mattansb** [comment]
Maybe it is time to support R>=3.5? It's been 4 years...
