### ISSUE TITLE
95% confidence interval for Cohen's d_z

### ISSUE THREAD

**Issue by Daiki-Nakamura-git** [easystats/effectsize#457]
I have a question about the calculation of confidence intervals for the effect size d_z of the two depended samples.

I understand that the test statistic _t_ calculated by the following equation follows a non-central _t_ distribution with non-centrality _λ_ and degrees of freedom _df_ when the null hypothesis is false.
![image](https://user-images.githubusercontent.com/72116259/177745017-bd892394-5e1f-46a4-9a28-ae36f5f3b110.png)

Using this property, we should be able to obtain a confidence interval for d_z by dividing the 95% interval _λ_ of the non-central _t_ distribution by √n and converting it to _δ_.
The R code is expressed as follows.
```
# data
library(mvtnorm)
set.seed(123)
sigma <- matrix(c(100,50,50,100), byrow=TRUE, ncol=2)  # r=0.5
mu <- c(50, 60)
n <- 100
dat <- data.frame(rmvnorm(n=n, mean=mu, sigma=sigma)) 
colnames(dat) <- c("pre","post")
```
```
# Cohen's d_z
library(effectsize)
dz <- cohens_d(dat$post, dat$pre, paired = T) # Cohen's d_z
t <- dz$Cohens_d*sqrt(n) # t value
df <- n-1
library(MBESS)
lambda.ci <- conf.limits.nct(t.value = t, df=df, conf.level = .95) # 95% point of non-central t distribution
lambda.ci$Lower.Limit/sqrt(n)  # 95%CI lower
lambda.ci$Upper.Limit/sqrt(n)  # 95%Ci upper
```

However, the 95% confidence intervals obtained with this code are slightly inconsistent with the results obtained using the _effectsize_ package. It appears that the effectsize package divides λ by √(n-1).
If the code is rewritten as follows, the results agree.
```
lambda.ci$Lower.Limit/sqrt(n-1)  # 95%CI lower
lambda.ci$Upper.Limit/sqrt(n-1)  # 95%Ci upper
dz$CI_low
dz$CI_high
```

I think it would be correct to divide the non-centrality parameter λ by √n. 
Can you tell me why the _effectsize_ package use √(n-1)?

**Comment by mattansb** [comment]
I can't say I remember when or why we decided on this... But you seem to be correct that n should be used there and no df (:

**Comment by Daiki-Nakamura-git** [comment]
Thank you for your quick response to the correction! 
I appreciate the convenient package you have provided.
