### ISSUE TITLE
allowing both central and non-central t-based CIs for Cohen's d and Hedge's g

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/effectsize#47]
Is this something that we can support? 

``` r
mod <- stats::t.test(formula = wt ~ am, data = mtcars)

# non-central t
statsExpressions:::effsize_t_parametric(formula = wt ~ am,
                                        data = mtcars,
                                        tobject = mod,
                                        noncentral = TRUE)
#> # A tibble: 1 x 9
#>   method estimate conf.low conf.high conf.level alternative paired noncentral
#>   <chr>     <dbl>    <dbl>     <dbl>      <dbl> <chr>       <lgl>  <lgl>     
#> 1 Hedge~     1.89     1.10      2.83       0.95 two.sided   FALSE  TRUE      
#> # ... with 1 more variable: var.equal <lgl>

# central t
statsExpressions:::effsize_t_parametric(formula = wt ~ am,
                                        data = mtcars,
                                        tobject = mod,
                                        noncentral = FALSE)
#> # A tibble: 1 x 9
#>   method estimate conf.low conf.high conf.level alternative paired noncentral
#>   <chr>     <dbl>    <dbl>     <dbl>      <dbl> <chr>       <lgl>  <lgl>     
#> 1 Hedge~     1.89     1.00      2.77       0.95 two.sided   FALSE  FALSE     
#> # ... with 1 more variable: var.equal <lgl>
```

<sup>Created on 2020-03-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by mattansb** [comment]
It's not in the pipes right now.

From what I can tell, all major / popular packages offer only the NCP method (that is, all the *other* major packages 😜), which from a theoretical standpoint also seems more accurate (and with minimal additional computing power, even for very very small effect sizes).

(all CIs in all the functions in the package right now are based on NCP, and I kinda like that singular constancy 😅.)

I'll leave this issue open for now (:

**Comment by IndrajeetPatil** [comment]
Fair enough :) 

I agree with you that NCP methods are always better and that's the default in my packages anyway, so not much to lose by not supporting this.

Feel free to close the issue whenever you feel like.

**Comment by mattansb** [comment]
Closing this (:
