### ISSUE TITLE
Adding of φ, Cramer's V (φc), Cohen's w to interpretation vignette

### ISSUE THREAD

**Issue by Buedenbender** [easystats/effectsize#471]
**Describe the solution you'd like**
Hi, thank you for all the work you put into this great collection of packages. 
Screening through the [interpretation](https://easystats.github.io/effectsize/articles/interpret.html#odds-ratio-or) vignette,
I realized it misses the interpretation for the contingency table effect size measures of φ, Cohen's w or Cramer's V. 
Is it intended to keep the vignette brief?
Additionally, for Cohen's w there seems to be now `interpret_cohens_w()` right?

**How could we do it?**
- [x] Add interpret_phi / interpret_cramers_v to the vignette
- [ ] Maybe include `interpret_cohens_w()` function
- [ ] Add `interpret_cohens_w()` as well to the vignette

**Comment by mattansb** [comment]
> I realized it misses the interpretation for the contingency table effect size measures of φ, Cohen's w or Cramer's V.

V, Phi and (Tschuprow's) T are all essentially correlation coefficients, so `interpret_r()` is appropriate for all of them.
Although W is *not* a correlation coefficient, Cohen does suggest the same cutoffs as if it were, so I guess that can also be used.

I have added a note in the vignette:

> There can be used to interpret not only Pearson's correlation coefficient, but also Spearman's, $\phi$ (phi), Cramer's *V* and Tschuprow's *T*. Although Cohen's *w* and Pearson's *C* are _not_ a correlation coefficients, they are often also interpreted as such.
