### ISSUE TITLE
Rename normalized Chi to Waw / Fei?

### ISSUE THREAD

**Issue by mattansb** [easystats/effectsize#474]
Following a scholarly discussion on the [bird app](https://twitter.com/mattansb/status/1568328501056663552?t=a9lhCzl_nn9odmvMQnSlYA&s=19) with @bwiernik , I suggest renaming the nameless effect size to either:

- Waw (ו)
- Fei (פ)

The former is related to v and w, which are other Chisq effect sizes, and is pronounced like word "wow". The latter sounds like phi and maybe looks better in print?

**Comment by bwiernik** [comment]
Let's go with fei

**Comment by DominiqueMakowski** [comment]
You should officialize it and describe it <sub>in the advances in stats computing special issue</sub>
