### ISSUE TITLE
Print effect size symbols?

### ISSUE THREAD

**Issue by mattansb** [easystats/effectsize#488]
@easystats/maintainers Do you know what limitations I might have (R version, systems?) if I were to change the printed names of the effect sizes to proper symbols?

So
``` r
cat("Glass' Delta")
#> Glass' Delta
```

Would become

``` r
cat("Glass' \u0394")
#> Glass' Δ
```

and

``` r
cat("Eta2 (partial)")
#> Eta2 (partial)
```

Would become

``` r
cat("\u03B72 (partial)")
#> η2 (partial)
```

<sup>Created on 2022-09-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Etc?

**Comment by mattansb** [comment]
So... What do we think?

All test and checks (including winbuilder) seem to work...

``` r
library(effectsize)

RCT <- matrix(c(71, 50,
                30, 100), nrow = 2)
m <- lm(mpg ~ cyl + am, data = mtcars)

phi(RCT)
#> Phi  |       95% CI
#> -------------------
#> 0.36 | [0.26, 1.00]
#> 
#> - One-sided CIs: upper bound fixed at [1.00].
```

Turn it one:

``` r
options(es.use_symbols = TRUE)



phi(RCT)
#> ϕ    |       95% CI
#> -------------------
#> 0.36 | [0.26, 1.00]
#> 
#> - One-sided CIs: upper bound fixed at [1.00].

eta_squared(m)
#> # Effect Size for ANOVA (Type I)
#> 
#> Parameter | η² (partial) |       95% CI
#> ---------------------------------------
#> cyl       |         0.75 | [0.61, 1.00]
#> am        |         0.12 | [0.00, 1.00]
#> 
#> - One-sided CIs: upper bound fixed at [1.00].

omega_squared(m)
#> # Effect Size for ANOVA (Type I)
#> 
#> Parameter | ω² (partial) |       95% CI
#> ---------------------------------------
#> cyl       |         0.73 | [0.58, 1.00]
#> am        |         0.08 | [0.00, 1.00]
#> 
#> - One-sided CIs: upper bound fixed at [1.00].

cohens_f_squared(m)
#> # Effect Size for ANOVA (Type I)
#> 
#> Parameter | Cohen's f² (partial) |      95% CI
#> ----------------------------------------------
#> cyl       |                 3.01 | [1.55, Inf]
#> am        |                 0.14 | [0.00, Inf]
#> 
#> - One-sided CIs: upper bound fixed at [Inf].

epsilon_squared(m)
#> # Effect Size for ANOVA (Type I)
#> 
#> Parameter | ϵ² (partial) |       95% CI
#> ---------------------------------------
#> cyl       |         0.74 | [0.59, 1.00]
#> am        |         0.09 | [0.00, 1.00]
#> 
#> - One-sided CIs: upper bound fixed at [1.00].

rank_epsilon_squared(mpg ~ cyl, data = mtcars)
#> ε²(R) |       95% CI
#> --------------------
#> 0.83  | [0.78, 1.00]
#> 
#> - One-sided CIs: upper bound fixed at [1.00].

rank_eta_squared(mpg ~ cyl, data = mtcars)
#> η²(H) |       95% CI
#> --------------------
#> 0.82  | [0.77, 1.00]
#> 
#> - One-sided CIs: upper bound fixed at [1.00].

glass_delta(mpg ~ am, data = mtcars)
#> Glass' Δ |         95% CI
#> -------------------------
#> -1.17    | [-1.93, -0.39]

fei(c(10,20)) # even got the RTL one to work!
#> פ‎    |       95% CI
#> --------------------
#> 0.33 | [0.00, 1.00]
#> 
#> - Adjusted for uniform expected probabilities.
#> - One-sided CIs: upper bound fixed at [1.00].
```

<sup>Created on 2022-09-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by bwiernik** [comment]
I had another issue I opened, maybe in insight?, about this topic where I gave the check for Unicode support we should look for

**Comment by mattansb** [comment]
Yup, found it in parameters https://github.com/easystats/parameters/issues/512

**Comment by mattansb** [comment]
Okay, so it passes on winbuilder even with `options(es.use_symbols = TRUE)` as default!

I think I should set this to `FALSE` for now by default.

**Comment by strengejacke** [comment]
We need an additional print function which returns a table with one column "symbols" and one column "translation" ;-)

**Comment by strengejacke** [comment]
on topic: I have no idea for which R or OS version this works, so I'm not sure if we can activate this by default?

**Comment by mattansb** [comment]
> 
We need an additional print function which returns a table with one column "symbols" and one column "translation" ;-)


``` r
library(effectsize)

get_effectsize_label("Glass_delta")
#> [1] "Glass' delta"
get_effectsize_label("Glass_delta", use_symbols = TRUE)
#> [1] "Glass' Δ"

get_effectsize_label("eta2_partial")
#> [1] "Eta2 (partial)"
get_effectsize_label("eta2_partial", use_symbols = TRUE)
#> [1] "η² (partial)"
```

<sup>Created on 2022-09-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>


> on topic: I have no idea for which R or OS version this works, so I'm not sure if we can activate this by default?

According to @bwiernik original posting https://github.com/easystats/parameters/issues/512, Windows is the trouble maker, and it passes winbuild, so I think that means its fine?

**Comment by strengejacke** [comment]
should we aim for "consistent" option names across packages? See docs here:
https://easystats.github.io/parameters/reference/model_parameters.html#global-options-to-customize-messages-when-printing

**Comment by strengejacke** [comment]
> so I think that means its fine?

I remember some twitter discussion that this feature was introduced only quite recently in R for windows.  I think I have R 4.0 installed somewhere, can test it for that R version, too.

**Comment by mattansb** [comment]
> should we aim for "consistent" option names across packages? See docs here:

`effectsize_` felt like a long prefix.

From what I can see, package options are usually `{some abbreviation on the package name}.{the option}

---

I have R 3.6 somewhere, I can test it.

**Comment by strengejacke** [comment]
> Do you think this should be effectsize_use_symbols instead of es.use_symbols?

A question for @DominiqueMakowski the nomenclature master.

**Comment by IndrajeetPatil** [comment]
I can confirm that on Windows for R version < 4.2, the user gets the following warning:

> unable to translate '<U+03D5>' to native encoding

cf. https://github.com/easystats/effectsize/actions/runs/3095655404/jobs/5010296575

**Comment by mattansb** [comment]
Yup, I'm getting this on R 3.6

```R
print(fei(c(10,30)), use_symbols = T)
#>   <U+05E4><U+200E> |       95% CI
#> -------------------------------
#>   0.50             | [0.24, 1.00]
#> 
#> - Adjusted for uniform expected probabilities.
#> - One-sided CIs: upper bound fixed at [1.00].
```

Okay - so should I set to false if System is windows and R < 4.2?

**Comment by mattansb** [comment]
Okay, I've added some code to set `use_symbols` to `FALSE` when on windows with R < 4.2

**Comment by strengejacke** [comment]
Nice!

**Comment by strengejacke** [comment]
We could add that functionality to `insight::format_table()`

**Comment by mattansb** [comment]
I currently just have a look-up table ^_^

**Comment by bwiernik** [comment]
Yeah that would be a great place for it

**Comment by mattansb** [comment]
Hmmm I think that would be easier to maintain here - I have those convenience functions to [find and replace names](https://easystats.github.io/effectsize/reference/is_effectsize_name.html) which are used in [`see`, `insight` and `report`](https://github.com/search?q=org%3Aeasystats+is_effectsize_name&type=code)

**Comment by strengejacke** [comment]
Maybe we can have both, because you store more information in your lookup-table. But since column name adjustment for the different packages is done in `format_table()`, I think it's also a good place to have the most common effectsizes there, too. For now, this would only activate when `format_symbol = TRUE`, to not break any tests that check the output of `print()`.

``` r
x <- data.frame(phi_adjusted = .3, Fei = .4, Epsilon2 = .7, R2 = 0.4)

insight::format_table(x)
#>   Phi (adj.)  Fei Epsilon2   R2
#> 1       0.30 0.40     0.70 0.40

insight::format_table(x, format_symbols = TRUE)
#>   ϕ (adj.)    פ‎   ϵ²   R²
#> 1     0.30 0.40 0.70 0.40
```

<sup>Created on 2022-09-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
ok, I change the argument to `use_symbols`, too, to be consistent.

**Comment by strengejacke** [comment]
``` r
x <- data.frame(phi_adjusted = .3, Fei = .4, Epsilon2 = .7, R2 = 0.4)

insight::format_table(x)
#>   Phi (adj.)  Fei Epsilon2   R2
#> 1       0.30 0.40     0.70 0.40

insight::format_table(x, use_symbols = TRUE) |> insight::print_md()
```

| ϕ (adj.) | פ‎   | ϵ²   | R²   |
|:---------|:-----|:-----|:-----|
| 0.30     | 0.40 | 0.70 | 0.40 |

``` r
insight::format_table(x, use_symbols = TRUE) |> insight::print_html()
```

<div id="oagnvqyity" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#oagnvqyity .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#oagnvqyity .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#oagnvqyity .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#oagnvqyity .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#oagnvqyity .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#oagnvqyity .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#oagnvqyity .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#oagnvqyity .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#oagnvqyity .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#oagnvqyity .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#oagnvqyity .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#oagnvqyity .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#oagnvqyity .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#oagnvqyity .gt_from_md > :first-child {
  margin-top: 0;
}

#oagnvqyity .gt_from_md > :last-child {
  margin-bottom: 0;
}

#oagnvqyity .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#oagnvqyity .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#oagnvqyity .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#oagnvqyity .gt_row_group_first td {
  border-top-width: 2px;
}

#oagnvqyity .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#oagnvqyity .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#oagnvqyity .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#oagnvqyity .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#oagnvqyity .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#oagnvqyity .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#oagnvqyity .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#oagnvqyity .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#oagnvqyity .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#oagnvqyity .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 4px;
  padding-right: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#oagnvqyity .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#oagnvqyity .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#oagnvqyity .gt_left {
  text-align: left;
}

#oagnvqyity .gt_center {
  text-align: center;
}

#oagnvqyity .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#oagnvqyity .gt_font_normal {
  font-weight: normal;
}

#oagnvqyity .gt_font_bold {
  font-weight: bold;
}

#oagnvqyity .gt_font_italic {
  font-style: italic;
}

#oagnvqyity .gt_super {
  font-size: 65%;
}

#oagnvqyity .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

#oagnvqyity .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#oagnvqyity .gt_indent_1 {
  text-indent: 5px;
}

#oagnvqyity .gt_indent_2 {
  text-indent: 10px;
}

#oagnvqyity .gt_indent_3 {
  text-indent: 15px;
}

#oagnvqyity .gt_indent_4 {
  text-indent: 20px;
}

#oagnvqyity .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col">ϕ (adj.)</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col">פ‎</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col">ϵ²</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col">R²</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left">0.30</td>
<td class="gt_row gt_center">0.40</td>
<td class="gt_row gt_center">0.70</td>
<td class="gt_row gt_center">0.40</td></tr>
  </tbody>
  <tfoot class="gt_sourcenotes">
    <tr>
      <td class="gt_sourcenote" colspan="4"></td>
    </tr>
  </tfoot>
  
</table>
</div>

<sup>Created on 2022-09-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by bwiernik** [comment]
Which epsilon character are we using? We should use \u03b5

**Comment by strengejacke** [comment]
`names(x)[names(x) == "Epsilon2"] <- "\u03F5\u00b2"`

**Comment by strengejacke** [comment]
``` r
library(insight)
x <- data.frame(phi_adjusted = .3, Fei = .4, Epsilon2 = .7, R2 = 0.4)
format_table(x, use_symbols = TRUE)
#>   ϕ (adj.)    פ‎   ε²   R²
#> 1     0.30 0.40 0.70 0.40
```

<sup>Created on 2022-09-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by mattansb** [comment]
> Which epsilon character are we using? We should use \u03b5

I just changed it to this, but Kelly originally used the other epsilon, so maybe...? Do we go with the source or with what is now common?

**Comment by bwiernik** [comment]
The two symbols are interchangeable, but the curvy epsilon (LaTeX \varepsilon) is way more common in math and stats typesetting in general. There are a bunch of references using each in the effect size literature and, eg, Stata uses curvy epsilon https://www.stata.com/features/overview/effect-sizes/

**Comment by strengejacke** [comment]
> Stata uses curvy epsilon

But only in the docs, not in their output, we're way cooler!

![image](https://user-images.githubusercontent.com/26301769/191714694-72525ca4-bf02-4925-8741-19cc2c9fb335.png)
