### ISSUE TITLE
effectsize() function

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/effectsize#49]
So far pretty much of all our packages have their big function, parameters::parameters(), performance::performance(), correlation::correlation() etc.

Would be good to have `effectsize::effectsize()` as a wrapper for other functions, that you could run on models.

For instance on t.tests (would return one/multiple *d*s), on regression models (standardized parameters), etc. 

Thoughts?

**Comment by mattansb** [comment]
Interesting..

For `t.test`, `cor.test`, `chisq.test`, and `anova` this is quite easy (Cohen's d, r, Cramer's V, Eta2p),
for models which would you choose?

- beta? (`standardize_parameters()`)
- eta? (`eta_squared()`)
- r for slopes? (nah)

**Comment by DominiqueMakowski** [comment]
the latter ties back to my issue regarding the unified index for regression models... but in the meantime, I'd say `standardize_parameters()` seems to be expected

**Comment by mattansb** [comment]
I think anova -> eta, else `standardize_parameters` (:

**Comment by DominiqueMakowski** [comment]
agreed

**Comment by mattansb** [comment]
``` r
library(effectsize)
contingency_table <- as.table(rbind(c(762, 327, 468), c(484, 239, 477), c(484, 239, 477)))
Xsq <- chisq.test(contingency_table)
effectsize(Xsq)
#> cramers_v |       95% CI
#> ------------------------
#>      0.07 | [0.05, 0.09]

Ts <- t.test(1:10, y = c(7:20))
effectsize(Ts)
#>     d |         95% CI
#> ----------------------
#> -2.32 | [-3.38, -1.22]

fit <- lm(mpg ~ factor(cyl) * wt + hp, data = mtcars)
effectsize(fit)
#>         Parameter Std_Coefficient
#> 1     (Intercept)     0.001135606
#> 2    factor(cyl)6    -0.202992374
#> 3    factor(cyl)8    -0.316876202
#> 4              wt    -0.895510974
#> 5              hp    -0.253601012
#> 6 factor(cyl)6:wt     0.368715669
#> 7 factor(cyl)8:wt     0.543855222

anova_table <- anova(fit)
effectsize(anova_table)
#> Parameter      | Eta_Sq_partial |       90% CI
#> ----------------------------------------------
#> factor(cyl)    |           0.86 | [0.76, 0.91]
#> wt             |           0.47 | [0.22, 0.64]
#> hp             |           0.14 | [0.00, 0.36]
#> factor(cyl):wt |           0.16 | [0.00, 0.35]
```

<sup>Created on 2020-03-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DominiqueMakowski** [comment]
noice 👌🎉, I even think we should add that on the readme as the default workflow, like model %>% effectsize()
