### ISSUE TITLE
`pearsons_c()` no longer has `adjust` parameter?

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/effectsize#490]
In CRAN version, it is present:

<img width="455" alt="Screenshot 2022-09-20 at 18 56 49" src="https://user-images.githubusercontent.com/11330453/191319090-69cf69e6-f771-436c-abeb-17e3b827a113.png">

But not in the GitHub version, but I can't also find any information about this change in NEWS.

Was this a deliberate change? If yes, then it will be good to mention it in the change log.

**Comment by mattansb** [comment]
Like you do you even...

I've updated the NEWS.md file (:

**Comment by IndrajeetPatil** [comment]
Thanks.

Btw, for other effect sizes where this argument is relevant, we default to `FALSE`, but I couldn't find anything in the docs to suggest that this is because this is the best practice or otherwise. 

As a user, I'd really find such a discussion useful.

**Comment by mattansb** [comment]
For small samples, its better to have `adjust = TRUE` on Phi and Cramer's V.
However, I thought it better to be consistent with the most common effect size, which is not adjusted. I will add to the docs.

**Comment by bwiernik** [comment]
For some effect sizes, the small sample bias correction is routinely applied. For others, it is rarely used. There isn't really any justification for not using it. In general, my preference would be to use the unbiased estimators that said, one worry I have is that because the effect size is typically reported without the bias correction, I would worry that meta-analysts might inadvertently double correct for it. A probably smaller concern would be users noticing and being confused by numbers not matching what they get elsewhere (eg, for a correlation).

**Comment by bwiernik** [comment]
For effect sizes in the standardized mean difference, family, different names are sometimes used for affect sizes with and without device correction. For example, D usually doesn't have the bias correction, whereas G does. But that is also very inconsistent. Although G always has the correction in my experience, d very often does too.

**Comment by mattansb** [comment]
> A probably smaller concern would be users noticing and being confused by numbers not matching what they get elsewhere (eg, for a correlation).

To me, this is the bigger concern. Also other packages do not correct by default.

In any case, when the correction is applied, the effect's label is changed `Phi` vs `Phi (adj.)`, etc...

I guess I could add the formulas for the corrections to the docs, also.

**Comment by IndrajeetPatil** [comment]
> In any case, when the correction is applied, the effect's label is changed `Phi` vs `Phi (adj.)`, etc...

Thinking more about this, I strongly feel that we should be adjusting by default. Given the labels, there is no confusing whether the effect size is adjusted or not.

**Comment by bwiernik** [comment]
Just to be clear, these are all small sample bias corrections, not continuity corrections, right?

**Comment by IndrajeetPatil** [comment]
IINM, yes, these are small sample bias corrections.

**Comment by bwiernik** [comment]
Okay, then I'm fine with it.
