### ISSUE TITLE
Improvements to Effect Size (Eta2, Omega2) Indices for ANOVAs

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/effectsize#5]
Combining several issues here:

- [x] Support repeated measures ANOVAs (#84, easystats/parameters#100):
    - [x] make it work for `anova(themixedmodel)`
    - [x] make it work for `anova(aovlist)`
    - [x] Make sure these are *correct*
- [ ] Generalized eta2 and Omega2 (#91)
    - https://www.frontiersin.org/articles/10.3389/fpsyg.2013.00863/full
- [x] Adjusted eta2
    - https://journals.sagepub.com/doi/abs/10.1177/2515245919855053?journalCode=ampa

Does anybody know an expert of ANOVAs that could help us going through this?

**Comment by DominiqueMakowski** [comment]
I have "successfully" (I *think*) moved ANOVA indices here from parameters (by replacing the instances of extract_parameters by model_parameters), this time without removing them from parameters yet (however, they needs `model_parameters`, hence parameters must be a dep of effectsize)

I'd suggest updating parameters on CRAN and submit effectsize anytime soon.

The two annoying consequences will be 1) breaking changes related to standardized parameters for regressions (`parameters::parameters_standardize` ->  `effectsize::standardize_parameters`). This issue could be dampened by re-adding the functions in parameters just to deprecate them indeed (saying, "this is now in effectsize"). 

The second annoying thing will be the double export of ANOVA related ES indices, as they currently exist in both packages. Again, we could deprecate their version in parameters (or remove them). 

But the transfer of the functions that we wanted to do is done I think, so it's just now a matter of updating the reversed deps. What do you think?

**Comment by strengejacke** [comment]
Can you update docs, namespace and website? I still don't see where parameters is a dependency of effectsize.

**Comment by DominiqueMakowski** [comment]
@mattansb The name says `F_to_partial_eta_squared` but in the definition it says *"These functions are convenience functions to convert \eqn{F} and \eqn{t}' test statistics to \eqn{\eta_p^2}"* is it eta² or partial eta²?

@strengejacke namespace updated

**Comment by mattansb** [comment]
All the functions are for partial - that's what the "p" is for:
> These functions are convenience functions to convert \eqn{F} and \eqn{t} test statistics to \eqn{\eta_**p**^2}, \eqn{\omega_**p**^2}, \eqn{\epsilon_**p**^2}, or \eqn{Adj. \eta_**p**^2}.

**Comment by DominiqueMakowski** [comment]
oh right right have missed that! (I am doing some renaming if you don't mind 😬 😅)

**Comment by mattansb** [comment]
Going back to [where this thread started](https://github.com/easystats/effectsize/issues/5#issue-505767423), I've made some changes to the `eta_squared`, `epsilon_squared` and `omega_squared` functions:

1. The partialled versions support mixed models (via `merMod`), and repeated measures (`aovlist`) via the `F_to_*` functions.
2. Now offering partial epsilon sq for `aov` objects.
3. Added `eta_squared_adj`, which is just a wrapper for `epsilon_squared`, as they are the same (as is shown in the [paper's](https://doi.org/10.1177/2515245919855053) appendix).

As they are, a lot of the methods across the functions repeat themselves - something I will go back to at some point.

***Question***: For Omega2, CIs are bootstrapped for partial estimates, while for Eta2, CIs are bootstrapped for **non**-partial estimates. Is this correct?

**Comment by IndrajeetPatil** [comment]
@DominiqueMakowski Until we figure out a better solution, can we rely on this for `aovlist`? 
I want to rely on `effectsize` in my own package and have been waiting for the `aovlist` support.

https://github.com/strengejacke/sjstats/blob/a1df042bba7f3034c708ed9cdc2982310e35598f/R/eta_sq.R#L165-L189

**Comment by DominiqueMakowski** [comment]
@IndrajeetPatil rely on this as in on the current aovlist support added by @mattansb or on the sjstats solution?

This makes me think that It would be nice to create a vignette about these ANOVA-related functions, to provide an overview (also useful for us to provide a clear testing framework).

**Comment by IndrajeetPatil** [comment]
Oops, linked to the wrong thing then. I meant adding support for omega-squared for `aovlist` objects.

And, I agree, it will be nice to have an overview vignette.

**Comment by mattansb** [comment]
I'm closing this issue, as most of the point brought up here have either been dealt with or were completely OT 😅
