### ISSUE TITLE
Get test coverage over 80% for each file

### ISSUE THREAD

**Issue by mattansb** [easystats/effectsize#501]
https://app.codecov.io/gh/easystats/effectsize/tree/main/R

**Comment by IndrajeetPatil** [comment]
You should skip `zzz.R` while computing code coverage.

You can use `{covr}` directives to do so (for example, see [this](https://github.com/r-lib/lintr/blob/e993d4d37fc3016aefade264b4547ea76dc40f06/R/zzz.R#L243-L288)).
