### ISSUE TITLE
Add styler ignore directives

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/effectsize#508]
@mattansb In this [PR](https://github.com/easystats/effectsize/pull/507), you mentioned that you don't like formatting that follows the tidyverse style guide. But, in our [contributing guidelines](https://easystats.github.io/effectsize/CONTRIBUTING.html), we mention that we do follow this style guide. I am not happy that `{effectsize}` is the only exception now.

A way out of this is to ignore parts of code from `{styler}`. This way, we don't need to skip style guide only in one repo.

``` r
styler::style_text("
a=1

x   <- 2
xyz <- 3
")
#> 
#> a <- 1
#> 
#> x <- 2
#> xyz <- 3

styler::style_text("
a=1

# styler: off
x   <- 2
xyz <- 3
# styler: on
")
#> 
#> a <- 1
#> 
#> # styler: off
#> x   <- 2
#> xyz <- 3
#> # styler: on
```

<sup>Created on 2022-10-01 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

For rmarkdown code chunks, you can use `tidy = FALSE`.

<img width="999" alt="Screenshot 2022-10-01 at 06 21 59" src="https://user-images.githubusercontent.com/11330453/193392338-b971a9fd-fafd-4503-b0f1-c4a00f94a7e1.png">

For more, see: https://styler.r-lib.org/reference/stylerignore.html?q=ignore

**Comment by mattansb** [comment]
I'm not against it overall - just that there are specific incidents where having clear irrelevant code is distracting from the main code in the examples.

Like I don't need the 2-3 lines of code that build a matrix for an example to become 6 lines of neat code, because the point is actually what is *done* with that matrix. YKWIM?

Perhaps this can be solved by just making those matrices part of the package data.

**Comment by IndrajeetPatil** [comment]
> Perhaps this can be solved by just making those matrices part of the package data.

Yes, this sounds like a good solution to me.

**Comment by IndrajeetPatil** [comment]
Btw, if you store the script to generate the data in `data-raw` [folder](https://github.com/IndrajeetPatil/ggstatsplot/tree/main/data-raw), that will also be styled. 😅

So you will need to use styler ignore directives at some point.
