### ISSUE TITLE
CRAN 0.3.0

### ISSUE THREAD

**Issue by mattansb** [easystats/effectsize#51]
I would like this on CRAN by early May (teaching ANOVA 😁).

Anything we should aim to add before next release?

**Comment by DominiqueMakowski** [comment]
nothing urgent afaic

**Comment by strengejacke** [comment]
> teaching ANOVA

![stupid-is-as-stupid-does](https://user-images.githubusercontent.com/26301769/77824442-f1462200-7102-11ea-8344-008058ce9a96.jpg)

**Comment by strengejacke** [comment]
Note that pkgpown 1.5.0 somehow doesn't render R code properly, so stick to version 1.4.1...

**Comment by IndrajeetPatil** [comment]
Yeah! Something has seriously gone wrong with how `README` codes are getting rendered in `pkgdown 1.5.0`.

**Comment by IndrajeetPatil** [comment]
Btw, is this something that we need to address before `CRAN` submission?
https://github.com/strengejacke/sjstats/issues/51#issuecomment-605488416

I am no longer even sure if this is an issue. But just wanted to compare outputs from `sjstats` and `effectsize` and once again came across that issue.

**Comment by mattansb** [comment]
See my comment there (:

**Comment by IndrajeetPatil** [comment]
Nothing else from my end. :)

**Comment by strengejacke** [comment]
Does the next release break existing code, e.g. in _parameters_?

**Comment by mattansb** [comment]
Yes - but I think just the stuff you fixed with ANOVA model_parameters.

**Comment by strengejacke** [comment]
Just let me know if we need to submit parameters first, then I'll check parameters on the latest version of effectsize.

**Comment by mattansb** [comment]
Would it be crazy to wait for `dplyr 1.0.0`? I have some function examples that would work really well with the new functionality 😅

Otherwise, can do this as early as next week (unless I find any new bugs to squash).

**Comment by strengejacke** [comment]
> Would it be crazy to wait for dplyr 1.0.0

Yes ;-)

**Comment by IndrajeetPatil** [comment]
I think `dplyr` is scheduled for _submission_ in May and given the number of dependencies it has, it will take a while for it to be accepted (maybe June).
 
That's lot of a wait! I would really appreciate it if we can push this new release before that, especially when it contains a few critical fixes (e.g., the incorrect pooled SD issue), and then have another minor release if `dplyr` changes breaks anything. 

Thanks in advance for considering this request.

**Comment by mattansb** [comment]
@IndrajeetPatil sounds like a good idea.

Next week then (:

**Comment by mattansb** [comment]
@strengejacke are you going to submit `parameters` before I submit `effectsize`? If so, I think https://github.com/easystats/parameters/issues/233 should be solved, and we're ready to go (:

**Comment by strengejacke** [comment]
> @strengejacke are you going to submit parameters before I submit effectsize?

I think we need to do this, else effectsize will break _parameters_. If everything is addressed here now, let's merge, so we have a clean master for checking (parameters needs to work with both current CRAN and current GitHub version of _effectsize_ - and you know, I cannot install from dev branch...)

**Comment by mattansb** [comment]
Merged.

**Comment by strengejacke** [comment]
https://cran.r-project.org/package=parameters

parameters-update is on CRAN, _should_ work with new effectsize.

**Comment by mattansb** [comment]
So.... how do I submit??

**Comment by IndrajeetPatil** [comment]
I usually do `devtools::submit_cran()` and that does it.

**Comment by mattansb** [comment]
Is that really all it takes???

God, I love R...

**Comment by IndrajeetPatil** [comment]
You will still have to **approve** the e-mail that CRAN will send to you and only then will the submission be finalized. 

Maybe you already know that, but just wanted to double-check.

**Comment by mattansb** [comment]
This is my first submission..

Does it matter that Dom used to be the maintainer?

**Comment by DominiqueMakowski** [comment]
Last time when we changed for parameters @strengejacke I think they asked him to confirm with me CCed that the change was legit, but nothing more if I recall

**Comment by strengejacke** [comment]
1) check the package locally
2) build the **source**-package
3) submit source to https://win-builder.r-project.org/ (wait for positive checks)
4) submit source package via https://cran.r-project.org/submit.html

I personally would not rely on devtools, even the local check is better using base R (because it also detects broken URLs etc.)

**Comment by mattansb** [comment]
> package effectsize_0.3.0.tar.gz is on its way to CRAN.

**Comment by DominiqueMakowski** [comment]
👏

**Comment by strengejacke** [comment]
> effectsize 0.2.0
> Changes
> News are hidden in an air of mystery…

🤣
