### ISSUE TITLE
`na.action` deactivated in last version of effectsize

### ISSUE THREAD

**Issue by iago-pssjd** [easystats/effectsize#517]
With the modification in commit 70c4902 of

https://github.com/easystats/effectsize/blob/45f6172cf2c9b813a57ce398a82572bdcab1b72f/R/utils_validate_input_data.R#L310-L319

currently, passing  `na-action` distinct of `na.pass` to those functions using this one,  for example `cohens_d(formula, na.action = na.omit)`, has no effect.

**Comment by mattansb** [comment]
You are right - I accidently override any user-passed na.action...

However, I'm not getting the same error you are, just a warning.

``` r
library(effectsize)

mtcars$mpg[1] <- NA

cohens_d(mpg ~ am, data = mtcars,
         na.action = na.fail)
#> Warning: Missing values detected. NAs dropped.
#> Cohen's d |         95% CI
#> --------------------------
#> -1.52     | [-2.33, -0.69]
#> 
#> - Estimated using pooled SD.
```

<sup>Created on 2022-10-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by mattansb** [comment]
This was my intended behavior:

``` r
library(effectsize)

mtcars$mpg[1] <- NA

cohens_d(mpg ~ am, data = mtcars) # default: na.pass - gives warning
#> Warning: Missing values detected. NAs dropped.
#> Cohen's d |         95% CI
#> --------------------------
#> -1.52     | [-2.33, -0.69]
#> 
#> - Estimated using pooled SD.

cohens_d(mpg ~ am, data = mtcars, # no warning
         na.action = na.omit)
#> Cohen's d |         95% CI
#> --------------------------
#> -1.52     | [-2.33, -0.69]
#> 
#> - Estimated using pooled SD.

cohens_d(mpg ~ am, data = mtcars, # error
         na.action = na.fail)
#> Error in na.fail.default(structure(list(mpg = c(NA, 21, 22.8, 21.4, 18.7, : missing values in object
```

<sup>Created on 2022-10-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by iago-pssjd** [comment]
Sorry! I have probably copied an error from the wrong place. I was getting also a warning.
