### ISSUE TITLE
Clearly describe that one can convert d to point-biserial correlation and vice-versa

### ISSUE THREAD

**Issue by wviechtb** [easystats/effectsize#534]
In https://easystats.github.io/effectsize/articles/convert_r_d_OR.html you describe how to convert d values to correlations and vice-versa. The conversion described there transforms a d values to a **point-biserial correlation** and back, not a Pearson product-moment correlation coefficient (some may use `r_to_d()` thinking they can convert a Pearson product-moment correlation coefficient between two continuous variables into a d value, but that is not how this transformation should be used). Also, the exact transformation is $r_{pb} = \frac{d}{\sqrt{d^2 + h}}$ and $d = \frac{r_{pb} \sqrt{h}}{\sqrt{1-r_{pb}^2}}$, where $h = \frac{m}{n_1} + \frac{m}{n_2}$ and $m = n_1 + n_2 - 2$, where $n_1$ and $n_2$ are the group sizes. When assuming $n_1 = n_2$ and ignoring the $-2$, then this simplifies to $4$.

**Comment by mattansb** [comment]
Thanks @wviechtb !

``` r
effectsize::r_to_d(0.5)
#> [1] 1.154701

effectsize::r_to_d(0.5, n1 = 20, n2 = 2)
#> [1] 1.914854
```

<sup>Created on 2022-11-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I've also made this more clear in to docs - see #535.
let me know if this is clearer

**Comment by wviechtb** [comment]
Great, thanks for tackling this so quickly!

**Comment by mattansb** [comment]
@wviechtb Do you have a citation for this method of $h$?

[Here](https://www.meta-analysis.com/downloads/Meta-analysis%20Converting%20among%20effect%20sizes.pdf) they are using $h = \frac{(n1 + n2)^2}{n1 * n2}$, which is equal to the formulation you suggested with $m = n1 + n2$.

**Comment by wviechtb** [comment]
Indeed, people have used all kinds of values for $h$. But if you want to convert d to a point-biserial correlation coefficient and have it be exactly the same as if you had the raw data, then it's the one I gave. An example:

```r
n1 <- 10
n2 <- 20
x1 <- rnorm(n1, 6, 1)
x2 <- rnorm(n2, 5, 1)
d <- c(mean(x1) - mean(x2)) / sqrt(((n1-1)*var(x1) + (n2-1)*var(x2)) / (n1 + n2 - 2))
h <- (n1 + n2 - 2) / n1 + (n1 + n2 - 2) / n2
d / sqrt(d^2 + h)
cor(rep(c(1,0), times=c(n1,n2)), c(x1,x2))
```

Anything else is an approximation.

A reference for this:

Jacobs, P. & Viechtbauer, W. (2017). Estimation of the biserial correlation and its sampling variance for use in meta-analysis. _Research Synthesis Methods, 8_(2), 161-180. https://doi.org/10.1002/jrsm.1218

**Comment by mattansb** [comment]
Thanks, added the citation to your paper
