### ISSUE TITLE
Update default rules for lavaan fit measures

### ISSUE THREAD

**Issue by lstmemery** [easystats/effectsize#538]
**Describe the bug**
Not sure if this counts as a bug, but the default cutoff for NFI (and related fit indices, such as NNFI and CFI) is 0.90, citing Byrne 1994. This textbook has a more recent edition:

Byrne, B. M. (2016). Structural Equation Modeling With AMOS: Basic Concepts, Applications, and Programming, Third Edition (3rd edition). Routledge.

Here's a passage from page 96:

> Although a value >.90 [for CFI] was originally considered representative of a well-fitting model (see Bentler, 1992), a revised cutoff value close to .95 has recently been advised (Hu & Bentler, 1999). ... As shown in [table], the CFI (.962) indicated that the model fitted the data well in the sense that the hypothesized model adequately described the sample data. In somewhat less glowing terms, the NFI value suggested that model fit was only marginally adequate (.907).

This would suggest to me that the appropriate default cut-offs should be >.90 is adequate and >.95 is good.

**To Reproduce**
``` > interpret_nfi(c(.5, .89, .91, .99))
[1] "poor"         "poor"         "satisfactory" "satisfactory"
(Rules: byrne1994)
> interpret_cfi(c(.5, .89, .91, .99))
[1] "poor"         "poor"         "satisfactory" "satisfactory" 
```

**Expected behavior**

```> interpret_nfi(c(.5, .89, .91, .99))
[1] "poor"         "poor"         "satisfactory" "good"
(Rules: byrne1994)
> interpret_cfi(c(.5, .89, .91, .99))
[1] "poor"         "poor"         "satisfactory" "good"
```

**Specifiations (please complete the following information):**
 - `R` Version 4.2.2 Patched (2022-11-10 r83330)
 - `effectsize` Version 0.8.1

**Comment by mattansb** [comment]
So we should add a `"byrne2016"` with a 0.95 cutoff?

--- 

Reading the quoted text, we have:
- CFI = .962 -> adequate
- CFI = .907 -> marginally adequate

(Since we don't have any other "marginal" cutoffs (e.g., we don't have "marginally significnat"), I see need to add the second 0.9 cutoff here)

**Comment by lstmemery** [comment]
That makes sense to me!
