### ISSUE TITLE
Add ARR and NNT

### ISSUE THREAD

**Issue by mattansb** [easystats/effectsize#559]
$SE_{ARR} = \sqrt{\frac{p_1 (1-p_1)}{n_1} + \frac{p_2 (1-p_2)}{n_2}}$

ARR = `p0 - p0 * oddsratio_to_riskratio(OR, p0)`

ARR = `p0 - p0 * riskratio`

$NNT = \frac{1}{ARR}$

---

Also:
- [ ] Add for `htest`
- [ ] Add for `BFBayesFactor`

**Comment by bwiernik** [comment]
Ah, NNT, Brenton's least favorite effect size metric 😜

**Comment by mattansb** [comment]
I like ARR 🏴‍☠️
