### ISSUE TITLE
Encoding issue?

### ISSUE THREAD

**Issue by strengejacke** [easystats/effectsize#560]
See https://www.r-project.org/nosvn/R.check/r-oldrel-windows-ix86+x86_64/effectsize-00check.html

**Comment by mattansb** [comment]
Odd.... This seems to be due to the use of "meta‐analysis" instead of "meta-analysis" (can anyone but @bwiernik spot the difference?)

Will CRAN ask for a fix?

**Comment by bwiernik** [comment]
What do you mean Mattan? What's the difference there? Are you sure it's not a Greek character or similar?

**Comment by mattansb** [comment]
The error is about the U+2010 character, which is a (true) hyphen 🤷

**Comment by bwiernik** [comment]
No idea about that one!
