### ISSUE TITLE
convert_oddsratio_to_riskratio() / convert_oddsratio_to_riskdiff() and vice versa

### ISSUE THREAD

**Issue by bwiernik** [easystats/effectsize#568]
```
convert_oddsratio_to_odds <- function(OR, log = FALSE, base_rate = NULL, base_odds = NULL) {
  if (is.null(base_odds)) {
    if (is.null(base_rate)) {
      insight::format_error("Either `base_rate` or `base_odds` must be supplied.")
    }
    base_odds <- convert_probs_to_odds(base_rate, log = log)
  }
  compare_odds <- ifelse(isTRUE(log), OR + base_odds, OR * base_odds)
  return(compare_odds)
}

convert_oddsratio_to_probs <- function(OR, log = FALSE, base_rate = NULL, base_odds = NULL) {
  compare_odds <- convert_oddsratio_to_odds(OR = OR, log = log, base_rate = base_rate, base_odds = base_odds)
  compare_rate <- convert_odds_to_probs(compare_odds, log = log)
  return(compare_rate)
}

convert_oddsratio_to_riskratio <- function(OR, log = FALSE, base_rate = NULL, base_odds = NULL) {
  compare_rate <- convert_oddsratio_to_probs(OR = OR, log = log, base_rate = base_rate, base_odds = base_odds)
  if (is.null(base_rate)) {
    base_rate <- convert_odds_to_probs(base_odds, log = log)
  }
  riskratio <- compare_rate / base_rate
}

convert_oddsratio_to_riskdiff <- function(OR, log = FALSE, base_rate = NULL, base_odds = NULL) {
  compare_rate <- convert_oddsratio_to_probs(OR = OR, log = log, base_rate = base_rate, base_odds = base_odds)
  if (is.null(base_rate)) {
    base_rate <- convert_odds_to_probs(base_odds, log = log)
  }
  riskratio <- compare_rate - base_rate
}
```

**Comment by mattansb** [comment]
We have the OR to RR one here https://easystats.github.io/effectsize/reference/oddsratio_to_riskratio.html

Should we have all possible pairings?

**Comment by bwiernik** [comment]
Oh, then I guess the issue is that some of our functions start with convert and some don't. That's confusing and we should consider standardizing

**Comment by mattansb** [comment]
I think the verbosity can be reduced (:

**Comment by strengejacke** [comment]
Do any functions start with `convert_*`?

**Comment by strengejacke** [comment]
Just saw, that seem to be aliases, right? Maybe we can deprecate those?

**Comment by strengejacke** [comment]
But for convenience reasons, we could probably add those conversion functions, too? And also add log-odds functions that call the oddsratio-functions with `log = TRUE`?  Some colleagues were using the _effectsize_ package and "complaining" that you can only convert to/from odds ratio, but not log-odds. They missed the `log` argument, which also isn't clearly documented (people need "keywords" like "log-odds" or similar).

**Comment by mattansb** [comment]
Okay, so I think we need two sets of functions:

## 1. Between prob-change metrics 

- [x] OR to RR (`oddsratio_to_riskratio`)
- [x] OR to ARR (`oddsratio_to_arr`)
- [ ] OR to NNT
- [ ] logOR to RR
- [ ] logOR to ARR
- [ ] logOR to NNT
- [x] RR to OR (`riskratio_to_oddsratio`)
- [ ] RR to logOR
- [x] RR to ARR (`riskratio_to_arr`)
- [ ] RR to NNT
- [x] ARR to OR (`arr_to_oddsratio`)
- [ ] ARR to logOR
- [x] ARR to RR (`arr_to_riskratio`)
- [x] ARR to NNT (`arr_to_nnt`)
- [ ] NNT to OR
- [ ] NNT to logOR
- [ ] NNT to RR
- [x] NNT to ARR (`nnt_to_arr`)

Do we need??
- [ ] OR to logOR
- [ ] logOR to OR

## 2. Change to Probs

- [ ] OR to prob
- [ ] logOR to prob
- [ ] RR to prob
- [ ] ARR to prob
- [ ] NNT to prob

@strengejacke @bwiernik 
- Do we also want the inverse of these? (e.g., prob to OR)
- Do we also want conversion to odds? (e.g., NNT to odds)
---

Also

- [ ] Deprecate all the `convert_` functions (sorry @DominiqueMakowski )
- [ ] d to logOR

@strengejacke started on some of these in #569

**Comment by mattansb** [comment]
Closing in favor of #660
