### ISSUE TITLE
New potential function: `interpret_r2_semipartial()`?

### ISSUE THREAD

**Issue by rempsyc** [easystats/effectsize#570]
I've been asked how to interpret small, medium, large effects for the `r2_semipartial` reported in `rempsyc`. Would it make sense to have an `effectsize::interpret_r2_semipartial()` function?

Would we be allowed to simply do:

```r
interpret_r2_semipartial() <- interpret_eta_squared()
```

Do the thresholds differ at all? If that works I could make a PR.

**Comment by bwiernik** [comment]
So, it's increase in R squared, generally we would probably expect them to be somewhat smaller than R2 by itself. Maybe cut the thresholds in half?

**Comment by rempsyc** [comment]
Do you mean split in half the R2 thresholds or the pEta-sqr thresholds?

`interpret_r2()` (Cohen 1988) is

> - R2 < 0.02 - Very weak
> - 0.02 <= R2 < 0.13 - Weak
> - 0.13 <= R2 < 0.26 - Moderate
> - R2 >= 0.26 - Substantial

So half of that would be:

> - R2 < 0.01 - Very weak
> - 0.01 <= R2 < 0.065 - Weak
> - 0.065 <= R2 < 0.13 - Moderate
> - R2 >= 0.13 - Substantial

But in my experience sr2 is usually smaller and closer to the pEta-sqr.

`interpret_eta_squared()` (Field 2013) is

> - ES < 0.01 - Very small
> - 0.01 <= ES < 0.06 - Small
> - 0.06 <= ES < 0.14 - Medium
> - **ES >= 0.14** - Large

So half of that would be:

> - ES < 0.005 - Very small
> - 0.005 <= ES < 0.03 - Small
> - 0.03 <= ES < 0.7 - Medium
> - **ES >= 0.7** - Large

Thoughts?

**Comment by mattansb** [comment]
I also think this should just be an alias to the partial eta square interpretations... no?

**Comment by rempsyc** [comment]
In retrospective, I can see that half of R2 is almost identical to the Eta-sqr thresholds so I can see the logic there (0.01 vs 0.01; 0.065 vs 0.06; and 0.13 vs 0.14; it's like rounding error). I'll open a PR.

**Comment by bwiernik** [comment]
Yeah just the eta squared thresholds is fine
