### ISSUE TITLE
Confidence interval of Cohen's d in large datasets

### ISSUE THREAD

**Issue by jkelgs** [easystats/effectsize#574]
**Describe the bug**
Confidence intervals of Cohen's d seems wrong in large datasets, i.e., the point estimate is outside the confidence interval

**To Reproduce**
library(effectsize)
x <- mtcars[rep(1:nrow(mtcars), 100),]
cohens_d(x$wt, mu = 0)

**Specifiations (please complete the following information):**
 - `R` Version [4.2.2]
 - `effectsize` Version [0.8.3]

**Comment by mattansb** [comment]
> "For very large sample sizes or effect sizes, the width of the CI can be smaller than the tolerance of the optimizer, resulting in CIs of width 0. This can also result in the estimated CIs excluding the point estimate."
>
> From *[CI Does Not Contain the Estimate](https://easystats.github.io/effectsize/reference/effectsize_CIs.html#ci-does-not-contain-the-estimate)*

There are no plans to fix this at this time.

An alternative would be to bootstrap the CI instead:

```R
library(effectsize)

x <- mtcars[rep(1:nrow(mtcars), 100),]

cohens_d(x$wt)
#> Cohen's d |       95% CI
#> ------------------------
#> 3.34      | [3.67, 3.67]


## Bootstrap:

n <- nrow(x)

ds <- replicate(1000, {
  x_boot <- x[sample(n, replace = TRUE),] # sample obs. with replacment
  d_boot <- cohens_d(x_boot$wt, ci = NULL)
  d_boot[[1]]
})

bayestestR::describe_posterior(ds, centrality = "mean", test = NULL)
#> Summary of Posterior Distribution
#> 
#> Parameter | Mean |       95% CI
#> -------------------------------
#> Posterior | 3.34 | [3.27, 3.44]
```

**Comment by jkelgs** [comment]
thank you very much for your quick and elaborate answer!
