### ISSUE TITLE
Add additional logOR to d transofmration 

### ISSUE THREAD

**Issue by mattansb** [easystats/effectsize#593]
$$
d_{Cox} = \ln(OR) / 1.65
$$

Also note that since these are linear transformations, the SE of the resulting d is the transformed SE of the log(OR).

**Comment by bwiernik** [comment]
Let's be precise and divide by (pi / sqrt(3))

**Comment by mattansb** [comment]
We already have the 3/sqrt(pi) conversion. 
1.65 is from Sánchez-Meca, et al. (2003). Effect-size indices for dichotomized outcomes in meta-analysis. Psychological methods, 8(4), 448.

A user (meta-analyst) emailed me asking if we might add this conversion as well.

**Comment by DominiqueMakowski** [comment]
Maybe `qnorm(0.95)`?

**Comment by bwiernik** [comment]
Let me look into it—it's not obvious to me what the theory is behind that value (and the meta-analysis literature is rife with junk conversions, so I start off skeptical)

**Comment by mattansb** [comment]
Closing this as there seems to be no need (and also we now have an exact transformation when supplying `p0`).
