### ISSUE TITLE
Include `.gitattributes` file

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/effectsize#603]
E.g. GitHub thinks this is a `PostScript`, and not `R`, repo.

<img width="898" alt="Screenshot 2023-09-14 at 12 45 23" src="https://github.com/easystats/effectsize/assets/11330453/470f7f50-f15b-4a3c-99d6-9f430aed9521">

This can be avoided by using a gitattributes file. You can just copy-paste the file I have added to `{see}`:

https://github.com/easystats/see/commit/eccd98c37d3866355b593d474df339472d81d1b4

**Comment by mattansb** [comment]
Ew.

**Comment by mattansb** [comment]
Solved (:
