### ISSUE TITLE
calculating effect size in easystats in t-test

### ISSUE THREAD

**Issue by Niloofar-GH** [easystats/effectsize#632]
**Question and context**
Hi, 

Fisrt of all, thank you for your great website. I have one question. I wanted to calculated cohen's d based on t value (5.1) and df (23). Your website gave me 2.12 as d (partial). Is it the cohen's d? beacsue I used following formula in R : cohensd_fixduration <- round(2*t/sqrt(N-2),2   to get cohn's d (t:5.1 and sample size: 66) and I got cohn's d 0.63. I was wondering that maybe d paRTIAL is not cohen's d.

Kind regards, 
Niloofar

**Comment by bwiernik** [comment]
Can you please show your full code as a reproducible example?

**Comment by Niloofar-GH** [comment]
t(23)=5.1 . sample size=66

N = 66 #tot7al subject number (half per group)
t = 5.1 
cohensd_fixduration <- round(2*t/sqrt(N-2),2)
print(cohensd_fixduration)


[1] 1.27




But when I run it in easystats (I mean here : https://easystats4u.shinyapps.io/statistic2effectsize/_w_710741a3/#tab-6161-4)., it gives me 
![Screenshot (89)](https://github.com/easystats/effectsize/assets/160255328/8e47636d-7163-4b4d-b60d-9c75c09d26b3)

**Comment by bwiernik** [comment]
A two-samples t test with a sample size of 66 has 64 df, not 23. 

The "N-2" in the formula you are using is the df of the t test. Note that that formula only applies to an independent samples t test, not any other t statistic.

Either this is not an independent samples t or one or more of the numbers (23 or 66) is wrong.

**Comment by bwiernik** [comment]
If you enter 64 for the df in the easystats page, you will get 1.27 as a result.

**Comment by Niloofar-GH** [comment]
Thank you very much for explanation.
