### ISSUE TITLE
Effect sizes from test statistics

### ISSUE THREAD

**Issue by mattansb** [easystats/effectsize#7]
Here are some good ones that I use:
From [https://doi.org/10.1111%2F1467-9280.00287](https://doi.org/10.1111%2F1467-9280.00287)

```r
d_from_r <- function(r){
  (2 * r) / 
    sqrt(1 - r^2)
}

r_from_d <- function(d){
  d / 
    sqrt(4 + d^2)
}
```

(these two ^ are approximations, the rest are either exact, or practically exact)

From [https://doi.org/10.1177%2F001316448204200214](https://doi.org/10.1177%2F001316448204200214)
```r
partial_eta_sq_from_F <- function(F.ratio, df1, df2){
  (F.ratio * df1) /
    (F.ratio * df1 + df2)
}

partial_eta_sq_from_t <- function(t.ratio, df){
  partial_eta_sq_from_F(t.ratio^2, 1, df)
}

r_from_t <- function(t.ratio, df){
  # really this is a partial r, but it is usually just denoted by "r"
  sign(t.ratio) * sqrt(partial_eta_sq_from_t(t.ratio, df))
}

# thus...
d_from_t <- function(t.ratio, df){
  r <- r_from_t(t.ratio, df)
  d_from_r(r)
}
```
From [https://doi.org/10.1177%2F2515245919855053](https://doi.org/10.1177%2F2515245919855053)
```r
partial_epsilon_sq_from_F <- function(F.ratio, df1, df2){
  ((F.ratio - 1) * df1) /
    (F.ratio * df1 + df2)
}

adj_partial_eta_sq_from_F <- partial_epsilon_sq_from_F # love this!
```

From [http://daniellakens.blogspot.com/2015/06/why-you-should-use-omega-squared.html](http://daniellakens.blogspot.com/2015/06/why-you-should-use-omega-squared.html)
```r
partial_omega_sq_from_F <- function(F.tatio, df1, df2){
  ((F.tatio - 1) * df1) /
    (F.tatio * df1 + df2 + 1)
}
```

For contingency tables:
```r
phi_from_chisq <- function(chisq, N){
  sqrt(chisq / N)
}

cramers_V_from_chisq <- function(chisq, a, b, N){
  # a, b are the number of levels of the two factors
  phi_from_chisq(chisq, N) /
    (N * (min(a, b) - 1))
}
```

**Comment by DominiqueMakowski** [comment]
We already have the r <-> d ones, but the rest is 👍 Do you wanna make a PR with these (and make yourself as author) 😏?

**Comment by mattansb** [comment]
Sure 👍

**Comment by strengejacke** [comment]
See also https://strengejacke.github.io/esc/reference/hedges_g.html

Since you can convert from many effect sizes into many effect sizes, the idea was to have a function that returns a specific effect size, given any arbitrary effect size as argument.

**Comment by mattansb** [comment]
Done.
I haven't added `d_from_t` because strictly speaking I don't think it is "Cohen's d", but some other "d" - have to read more into it.

**Comment by mattansb** [comment]
@strengejacke Those are awesome!
Feel free to port them to `effectsize` 😋😉

**Comment by DominiqueMakowski** [comment]
> Since you can convert from many effect sizes into many effect sizes, the idea was to have a function that returns a specific effect size, given any arbitrary effect size as argument.


Indeed, that makes sense! However I'd go even further with a generic in the form `convert_effsize(value, from = "d", to "r")`, so it could be used "programmatically". An example usecase would be let's say you have a dataframe with the index type and values as columns, you might want to pass these columns to such function where the type and output is entered as a character (rather than as the argument name such as in `esc`)

**Comment by mattansb** [comment]
> However I'd go even further with a generic in the form convert_effsize(value, from = "d", to "r"), so it could be used "programmatically".

Yes! This would be super useful!

---

As far the the d from t... for a simple `y ~ between_2_groups` model, it does give a true Cohen's d. For everything else, it seems to give something close, but not 100% that (@strengejacke this is also true for your `cohens_d()` function).

How ever we do this, for Cohen's d (and log odds and OR) we should document well that these are only applicable to slopes and differences (cf. multi group F >> eta >> cohens d ***does not make sense***).

**Comment by strengejacke** [comment]
Just for the record, when doing meta-analysis, a typical workflow for me is to read the papers and copy the important information into a word table (study title, type of effect size measure, effect size etc.), then I import the word table into R (package docextractr) and just run this function on the created data frame:
https://strengejacke.github.io/esc/reference/effect_sizes.html
Then I have all data I need for metafor. Maybe we can have something like this here as well since it really supports easy workflows.

**Comment by mattansb** [comment]
@DominiqueMakowski 
I see you've changed the the partial variance explained from F/t doc to reflect that these are fro between-subject ANOVAs, but:
1. These also apply to mixed / within subject ANOVAs.
2. These apply to any statistical model.... In fact,
3. These apply to ***any*** F or t:

e.g., converting the t-value of a slope in a linear model to a partial eta square gives the partial correlation:

``` r
library(ppcor)
#> Warning: package 'ppcor' was built under R version 3.6.1
#> Loading required package: MASS
library(effectsize)

fit <- lm(Sepal.Length ~ Sepal.Width + Petal.Length, iris)
summary(fit)
#> 
#> Call:
#> lm(formula = Sepal.Length ~ Sepal.Width + Petal.Length, data = iris)
#> 
#> Residuals:
#>      Min       1Q   Median       3Q      Max 
#> -0.96159 -0.23489  0.00077  0.21453  0.78557 
#> 
#> Coefficients:
#>              Estimate Std. Error t value Pr(>|t|)    
#> (Intercept)   2.24914    0.24797    9.07 7.04e-16 ***
#> Sepal.Width   0.59552    0.06933    8.59 1.16e-14 ***
#> Petal.Length  0.47192    0.01712   27.57  < 2e-16 ***
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> 
#> Residual standard error: 0.3333 on 147 degrees of freedom
#> Multiple R-squared:  0.8402, Adjusted R-squared:  0.838 
#> F-statistic: 386.4 on 2 and 147 DF,  p-value: < 2.2e-16

t_to_partial_eta_squared(8.59, 147)
#> [1] 0.3342032

partial_cors <- pcor(iris[,1:3])$estimate
partial_cors[2,1]^2
#> [1] 0.3342001
```

<sup>Created on 2019-10-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I fear that framing these as "anova functions" will deter users from using them in other situations (contrasts, other omnibus F tests, etc...).

Also, "Convert between ANOVA indices (F, t, Eta squared, ...)" technically this is a one-way conversion fot F/t to partial variance explained measures (as it was stated before 😅).

**Comment by DominiqueMakowski** [comment]
> converting the t-value of a slope in a linear model to a partial eta square gives the partial correlation: 

Did not know that, seems very useful indeed!

> I fear that framing these as "anova functions" will deter users from using them in other situations

Agreed, will revert

**Comment by mattansb** [comment]
Another cool example for a repeated-measures correlation:

``` r
library(dplyr)
library(lmerTest)
library(effectsize)
library(rmcorr)

data(bland1995)

bland1995 <- bland1995 %>% 
  group_by(Subject) %>% 
  mutate(PacO2_s = PacO2 - mean(PacO2)) %>% 
  ungroup()
# fit a model with a random intercept
fit <- lmer(pH ~ PacO2_s + (1|Subject), data = bland1995)

summary(fit)
#> Linear mixed model fit by REML. t-tests use Satterthwaite's method [
#> lmerModLmerTest]
#> Formula: pH ~ PacO2_s + (1 | Subject)
#>    Data: bland1995
#> 
#> REML criterion at convergence: -51.2
#> 
#> Scaled residuals: 
#>      Min       1Q   Median       3Q      Max 
#> -2.29445 -0.35350  0.03818  0.48992  1.75836 
#> 
#> Random effects:
#>  Groups   Name        Variance Std.Dev.
#>  Subject  (Intercept) 0.086420 0.29397 
#>  Residual             0.008787 0.09374 
#> Number of obs: 47, groups:  Subject, 8
#> 
#> Fixed effects:
#>             Estimate Std. Error      df t value Pr(>|t|)    
#> (Intercept)   7.1121     0.1050  6.9585  67.761  4.5e-11 ***
#> PacO2_s      -0.1083     0.0299 37.9592  -3.623  0.00085 ***
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> 
#> Correlation of Fixed Effects:
#>         (Intr)
#> PacO2_s 0.000

t_to_partial_eta_squared(-3.623,37.9592)
#> [1] 0.2569452



rmc <- rmcorr(Subject, PacO2, pH, bland1995)
#> Warning in rmcorr(Subject, PacO2, pH, bland1995): 'Subject' coerced into a
#> factor
rmc$r^2
#> [1] 0.2568156
```

<sup>Created on 2019-10-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mattansb** [comment]
> Did not know that, seems very useful indeed!

It is! ^_^

**Comment by DominiqueMakowski** [comment]
@mattansb  "Convert between test statistics (F, t) to partial indices of variance explained (Eta squared, Omega Squared, ...)" ?

**Comment by mattansb** [comment]
Maybe:
"Convert test statistics (F, t) to indices of partial variance explained (partial Eta / Omega / Epsilon squared)"?

**Comment by strengejacke** [comment]
We could ping @IndrajeetPatil here, as he is interested in such stuff.

**Comment by DominiqueMakowski** [comment]
this correspondence between test statistics and indices of effect size is quite convenient in some cases... What would be the alternative for Bayesian models??

**Comment by DominiqueMakowski** [comment]
![image](https://user-images.githubusercontent.com/8875533/66704214-6d62ce00-ed4c-11e9-9a54-2d3d8a8d1d07.png)

An expert of formulae formatting is required 😁

**Comment by strengejacke** [comment]
Is this from the pdf or the r inline help? Latter only accepts HTML, I think. Does the help for get_variance help?

https://github.com/easystats/insight/blob/master/R/get_variances.R

**Comment by mattansb** [comment]
@strengejacke This is from the `?t_to_partial_eta_squared`. If anyone can re-write it so it's readable, let me know and I'll check the formulae (:

---

> this correspondence between test statistics and indices of effect size is quite convenient in some cases... What would be the alternative for Bayesian models??

Unfortunately, there isn't any... It seems like any effect sized in a Bayes framework actually needs to be computed from the posteriors ([even when it's simple, it's hard](https://discourse.mc-stan.org/t/obtaining-effect-size-from-rstanarm-packages-linear-regression/3601/3)... good luck...).
Generally, there seems to be very little work on standardized effect sizes in Bayesian modeling. This is probably because up until recently most users of Bayes were high-level stats / modeling users who ~felt they were above the dumb social sci needs~ were not interested in standardized anything.

But I read some tweet (or maybe on the JASP forum?) that the JASP team is working on some partial eta square / beta stuff...

**Comment by mattansb** [comment]
_regarding `convert_t_to_d`_

I came across the idea that for repeated measures, there are two forms of Cohen's D:
1. Accounting for the covariance (pretending data is from independent samples).
2. Not accounting for the covariance.

(see for example calculators 4 and 5 [here](http://www.psychometrica.de/effect_size.html)).

For us, `convert_t_to_d` always returns the first (the one that pretends the t-value is the result of an independent t-test).

(For fun, ran a small simulation)
![image](https://user-images.githubusercontent.com/35330040/66826064-44ad2500-ef54-11e9-92e0-8a0be038a0b5.png)

Thus, suggesting changing `convert_t_to_d` to:

```R
convert_t_to_d <- function(t, df_error, pooled = FALSE) {
  if (isTRUE(pooled)) {
    t / sqrt(df_error)
  } else {
    2 * t / sqrt(df_error)
  }
}
```
Any ideas how to explain this in the documentation...?

**Comment by mattansb** [comment]
Done.
I've also split the documentation so there's:
1. Convert between ESs
2. F,t,z to Cohen's d and (partial) r
3. F,t to partial variance explained
4. Chisq to phi / Cramer's V

I think this issue can be closed at this point.

**Comment by strengejacke** [comment]
@mattansb 

> @strengejacke Those are awesome!
> Feel free to port them to effectsize 😋😉

I was on vacation until yesterday, that's why I was inactive the past days. I think in the course of this week I can start working on our packages again...

**Comment by DominiqueMakowski** [comment]
the return of the jedi

**Comment by mattansb** [comment]
Or revenge of the Sith?

@strengejacke Welcome back!

@DominiqueMakowski does the heart on this [comment](https://github.com/easystats/effectsize/issues/7#issuecomment-542538304) mean it's okay to close this? Or just a symbol of you undying love to me? 😋

**Comment by DominiqueMakowski** [comment]
only my flaming love what else! and can close this too ;)
