### ISSUE TITLE
CI for standardized parameters 

### ISSUE THREAD

**Issue by mattansb** [easystats/effectsize#72]
I've added the option of getting CIs for `standardize_parameters`.

``` r
fit <- lm(mpg ~ ., mtcars)

effectsize::standardize_parameters(fit, method = "basic", ci = 0.95)
#> Parameter   | Coefficient (std.) |         95% CI
#> -------------------------------------------------
#> (Intercept) |               0.00 | [ 0.00,  0.00]
#> cyl         |              -0.03 | [-0.64,  0.57]
#> disp        |               0.27 | [-0.45,  0.99]
#> hp          |              -0.24 | [-0.73,  0.24]
#> drat        |               0.07 | [-0.21,  0.35]
#> wt          |              -0.60 | [-1.21,  0.00]
#> qsec        |               0.24 | [-0.18,  0.67]
#> vs          |               0.03 | [-0.32,  0.37]
#> am          |               0.21 | [-0.13,  0.54]
#> gear        |               0.08 | [-0.28,  0.44]
#> carb        |              -0.05 | [-0.49,  0.38]
```
However, to avoid infinite looping when calling `parameters::model_parameters(standardize = ...)`, I've set this to default `NULL`.

```R
effectsize::standardize_parameters(fit, method = "basic")
#> Parameter   | Coefficient (std.)
#> --------------------------------
#> (Intercept) |               0.00
#> cyl         |              -0.03
#> disp        |               0.27
#> hp          |              -0.24
#> drat        |               0.07
#> wt          |              -0.60
#> qsec        |               0.24
#> vs          |               0.03
#> am          |               0.21
#> gear        |               0.08
#> carb        |              -0.05

parameters::model_parameters(fit, standardize = "basic")
#> Parameter   | Coefficient (std.) |   SE |         95% CI |     t | df |     p
#> -----------------------------------------------------------------------------
#> (Intercept) |               0.00 | 0.00 | [ 0.00,  0.00] |  0.66 | 21 | 0.518
#> cyl         |              -0.03 | 0.31 | [-0.64,  0.57] | -0.11 | 21 | 0.916
#> disp        |               0.27 | 0.37 | [-0.45,  0.99] |  0.75 | 21 | 0.463
#> hp          |              -0.24 | 0.25 | [-0.73,  0.24] | -0.99 | 21 | 0.335
#> drat        |               0.07 | 0.15 | [-0.21,  0.35] |  0.48 | 21 | 0.635
#> wt          |              -0.60 | 0.31 | [-1.21,  0.00] | -1.96 | 21 | 0.063
#> qsec        |               0.24 | 0.22 | [-0.18,  0.67] |  1.12 | 21 | 0.274
#> vs          |               0.03 | 0.18 | [-0.32,  0.37] |  0.15 | 21 | 0.881
#> am          |               0.21 | 0.17 | [-0.13,  0.54] |  1.23 | 21 | 0.234
#> gear        |               0.08 | 0.18 | [-0.28,  0.44] |  0.44 | 21 | 0.665
#> carb        |              -0.05 | 0.22 | [-0.49,  0.38] | -0.24 | 21 | 0.812
```

@strengejacke Would be nice if calls to `standardize_parameters` in `parameters` could set `ci = NULL`, so that here I can de-`NULL` argument, as all other effect size function return CIs by default... What do you think?

**Comment by strengejacke** [comment]
Not sure if I need the `ci`-argument at the moment, because `model_parameters()` currently extracts the SE from attributes:

``` r
fit <- lm(mpg ~ ., mtcars)
str(effectsize::standardize_parameters(fit, method = "basic"))
#> Classes 'effectsize_std_params' and 'data.frame':    11 obs. of  2 variables:
#>  $ Parameter      : chr  "(Intercept)" "cyl" "disp" "hp" ...
#>  $ Std_Coefficient: num  0 -0.033 0.2742 -0.2444 0.0698 ...
#>  - attr(*, "standard_error")= num [1:11] 0 0.31 0.367 0.248 0.145 ...
```

<sup>Created on 2020-04-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Else, I would just pass down the `ci`-argument from `model_parameters()` to `effectsize::standardize_parameters()`, or what do you think?

**Comment by DominiqueMakowski** [comment]
> Else, I would just pass down the ci-argument from model_parameters() to effectsize::standardize_parameters(), or what do you think?

This sounds like the best option, as usually, we want the CI for the raw and standardized parameters to be consistent, so one `ci` arg seems the simplest

*flying back to his cave*

**Comment by strengejacke** [comment]
> This sounds like the best option, as usually, we want the CI for the raw and standardized parameters to be consistent, so one ci arg seems the simplest

Looks like you need a date with your hairdresser, else stay in your cave! 😄 
Yes, this is how we currently do it, just having one `ci` argument, and when `standardize` is not `NULL`, `ci` refers to the ci-level of the (standardized) coefficients. Everything else would indeed be nonsense, I'd say.

Changing this would take two release cycles: 1) effectsize needs to be updated, allowing both `ci` and returning the SE as attribute (to not break parameters code) - 2) parameters will be updated, using the `ci`-argument in `standardize_parameters()`. From the third release cycle, you can remove that attribute.

**Comment by mattansb** [comment]
Okay. I actually need to keep the SE attribute, as internally I use `parameters::ci` to get the CIs.

I went a head and made these changes. I will update effectsize in a few weeks, then you can update parameters.
Sounds good?

**Comment by mattansb** [comment]
Closing this, as I think this has been fully dealt with here and in parameters.

**Comment by strengejacke** [comment]
Yes I think so too
