### ISSUE TITLE
Automatic selection of effectsizes for cross tables

### ISSUE THREAD

**Issue by strengejacke** [easystats/effectsize#75]
Would be nice to have a function like [`sjstats::crosstable_statistics()`](https://strengejacke.github.io/sjstats/reference/crosstable_statistics.html) in _effectsize_.

**Comment by mattansb** [comment]
The "spearman", "kendall" and "pearson" effect sizes (which are not strictly xtab measures) are already supported in `correlation`.

And "fisher" only changes the computed p-value.

So this would just add a Chisq, df, and p value?
This seems like a job for `parameter`! 🦸‍♂️
Where `model_parameters.htest` could add also a phi / cramer's V?
https://github.com/easystats/parameters/issues/257

**Comment by mattansb** [comment]
*bump*

**Comment by strengejacke** [comment]
I think you can close this if implementation should happen in _parameters_. I must think about a nice `print()`-method, though.
