### ISSUE TITLE
base dependency issue

### ISSUE THREAD

**Issue by timbalam** [easystats/effectsize#83]
Hi! I have encountered the following issue: I am running an ancient version of R (3.4.4). When I try to call `cohens_f` I get the error:

    Error in isFALSE(partial) : could not find function "isFALSE" 

I believe that the problem is that `isFALSE` is only available for later versions of R (>= 3.5?). The CRAN package currently specifies a dependency on R >= 3.2.

To fix this, one could either increase the dependency, or add some sort of version check as in this similar issue I noticed:
https://github.com/r-spatial/mapview/issues/177#issuecomment-417035123
(Fix at this link:)
https://github.com/r-spatial/mapview/blob/8fe412b0b2510a0642b11c75e21a028dbf84f5c1/R/mapviewControls.R#L306-L312

Hope this helps,
Tim

**Comment by mattansb** [comment]
I've replaced all `isFALSE()` with `!isTRUE()`, which should work here.
