### ISSUE TITLE
effect size paper

### ISSUE THREAD

**Issue by mattansb** [easystats/effectsize#91]
## Estimating standardized effect sized and their confidence intervals using R

1. Effect sizes for linear models
    - eta / omega / epsilon
    - cohen's d / hedge's g / glass delta
    - standardized coefficiants 
      - Use in glms
2. Effect sizes for contingency tables
3. Effect sizes from test statistics
4. Conversion
5. Utils (standardization + rescaling) + Interpretation (?)

---

Will get to this later this summer

**Comment by DominiqueMakowski** [comment]
Title: I vote for: *"Size does matter: Estimation, conversion and interpretation of indices of effect size using R "* 🧨🧨  (I mainly care about the first part tho 😅). Maybe add something like "and uncertainty quantification" if you want to put the notion of CI in?

**Comment by strengejacke** [comment]
![0ed979fa79684a30a663f182b7142480](https://user-images.githubusercontent.com/26301769/86232265-f9937a80-bb93-11ea-9453-b46b6370df03.jpg)

Most important is _statement of need_ (not in the title, of course...).

**Comment by mattansb** [comment]
Sorry for the slowness on this, lots of things happening here (covid hit here pretty hard, with a big impact of university and academic life)...

I hope to get back to this soon enough.

**Comment by DominiqueMakowski** [comment]
No worries at all it's a tough year ^^ stay safe 🤗

**Comment by mattansb** [comment]
@strengejacke @DominiqueMakowski Basically done with first draft. 
Is it too long? (Still need to add more on ANOVAs)
Is anything missing?

**Comment by mattansb** [comment]
Alright, as far as I'm concerned, this is complete. ✔
You guys want to give this a look? (and also tell me how to submit?)

**Comment by DominiqueMakowski** [comment]
Are you ***sure*** you don't wanna change the title to *Size does matter: Estimation and Interpretation of Effect Size Indices and Standardized Parameters*? I think it's really worth considering; it's a once-in-a-lifetime opportunity and will surely increase the interest in the paper ^^

> and also tell me how to submit?

I think the paper branch should be merged to master, then you might wanna take a look at that:

https://joss.readthedocs.io/en/latest/review_checklist.html
https://joss.readthedocs.io/en/latest/submitting.html

Just to make sure everything is okay. The submission is done through the JOSS website.

I wonder if we shouldn't add a section about the `effectsize()` OP function and have like a "Usecase example" in which we apply an effectsize workflow, like fit an aov on the iris dataset -> apply effectsize() -> apply interpret to give a more concrete example (we could add this as the first example), but maybe it's useless

**Comment by mattansb** [comment]
[x] title change 😂
[x] JOSS submission guidelines
[x] demo `effectsize()` - I added, but in the "From Test Statistics" section because I don't see this as a work flow function, but as a "last resort because I'm not sure what I'm doing" function 😇

**Comment by mattansb** [comment]
So... I think we're ready. Any objections / thoughts?

**Comment by DominiqueMakowski** [comment]
You have my greenlight ✔️  awaiting master Daniel

**Comment by strengejacke** [comment]
Ok, did some minor changes, else looks very good!

**Comment by mattansb** [comment]
Submitting then 👍

**Comment by strengejacke** [comment]
What is actually the current state of submission?

**Comment by IndrajeetPatil** [comment]
Maybe this can be closed now that it is just a matter of time this will be published in _JOSS_? 😁 
https://joss.theoj.org/papers/10.21105/joss.02815

**Comment by mattansb** [comment]
Yup!
