### ISSUE TITLE
Perhaps a parsing error in correlation function? partial = FALSE did not generate an error, but partial=TRUE did.

### ISSUE THREAD

**Issue by curtisld** [easystats/effectsize#93]
cor <- correlation(monthly.epi.0612[c(5:13)],p.adjust = 'fdr',partial=TRUE)
Error in parse(text = x, keep.source = FALSE) : 
  <text>:1:13: unexpected symbol
1: Chlorophyll a
                ^

**Comment by strengejacke** [comment]
``` r
library(effectsize)

tmp <- data.frame("Chlorophyll a" = c(1.3,4.2,12.9,2.3,4.7,8.7,10.0,2.0,0.4,1.8,0.01,0.0114),
                  "Temperature" = c(6.3,5.6,6.7,9.8,13.2,16.8,18.3,19.6,19.5,16.7,12.4,8.5),
                  "Total Phosphorus" = c(0.027,0.022,0.012,0.014,0.011,0.027,0.028,0.010,0.010,0.007,0.009,0.017),
                  check.names = FALSE)

effectsize::adjust(tmp)
#> Error in str2lang(x): <text>:1:13: unexpected symbol
#> 1: Chlorophyll a
#>                 ^
```

<sup>Created on 2020-07-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
Not sure if this is actually a bug... If you use "proper" column names (i.e. w/o spaces), everything works fine:

``` r
library(correlation)
tmp <- data.frame("Chlorophyll.a" = c(1.3,4.2,12.9,2.3,4.7,8.7,10.0,2.0,0.4,1.8,0.01,0.0114),
                  "Temperature" = c(6.3,5.6,6.7,9.8,13.2,16.8,18.3,19.6,19.5,16.7,12.4,8.5),
                  "Total.Phosphorus" = c(0.027,0.022,0.012,0.014,0.011,0.027,0.028,0.010,0.010,0.007,0.009,0.017),
                  check.names = FALSE)

correlation(tmp,p.adjust = 'fdr',partial=FALSE)
#> Parameter1    |       Parameter2 |     r |        95% CI |     t | df |     p |  Method | n_Obs
#> -----------------------------------------------------------------------------------------------
#> Chlorophyll.a |      Temperature | -0.03 | [-0.60, 0.55] | -0.11 | 10 | 1.000 | Pearson |    12
#> Chlorophyll.a | Total.Phosphorus |  0.37 | [-0.26, 0.78] |  1.27 | 10 | 0.700 | Pearson |    12
#> Temperature   | Total.Phosphorus | -0.21 | [-0.70, 0.42] | -0.66 | 10 | 1.000 | Pearson |    12

correlation(tmp,p.adjust = 'fdr',partial=TRUE)
#> Parameter1    |       Parameter2 |     r |        95% CI |     t | df |     p |  Method | n_Obs
#> -----------------------------------------------------------------------------------------------
#> Chlorophyll.a |      Temperature |  0.05 | [-0.54, 0.60] |  0.15 | 10 | 1.000 | Pearson |    12
#> Chlorophyll.a | Total.Phosphorus |  0.37 | [-0.26, 0.78] |  1.27 | 10 | 0.695 | Pearson |    12
#> Temperature   | Total.Phosphorus | -0.21 | [-0.70, 0.42] | -0.67 | 10 | 1.000 | Pearson |    12
```

<sup>Created on 2020-07-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


I suggest closing this as invalid...

**Comment by DominiqueMakowski** [comment]
@curtisld yes, I'd add that indeed having spaces in names is generally considered a not so good practice. I'd suggest replacing all spaces in your column names by for instance underscores or something like that so you'll avoid future issues.

**Comment by mattansb** [comment]
@DominiqueMakowski Should we try and fix this with `make.names()`?

**Comment by strengejacke** [comment]
I thought about this, too. But I'm not sure if we manipulate the names of the columns, there might be problems in subsequent functions where `adjust()` is just a "pass through" function. This seems to be a hassle to deal with "non syntactic column" names which is difficult to maintain, and possible problems with other functions are hard to anticipate.

At most, we could check if `all(colnames(data) == colnames(make.names(data))`, and if not, throw a warning.

**Comment by mattansb** [comment]
I looked into this - we don't manipulate the names of the columns, the error is due to the formula parsing of the non-name column names.
We could circumvent this by making all formulas:
![image](https://user-images.githubusercontent.com/35330040/86437583-79912000-bd0d-11ea-832c-7dc6a481bf81.png)
but I'm not sure how this will effect things down the line. Leaving as is for now.

**Comment by strengejacke** [comment]
> we don't manipulate the names

Yes, I know. But we would do this when use `make.names`, and since we return the data frame with the column names in the formula, we would return a data frame with different column names as the original input.

**Comment by strengejacke** [comment]
Alternatively, you could check the column names for syntactically valid names, and wrap all non-syntactically names into backticks for the formula. But I thought that was too much of a hassle.

**Comment by DominiqueMakowski** [comment]
I think an informative warning makes sense here, as the user using spaces in colnames is likely to encounter more problems down the road. And somehow it's part of the "helping with good practices" mission that is somewhat tangent to our endeavour.

**Comment by mattansb** [comment]
Something like?
```R
if (!all(colnames(data) == make.names(colnames(data), unique = TRUE))) {
  warning("Some column names are not proper names (see `make.names()`),\n",
          "and might not be parsed correctly.", 
          call. = FALSE)
}
```

In the beginning of `adjust()`?

**Comment by DominiqueMakowski** [comment]
Yeah, or:

```
"We detected bad column names (e.g., with spaces) which will create issues in many functions.",
" Please fix it (you can run `names(mydata) <- make.names(names(mydata))` for an automatic fix)."
```

More verbose but provides a direct fix to the user
